// Code generated by gen/gen_chunkstatus.go from 26.3/registries.json; DO NOT EDIT.

package level

// ChunkStatus is how far a chunk's generation has come: the value of a saved
// chunk's `Status` tag, and an entry of the minecraft:chunk_status registry.
// The constants are in generation order, StatusEmpty first and StatusFull last;
// a version adds, removes and renames them, so compare with these rather than
// with a string literal.
type ChunkStatus string

const (
	StatusEmpty               ChunkStatus = "empty"
	StatusStructureStarts     ChunkStatus = "structure_starts"
	StatusStructureReferences ChunkStatus = "structure_references"
	StatusBiomes              ChunkStatus = "biomes"
	StatusTerrain             ChunkStatus = "terrain"
	StatusFeatures            ChunkStatus = "features"
	StatusInitializeLight     ChunkStatus = "initialize_light"
	StatusLight               ChunkStatus = "light"
	StatusSpawn               ChunkStatus = "spawn"
	StatusFull                ChunkStatus = "full"
)

// ChunkStatuses lists every status of this version in generation order.
var ChunkStatuses = []ChunkStatus{
	StatusEmpty,
	StatusStructureStarts,
	StatusStructureReferences,
	StatusBiomes,
	StatusTerrain,
	StatusFeatures,
	StatusInitializeLight,
	StatusLight,
	StatusSpawn,
	StatusFull,
}
