// Code generated by gen/gen_packets.go from 26.3/packet_schema.json; DO NOT EDIT.
package level

import (
	"io"

	"github.com/mj41/go-mc26/level/biome"
	"github.com/mj41/go-mc26/level/block"
	pk "github.com/mj41/go-mc26/net/packet"
	"github.com/mj41/go-mc26/wire"
)

var _ = io.EOF

// PalettedContainerBiomesDataWidth is the storage width, in bits per value, that the palette byte of
// PalettedContainerBiomes.Data selects: what prims.json says of the run, the width of a global palette
// being the bits of the id space's size.
func PalettedContainerBiomesDataWidth(bits int) int {
	switch bits {
	case 0:
		return 0
	case 1:
		return 1
	case 2:
		return 2
	case 3:
		return 3
	}
	return biome.BitsPerBiome
}

// PalettedContainerBlockStatesDataWidth is the storage width, in bits per value, that the palette byte of
// PalettedContainerBlockStates.Data selects: what prims.json says of the run, the width of a global palette
// being the bits of the id space's size.
func PalettedContainerBlockStatesDataWidth(bits int) int {
	switch bits {
	case 0:
		return 0
	case 1, 2, 3, 4:
		return 4
	case 5:
		return 5
	case 6:
		return 6
	case 7:
		return 7
	case 8:
		return 8
	}
	return block.BitsPerBlock
}

// PalettedContainerBlockStates is Java PalettedContainer$BlockStates.
type PalettedContainerBlockStates struct {
	Bits    pk.Byte
	Single  pk.VarInt
	Palette wire.List[pk.VarInt, *pk.VarInt]
	Data    wire.Packed // 4096 values of the width Bits selects, in big-endian longs
}

func (v *PalettedContainerBlockStates) ReadFrom(r io.Reader) (n int64, err error) {
	var m int64
	m, err = pk.Tuple{&v.Bits}.ReadFrom(r)
	n += m
	if err != nil {
		return n, err
	}
	if v.Bits == 0 {
		m, err = pk.Tuple{&v.Single}.ReadFrom(r)
		n += m
		if err != nil {
			return n, err
		}
	}
	if v.Bits >= 1 && v.Bits <= 8 {
		m, err = pk.Tuple{&v.Palette}.ReadFrom(r)
		n += m
		if err != nil {
			return n, err
		}
	}
	m, err = pk.Tuple{wire.PackedOf(&v.Data, 4096, PalettedContainerBlockStatesDataWidth(int(v.Bits)))}.ReadFrom(r)
	n += m
	if err != nil {
		return n, err
	}
	return n, nil
}

func (v PalettedContainerBlockStates) WriteTo(w io.Writer) (n int64, err error) {
	var m int64
	m, err = pk.Tuple{v.Bits}.WriteTo(w)
	n += m
	if err != nil {
		return n, err
	}
	if v.Bits == 0 {
		m, err = pk.Tuple{v.Single}.WriteTo(w)
		n += m
		if err != nil {
			return n, err
		}
	}
	if v.Bits >= 1 && v.Bits <= 8 {
		m, err = pk.Tuple{v.Palette}.WriteTo(w)
		n += m
		if err != nil {
			return n, err
		}
	}
	m, err = pk.Tuple{wire.PackedOf(&v.Data, 4096, PalettedContainerBlockStatesDataWidth(int(v.Bits)))}.WriteTo(w)
	n += m
	if err != nil {
		return n, err
	}
	return n, nil
}

// PalettedContainerBiomes is Java PalettedContainer$Biomes.
type PalettedContainerBiomes struct {
	Bits    pk.Byte
	Single  pk.VarInt
	Palette wire.List[pk.VarInt, *pk.VarInt]
	Data    wire.Packed // 64 values of the width Bits selects, in big-endian longs
}

func (v *PalettedContainerBiomes) ReadFrom(r io.Reader) (n int64, err error) {
	var m int64
	m, err = pk.Tuple{&v.Bits}.ReadFrom(r)
	n += m
	if err != nil {
		return n, err
	}
	if v.Bits == 0 {
		m, err = pk.Tuple{&v.Single}.ReadFrom(r)
		n += m
		if err != nil {
			return n, err
		}
	}
	if v.Bits >= 1 && v.Bits <= 3 {
		m, err = pk.Tuple{&v.Palette}.ReadFrom(r)
		n += m
		if err != nil {
			return n, err
		}
	}
	m, err = pk.Tuple{wire.PackedOf(&v.Data, 64, PalettedContainerBiomesDataWidth(int(v.Bits)))}.ReadFrom(r)
	n += m
	if err != nil {
		return n, err
	}
	return n, nil
}

func (v PalettedContainerBiomes) WriteTo(w io.Writer) (n int64, err error) {
	var m int64
	m, err = pk.Tuple{v.Bits}.WriteTo(w)
	n += m
	if err != nil {
		return n, err
	}
	if v.Bits == 0 {
		m, err = pk.Tuple{v.Single}.WriteTo(w)
		n += m
		if err != nil {
			return n, err
		}
	}
	if v.Bits >= 1 && v.Bits <= 3 {
		m, err = pk.Tuple{v.Palette}.WriteTo(w)
		n += m
		if err != nil {
			return n, err
		}
	}
	m, err = pk.Tuple{wire.PackedOf(&v.Data, 64, PalettedContainerBiomesDataWidth(int(v.Bits)))}.WriteTo(w)
	n += m
	if err != nil {
		return n, err
	}
	return n, nil
}

// LevelChunkSection is Java LevelChunkSection.
type LevelChunkSection struct {
	NonEmptyBlockCount pk.Short
	FluidCount         pk.Short
	States             PalettedContainerBlockStates
	Biomes             PalettedContainerBiomes
}

func (v *LevelChunkSection) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.NonEmptyBlockCount, &v.FluidCount, &v.States, &v.Biomes}.ReadFrom(r)
}

func (v LevelChunkSection) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.NonEmptyBlockCount, v.FluidCount, v.States, v.Biomes}.WriteTo(w)
}
