// Code generated by gen/gen_blockentities.go from 26.2/block_entities.json; DO NOT EDIT.

package block

var EntityList = [...]Entity{
	BannerEntity{},
	BarrelEntity{},
	BeaconEntity{},
	BeehiveEntity{},
	BellEntity{},
	BlastFurnaceEntity{},
	BrewingStandEntity{},
	BrushableBlockEntity{},
	CalibratedSculkSensorEntity{},
	CampfireEntity{},
	ChestEntity{},
	ChiseledBookshelfEntity{},
	CommandBlockEntity{},
	ComparatorEntity{},
	ConduitEntity{},
	CopperGolemStatueEntity{},
	CrafterEntity{},
	CreakingHeartEntity{},
	DaylightDetectorEntity{},
	DecoratedPotEntity{},
	DispenserEntity{},
	DropperEntity{},
	EnchantingTableEntity{},
	EndGatewayEntity{},
	EndPortalEntity{},
	EnderChestEntity{},
	FurnaceEntity{},
	HangingSignEntity{},
	HopperEntity{},
	JigsawEntity{},
	JukeboxEntity{},
	LecternEntity{},
	MobSpawnerEntity{},
	PistonEntity{},
	PotentSulfurEntity{},
	SculkCatalystEntity{},
	SculkSensorEntity{},
	SculkShriekerEntity{},
	ShelfEntity{},
	ShulkerBoxEntity{},
	SignEntity{},
	SkullEntity{},
	SmokerEntity{},
	StructureBlockEntity{},
	TestBlockEntity{},
	TestInstanceBlockEntity{},
	TrappedChestEntity{},
	TrialSpawnerEntity{},
	VaultEntity{},
}

func (BannerEntity) ID() string { return "minecraft:banner" }

func (BarrelEntity) ID() string { return "minecraft:barrel" }

func (BeaconEntity) ID() string { return "minecraft:beacon" }

func (BeehiveEntity) ID() string { return "minecraft:beehive" }

func (BellEntity) ID() string { return "minecraft:bell" }

func (BlastFurnaceEntity) ID() string { return "minecraft:blast_furnace" }

func (BrewingStandEntity) ID() string { return "minecraft:brewing_stand" }

func (BrushableBlockEntity) ID() string { return "minecraft:brushable_block" }

func (CalibratedSculkSensorEntity) ID() string { return "minecraft:calibrated_sculk_sensor" }

func (CampfireEntity) ID() string { return "minecraft:campfire" }

func (ChestEntity) ID() string { return "minecraft:chest" }

func (ChiseledBookshelfEntity) ID() string { return "minecraft:chiseled_bookshelf" }

func (CommandBlockEntity) ID() string { return "minecraft:command_block" }

func (ComparatorEntity) ID() string { return "minecraft:comparator" }

func (ConduitEntity) ID() string { return "minecraft:conduit" }

func (CopperGolemStatueEntity) ID() string { return "minecraft:copper_golem_statue" }

func (CrafterEntity) ID() string { return "minecraft:crafter" }

func (CreakingHeartEntity) ID() string { return "minecraft:creaking_heart" }

func (DaylightDetectorEntity) ID() string { return "minecraft:daylight_detector" }

func (DecoratedPotEntity) ID() string { return "minecraft:decorated_pot" }

func (DispenserEntity) ID() string { return "minecraft:dispenser" }

func (DropperEntity) ID() string { return "minecraft:dropper" }

func (EnchantingTableEntity) ID() string { return "minecraft:enchanting_table" }

func (EndGatewayEntity) ID() string { return "minecraft:end_gateway" }

func (EndPortalEntity) ID() string { return "minecraft:end_portal" }

func (EnderChestEntity) ID() string { return "minecraft:ender_chest" }

func (FurnaceEntity) ID() string { return "minecraft:furnace" }

func (HangingSignEntity) ID() string { return "minecraft:hanging_sign" }

func (HopperEntity) ID() string { return "minecraft:hopper" }

func (JigsawEntity) ID() string { return "minecraft:jigsaw" }

func (JukeboxEntity) ID() string { return "minecraft:jukebox" }

func (LecternEntity) ID() string { return "minecraft:lectern" }

func (MobSpawnerEntity) ID() string { return "minecraft:mob_spawner" }

func (PistonEntity) ID() string { return "minecraft:piston" }

func (PotentSulfurEntity) ID() string { return "minecraft:potent_sulfur" }

func (SculkCatalystEntity) ID() string { return "minecraft:sculk_catalyst" }

func (SculkSensorEntity) ID() string { return "minecraft:sculk_sensor" }

func (SculkShriekerEntity) ID() string { return "minecraft:sculk_shrieker" }

func (ShelfEntity) ID() string { return "minecraft:shelf" }

func (ShulkerBoxEntity) ID() string { return "minecraft:shulker_box" }

func (SignEntity) ID() string { return "minecraft:sign" }

func (SkullEntity) ID() string { return "minecraft:skull" }

func (SmokerEntity) ID() string { return "minecraft:smoker" }

func (StructureBlockEntity) ID() string { return "minecraft:structure_block" }

func (TestBlockEntity) ID() string { return "minecraft:test_block" }

func (TestInstanceBlockEntity) ID() string { return "minecraft:test_instance_block" }

func (TrappedChestEntity) ID() string { return "minecraft:trapped_chest" }

func (TrialSpawnerEntity) ID() string { return "minecraft:trial_spawner" }

func (VaultEntity) ID() string { return "minecraft:vault" }

func (b BannerEntity) IsValidBlock(block Block) bool {
	switch block.ID() {
	case "minecraft:black_banner",
		"minecraft:black_wall_banner",
		"minecraft:blue_banner",
		"minecraft:blue_wall_banner",
		"minecraft:brown_banner",
		"minecraft:brown_wall_banner",
		"minecraft:cyan_banner",
		"minecraft:cyan_wall_banner",
		"minecraft:gray_banner",
		"minecraft:gray_wall_banner",
		"minecraft:green_banner",
		"minecraft:green_wall_banner",
		"minecraft:light_blue_banner",
		"minecraft:light_blue_wall_banner",
		"minecraft:light_gray_banner",
		"minecraft:light_gray_wall_banner",
		"minecraft:lime_banner",
		"minecraft:lime_wall_banner",
		"minecraft:magenta_banner",
		"minecraft:magenta_wall_banner",
		"minecraft:orange_banner",
		"minecraft:orange_wall_banner",
		"minecraft:pink_banner",
		"minecraft:pink_wall_banner",
		"minecraft:purple_banner",
		"minecraft:purple_wall_banner",
		"minecraft:red_banner",
		"minecraft:red_wall_banner",
		"minecraft:white_banner",
		"minecraft:white_wall_banner",
		"minecraft:yellow_banner",
		"minecraft:yellow_wall_banner":
		return true
	default:
		return false
	}
}

func (b BarrelEntity) IsValidBlock(block Block) bool {
	return block.ID() == "minecraft:barrel"
}

func (b BeaconEntity) IsValidBlock(block Block) bool {
	return block.ID() == "minecraft:beacon"
}

func (b BeehiveEntity) IsValidBlock(block Block) bool {
	switch block.ID() {
	case "minecraft:bee_nest",
		"minecraft:beehive":
		return true
	default:
		return false
	}
}

func (b BellEntity) IsValidBlock(block Block) bool {
	return block.ID() == "minecraft:bell"
}

func (b BlastFurnaceEntity) IsValidBlock(block Block) bool {
	return block.ID() == "minecraft:blast_furnace"
}

func (b BrewingStandEntity) IsValidBlock(block Block) bool {
	return block.ID() == "minecraft:brewing_stand"
}

func (b BrushableBlockEntity) IsValidBlock(block Block) bool {
	switch block.ID() {
	case "minecraft:suspicious_gravel",
		"minecraft:suspicious_sand":
		return true
	default:
		return false
	}
}

func (c CalibratedSculkSensorEntity) IsValidBlock(block Block) bool {
	return block.ID() == "minecraft:calibrated_sculk_sensor"
}

func (c CampfireEntity) IsValidBlock(block Block) bool {
	switch block.ID() {
	case "minecraft:campfire",
		"minecraft:soul_campfire":
		return true
	default:
		return false
	}
}

func (c ChestEntity) IsValidBlock(block Block) bool {
	switch block.ID() {
	case "minecraft:chest",
		"minecraft:copper_chest",
		"minecraft:exposed_copper_chest",
		"minecraft:oxidized_copper_chest",
		"minecraft:waxed_copper_chest",
		"minecraft:waxed_exposed_copper_chest",
		"minecraft:waxed_oxidized_copper_chest",
		"minecraft:waxed_weathered_copper_chest",
		"minecraft:weathered_copper_chest":
		return true
	default:
		return false
	}
}

func (c ChiseledBookshelfEntity) IsValidBlock(block Block) bool {
	return block.ID() == "minecraft:chiseled_bookshelf"
}

func (c CommandBlockEntity) IsValidBlock(block Block) bool {
	switch block.ID() {
	case "minecraft:chain_command_block",
		"minecraft:command_block",
		"minecraft:repeating_command_block":
		return true
	default:
		return false
	}
}

func (c ComparatorEntity) IsValidBlock(block Block) bool {
	return block.ID() == "minecraft:comparator"
}

func (c ConduitEntity) IsValidBlock(block Block) bool {
	return block.ID() == "minecraft:conduit"
}

func (c CopperGolemStatueEntity) IsValidBlock(block Block) bool {
	switch block.ID() {
	case "minecraft:copper_golem_statue",
		"minecraft:exposed_copper_golem_statue",
		"minecraft:oxidized_copper_golem_statue",
		"minecraft:waxed_copper_golem_statue",
		"minecraft:waxed_exposed_copper_golem_statue",
		"minecraft:waxed_oxidized_copper_golem_statue",
		"minecraft:waxed_weathered_copper_golem_statue",
		"minecraft:weathered_copper_golem_statue":
		return true
	default:
		return false
	}
}

func (c CrafterEntity) IsValidBlock(block Block) bool {
	return block.ID() == "minecraft:crafter"
}

func (c CreakingHeartEntity) IsValidBlock(block Block) bool {
	return block.ID() == "minecraft:creaking_heart"
}

func (d DaylightDetectorEntity) IsValidBlock(block Block) bool {
	return block.ID() == "minecraft:daylight_detector"
}

func (d DecoratedPotEntity) IsValidBlock(block Block) bool {
	return block.ID() == "minecraft:decorated_pot"
}

func (d DispenserEntity) IsValidBlock(block Block) bool {
	return block.ID() == "minecraft:dispenser"
}

func (d DropperEntity) IsValidBlock(block Block) bool {
	return block.ID() == "minecraft:dropper"
}

func (e EnchantingTableEntity) IsValidBlock(block Block) bool {
	return block.ID() == "minecraft:enchanting_table"
}

func (e EndGatewayEntity) IsValidBlock(block Block) bool {
	return block.ID() == "minecraft:end_gateway"
}

func (e EndPortalEntity) IsValidBlock(block Block) bool {
	return block.ID() == "minecraft:end_portal"
}

func (e EnderChestEntity) IsValidBlock(block Block) bool {
	return block.ID() == "minecraft:ender_chest"
}

func (f FurnaceEntity) IsValidBlock(block Block) bool {
	return block.ID() == "minecraft:furnace"
}

func (h HangingSignEntity) IsValidBlock(block Block) bool {
	switch block.ID() {
	case "minecraft:acacia_hanging_sign",
		"minecraft:acacia_wall_hanging_sign",
		"minecraft:bamboo_hanging_sign",
		"minecraft:bamboo_wall_hanging_sign",
		"minecraft:birch_hanging_sign",
		"minecraft:birch_wall_hanging_sign",
		"minecraft:cherry_hanging_sign",
		"minecraft:cherry_wall_hanging_sign",
		"minecraft:crimson_hanging_sign",
		"minecraft:crimson_wall_hanging_sign",
		"minecraft:dark_oak_hanging_sign",
		"minecraft:dark_oak_wall_hanging_sign",
		"minecraft:jungle_hanging_sign",
		"minecraft:jungle_wall_hanging_sign",
		"minecraft:mangrove_hanging_sign",
		"minecraft:mangrove_wall_hanging_sign",
		"minecraft:oak_hanging_sign",
		"minecraft:oak_wall_hanging_sign",
		"minecraft:pale_oak_hanging_sign",
		"minecraft:pale_oak_wall_hanging_sign",
		"minecraft:spruce_hanging_sign",
		"minecraft:spruce_wall_hanging_sign",
		"minecraft:warped_hanging_sign",
		"minecraft:warped_wall_hanging_sign":
		return true
	default:
		return false
	}
}

func (h HopperEntity) IsValidBlock(block Block) bool {
	return block.ID() == "minecraft:hopper"
}

func (j JigsawEntity) IsValidBlock(block Block) bool {
	return block.ID() == "minecraft:jigsaw"
}

func (j JukeboxEntity) IsValidBlock(block Block) bool {
	return block.ID() == "minecraft:jukebox"
}

func (l LecternEntity) IsValidBlock(block Block) bool {
	return block.ID() == "minecraft:lectern"
}

func (m MobSpawnerEntity) IsValidBlock(block Block) bool {
	return block.ID() == "minecraft:spawner"
}

func (p PistonEntity) IsValidBlock(block Block) bool {
	return block.ID() == "minecraft:moving_piston"
}

func (p PotentSulfurEntity) IsValidBlock(block Block) bool {
	return block.ID() == "minecraft:potent_sulfur"
}

func (s SculkCatalystEntity) IsValidBlock(block Block) bool {
	return block.ID() == "minecraft:sculk_catalyst"
}

func (s SculkSensorEntity) IsValidBlock(block Block) bool {
	return block.ID() == "minecraft:sculk_sensor"
}

func (s SculkShriekerEntity) IsValidBlock(block Block) bool {
	return block.ID() == "minecraft:sculk_shrieker"
}

func (s ShelfEntity) IsValidBlock(block Block) bool {
	switch block.ID() {
	case "minecraft:acacia_shelf",
		"minecraft:bamboo_shelf",
		"minecraft:birch_shelf",
		"minecraft:cherry_shelf",
		"minecraft:crimson_shelf",
		"minecraft:dark_oak_shelf",
		"minecraft:jungle_shelf",
		"minecraft:mangrove_shelf",
		"minecraft:oak_shelf",
		"minecraft:pale_oak_shelf",
		"minecraft:spruce_shelf",
		"minecraft:warped_shelf":
		return true
	default:
		return false
	}
}

func (s ShulkerBoxEntity) IsValidBlock(block Block) bool {
	switch block.ID() {
	case "minecraft:black_shulker_box",
		"minecraft:blue_shulker_box",
		"minecraft:brown_shulker_box",
		"minecraft:cyan_shulker_box",
		"minecraft:gray_shulker_box",
		"minecraft:green_shulker_box",
		"minecraft:light_blue_shulker_box",
		"minecraft:light_gray_shulker_box",
		"minecraft:lime_shulker_box",
		"minecraft:magenta_shulker_box",
		"minecraft:orange_shulker_box",
		"minecraft:pink_shulker_box",
		"minecraft:purple_shulker_box",
		"minecraft:red_shulker_box",
		"minecraft:shulker_box",
		"minecraft:white_shulker_box",
		"minecraft:yellow_shulker_box":
		return true
	default:
		return false
	}
}

func (s SignEntity) IsValidBlock(block Block) bool {
	switch block.ID() {
	case "minecraft:acacia_sign",
		"minecraft:acacia_wall_sign",
		"minecraft:bamboo_sign",
		"minecraft:bamboo_wall_sign",
		"minecraft:birch_sign",
		"minecraft:birch_wall_sign",
		"minecraft:cherry_sign",
		"minecraft:cherry_wall_sign",
		"minecraft:crimson_sign",
		"minecraft:crimson_wall_sign",
		"minecraft:dark_oak_sign",
		"minecraft:dark_oak_wall_sign",
		"minecraft:jungle_sign",
		"minecraft:jungle_wall_sign",
		"minecraft:mangrove_sign",
		"minecraft:mangrove_wall_sign",
		"minecraft:oak_sign",
		"minecraft:oak_wall_sign",
		"minecraft:pale_oak_sign",
		"minecraft:pale_oak_wall_sign",
		"minecraft:spruce_sign",
		"minecraft:spruce_wall_sign",
		"minecraft:warped_sign",
		"minecraft:warped_wall_sign":
		return true
	default:
		return false
	}
}

func (s SkullEntity) IsValidBlock(block Block) bool {
	switch block.ID() {
	case "minecraft:creeper_head",
		"minecraft:creeper_wall_head",
		"minecraft:dragon_head",
		"minecraft:dragon_wall_head",
		"minecraft:piglin_head",
		"minecraft:piglin_wall_head",
		"minecraft:player_head",
		"minecraft:player_wall_head",
		"minecraft:skeleton_skull",
		"minecraft:skeleton_wall_skull",
		"minecraft:wither_skeleton_skull",
		"minecraft:wither_skeleton_wall_skull",
		"minecraft:zombie_head",
		"minecraft:zombie_wall_head":
		return true
	default:
		return false
	}
}

func (s SmokerEntity) IsValidBlock(block Block) bool {
	return block.ID() == "minecraft:smoker"
}

func (s StructureBlockEntity) IsValidBlock(block Block) bool {
	return block.ID() == "minecraft:structure_block"
}

func (t TestBlockEntity) IsValidBlock(block Block) bool {
	return block.ID() == "minecraft:test_block"
}

func (t TestInstanceBlockEntity) IsValidBlock(block Block) bool {
	return block.ID() == "minecraft:test_instance_block"
}

func (t TrappedChestEntity) IsValidBlock(block Block) bool {
	return block.ID() == "minecraft:trapped_chest"
}

func (t TrialSpawnerEntity) IsValidBlock(block Block) bool {
	return block.ID() == "minecraft:trial_spawner"
}

func (v VaultEntity) IsValidBlock(block Block) bool {
	return block.ID() == "minecraft:vault"
}
