// Code generated by gen/gen_nbt.go from 26.1/nbt_schema.json; DO NOT EDIT.

// The elements of the registries a server sends in the configuration phase
// (RegistryDataLoader.SYNCHRONIZED_REGISTRIES), typed from their codecs.
//
// Fields the schema cannot type, kept as raw NBT:
//
//	minecraft:dimension_type.(monsterSettings).monster_spawn_light_level: either INT or dispatch IntProviders
//	minecraft:timeline.time_markers/val: either INT or struct Timeline$TimeMarkerInfo
package registry

import (
	"github.com/mj41/go-mc26/chat"
	"github.com/mj41/go-mc26/nbt"
)

// BiomeSpecialEffectsGrassColorModifier is Java BiomeSpecialEffects$GrassColorModifier, stored as its serialized name.
type BiomeSpecialEffectsGrassColorModifier string

const (
	BiomeSpecialEffectsGrassColorModifierNone       BiomeSpecialEffectsGrassColorModifier = "none"
	BiomeSpecialEffectsGrassColorModifierDarkForest BiomeSpecialEffectsGrassColorModifier = "dark_forest"
	BiomeSpecialEffectsGrassColorModifierSwamp      BiomeSpecialEffectsGrassColorModifier = "swamp"
)

// BiomeSpecialEffectsGrassColorModifierValues lists the constants in declaration order (the ordinals).
var BiomeSpecialEffectsGrassColorModifierValues = []BiomeSpecialEffectsGrassColorModifier{BiomeSpecialEffectsGrassColorModifierNone, BiomeSpecialEffectsGrassColorModifierDarkForest, BiomeSpecialEffectsGrassColorModifierSwamp}

// BiomeTemperatureModifier is Java Biome$TemperatureModifier, stored as its serialized name.
type BiomeTemperatureModifier string

const (
	BiomeTemperatureModifierNone   BiomeTemperatureModifier = "none"
	BiomeTemperatureModifierFrozen BiomeTemperatureModifier = "frozen"
)

// BiomeTemperatureModifierValues lists the constants in declaration order (the ordinals).
var BiomeTemperatureModifierValues = []BiomeTemperatureModifier{BiomeTemperatureModifierNone, BiomeTemperatureModifierFrozen}

// CardinalLightingType is Java CardinalLighting$Type, stored as its serialized name.
type CardinalLightingType string

const (
	CardinalLightingTypeDefault CardinalLightingType = "default"
	CardinalLightingTypeNether  CardinalLightingType = "nether"
)

// CardinalLightingTypeValues lists the constants in declaration order (the ordinals).
var CardinalLightingTypeValues = []CardinalLightingType{CardinalLightingTypeDefault, CardinalLightingTypeNether}

// ChickenVariantModelType is Java ChickenVariant$ModelType, stored as its serialized name.
type ChickenVariantModelType string

const (
	ChickenVariantModelTypeNormal ChickenVariantModelType = "normal"
	ChickenVariantModelTypeCold   ChickenVariantModelType = "cold"
)

// ChickenVariantModelTypeValues lists the constants in declaration order (the ordinals).
var ChickenVariantModelTypeValues = []ChickenVariantModelType{ChickenVariantModelTypeNormal, ChickenVariantModelTypeCold}

// CowVariantModelType is Java CowVariant$ModelType, stored as its serialized name.
type CowVariantModelType string

const (
	CowVariantModelTypeNormal CowVariantModelType = "normal"
	CowVariantModelTypeCold   CowVariantModelType = "cold"
	CowVariantModelTypeWarm   CowVariantModelType = "warm"
)

// CowVariantModelTypeValues lists the constants in declaration order (the ordinals).
var CowVariantModelTypeValues = []CowVariantModelType{CowVariantModelTypeNormal, CowVariantModelTypeCold, CowVariantModelTypeWarm}

// DamageEffects is Java DamageEffects, stored as its serialized name.
type DamageEffects string

const (
	DamageEffectsHurt     DamageEffects = "hurt"
	DamageEffectsThorns   DamageEffects = "thorns"
	DamageEffectsDrowning DamageEffects = "drowning"
	DamageEffectsBurning  DamageEffects = "burning"
	DamageEffectsPoking   DamageEffects = "poking"
	DamageEffectsFreezing DamageEffects = "freezing"
)

// DamageEffectsValues lists the constants in declaration order (the ordinals).
var DamageEffectsValues = []DamageEffects{DamageEffectsHurt, DamageEffectsThorns, DamageEffectsDrowning, DamageEffectsBurning, DamageEffectsPoking, DamageEffectsFreezing}

// DamageScaling is Java DamageScaling, stored as its serialized name.
type DamageScaling string

const (
	DamageScalingNever                       DamageScaling = "never"
	DamageScalingWhenCausedByLivingNonPlayer DamageScaling = "when_caused_by_living_non_player"
	DamageScalingAlways                      DamageScaling = "always"
)

// DamageScalingValues lists the constants in declaration order (the ordinals).
var DamageScalingValues = []DamageScaling{DamageScalingNever, DamageScalingWhenCausedByLivingNonPlayer, DamageScalingAlways}

// DeathMessageType is Java DeathMessageType, stored as its serialized name.
type DeathMessageType string

const (
	DeathMessageTypeDefault               DeathMessageType = "default"
	DeathMessageTypeFallVariants          DeathMessageType = "fall_variants"
	DeathMessageTypeIntentionalGameDesign DeathMessageType = "intentional_game_design"
)

// DeathMessageTypeValues lists the constants in declaration order (the ordinals).
var DeathMessageTypeValues = []DeathMessageType{DeathMessageTypeDefault, DeathMessageTypeFallVariants, DeathMessageTypeIntentionalGameDesign}

// DialogAction is Java DialogAction, stored as its serialized name.
type DialogAction string

const (
	DialogActionClose           DialogAction = "close"
	DialogActionNone            DialogAction = "none"
	DialogActionWaitForResponse DialogAction = "wait_for_response"
)

// DialogActionValues lists the constants in declaration order (the ordinals).
var DialogActionValues = []DialogAction{DialogActionClose, DialogActionNone, DialogActionWaitForResponse}

// DimensionTypeSkybox is Java DimensionType$Skybox, stored as its serialized name.
type DimensionTypeSkybox string

const (
	DimensionTypeSkyboxNone      DimensionTypeSkybox = "none"
	DimensionTypeSkyboxOverworld DimensionTypeSkybox = "overworld"
	DimensionTypeSkyboxEnd       DimensionTypeSkybox = "end"
)

// DimensionTypeSkyboxValues lists the constants in declaration order (the ordinals).
var DimensionTypeSkyboxValues = []DimensionTypeSkybox{DimensionTypeSkyboxNone, DimensionTypeSkyboxOverworld, DimensionTypeSkyboxEnd}

// EquipmentSlotGroup is Java EquipmentSlotGroup, stored as its serialized name.
type EquipmentSlotGroup string

const (
	EquipmentSlotGroupAny      EquipmentSlotGroup = "any"
	EquipmentSlotGroupMainhand EquipmentSlotGroup = "mainhand"
	EquipmentSlotGroupOffhand  EquipmentSlotGroup = "offhand"
	EquipmentSlotGroupHand     EquipmentSlotGroup = "hand"
	EquipmentSlotGroupFeet     EquipmentSlotGroup = "feet"
	EquipmentSlotGroupLegs     EquipmentSlotGroup = "legs"
	EquipmentSlotGroupChest    EquipmentSlotGroup = "chest"
	EquipmentSlotGroupHead     EquipmentSlotGroup = "head"
	EquipmentSlotGroupArmor    EquipmentSlotGroup = "armor"
	EquipmentSlotGroupBody     EquipmentSlotGroup = "body"
	EquipmentSlotGroupSaddle   EquipmentSlotGroup = "saddle"
)

// EquipmentSlotGroupValues lists the constants in declaration order (the ordinals).
var EquipmentSlotGroupValues = []EquipmentSlotGroup{EquipmentSlotGroupAny, EquipmentSlotGroupMainhand, EquipmentSlotGroupOffhand, EquipmentSlotGroupHand, EquipmentSlotGroupFeet, EquipmentSlotGroupLegs, EquipmentSlotGroupChest, EquipmentSlotGroupHead, EquipmentSlotGroupArmor, EquipmentSlotGroupBody, EquipmentSlotGroupSaddle}

// PigVariantModelType is Java PigVariant$ModelType, stored as its serialized name.
type PigVariantModelType string

const (
	PigVariantModelTypeNormal PigVariantModelType = "normal"
	PigVariantModelTypeCold   PigVariantModelType = "cold"
)

// PigVariantModelTypeValues lists the constants in declaration order (the ordinals).
var PigVariantModelTypeValues = []PigVariantModelType{PigVariantModelTypeNormal, PigVariantModelTypeCold}

// Rotation is Java Rotation, stored as its serialized name.
type Rotation string

const (
	RotationNone               Rotation = "none"
	RotationClockwise90        Rotation = "clockwise_90"
	RotationClockwise180       Rotation = "180"
	RotationCounterclockwise90 Rotation = "counterclockwise_90"
)

// RotationValues lists the constants in declaration order (the ordinals).
var RotationValues = []Rotation{RotationNone, RotationClockwise90, RotationClockwise180, RotationCounterclockwise90}

// TestEnvironmentDefinitionWeatherType is Java TestEnvironmentDefinition$Weather$Type, stored as its serialized name.
type TestEnvironmentDefinitionWeatherType string

const (
	TestEnvironmentDefinitionWeatherTypeClear   TestEnvironmentDefinitionWeatherType = "clear"
	TestEnvironmentDefinitionWeatherTypeRain    TestEnvironmentDefinitionWeatherType = "rain"
	TestEnvironmentDefinitionWeatherTypeThunder TestEnvironmentDefinitionWeatherType = "thunder"
)

// TestEnvironmentDefinitionWeatherTypeValues lists the constants in declaration order (the ordinals).
var TestEnvironmentDefinitionWeatherTypeValues = []TestEnvironmentDefinitionWeatherType{TestEnvironmentDefinitionWeatherTypeClear, TestEnvironmentDefinitionWeatherTypeRain, TestEnvironmentDefinitionWeatherTypeThunder}

// ZombieNautilusVariantModelType is Java ZombieNautilusVariant$ModelType, stored as its serialized name.
type ZombieNautilusVariantModelType string

const (
	ZombieNautilusVariantModelTypeNormal ZombieNautilusVariantModelType = "normal"
	ZombieNautilusVariantModelTypeWarm   ZombieNautilusVariantModelType = "warm"
)

// ZombieNautilusVariantModelTypeValues lists the constants in declaration order (the ordinals).
var ZombieNautilusVariantModelTypeValues = []ZombieNautilusVariantModelType{ZombieNautilusVariantModelTypeNormal, ZombieNautilusVariantModelTypeWarm}

// ActionButton is Java ActionButton ().
type ActionButton struct {
	CommonButtonData         // keys at this level
	Action           *Action `json:"action,omitempty" nbt:"action,omitempty"`
}

// BannerPattern is Java BannerPattern (the registry minecraft:banner_pattern).
type BannerPattern struct {
	AssetID        string `json:"asset_id" nbt:"asset_id"`
	TranslationKey string `json:"translation_key" nbt:"translation_key"`
}

// Biome is Java Biome (the registry minecraft:worldgen/biome).
type Biome struct {
	BiomeClimateSettings                           // keys at this level
	Attributes           map[string]nbt.RawMessage `json:"attributes,omitempty" nbt:"attributes,omitempty"` // keys: ids in minecraft:environment_attribute default EMPTY
	Effects              BiomeSpecialEffects       `json:"effects" nbt:"effects"`
}

// BiomeClimateSettings is Java Biome$ClimateSettings (inlined into Biome).
type BiomeClimateSettings struct {
	HasPrecipitation    bool                     `json:"has_precipitation" nbt:"has_precipitation"`
	Temperature         float32                  `json:"temperature" nbt:"temperature"`
	TemperatureModifier BiomeTemperatureModifier `json:"temperature_modifier,omitempty" nbt:"temperature_modifier,omitempty"` // default NONE
	Downfall            float32                  `json:"downfall" nbt:"downfall"`
}

// BiomeSpecialEffects is Java BiomeSpecialEffects ().
type BiomeSpecialEffects struct {
	WaterColor         Color                                 `json:"water_color" nbt:"water_color"`                                       // an int or "#rrggbb"
	FoliageColor       Color                                 `json:"foliage_color,omitempty" nbt:"foliage_color,omitempty"`               // an int or "#rrggbb"
	DryFoliageColor    Color                                 `json:"dry_foliage_color,omitempty" nbt:"dry_foliage_color,omitempty"`       // an int or "#rrggbb"
	GrassColor         Color                                 `json:"grass_color,omitempty" nbt:"grass_color,omitempty"`                   // an int or "#rrggbb"
	GrassColorModifier BiomeSpecialEffectsGrassColorModifier `json:"grass_color_modifier,omitempty" nbt:"grass_color_modifier,omitempty"` // default NONE
}

// CatSoundVariant is Java CatSoundVariant (the registry minecraft:cat_sound_variant).
type CatSoundVariant struct {
	AdultSounds CatSoundVariantCatSoundSet `json:"adult_sounds" nbt:"adult_sounds"`
	BabySounds  CatSoundVariantCatSoundSet `json:"baby_sounds" nbt:"baby_sounds"`
}

// CatSoundVariantCatSoundSet is Java CatSoundVariant$CatSoundSet ().
type CatSoundVariantCatSoundSet struct {
	AmbientSound      Holder[SoundEvent] `json:"ambient_sound" nbt:"ambient_sound"`             // an id in minecraft:sound_event or the inline element
	StrayAmbientSound Holder[SoundEvent] `json:"stray_ambient_sound" nbt:"stray_ambient_sound"` // an id in minecraft:sound_event or the inline element
	HissSound         Holder[SoundEvent] `json:"hiss_sound" nbt:"hiss_sound"`                   // an id in minecraft:sound_event or the inline element
	HurtSound         Holder[SoundEvent] `json:"hurt_sound" nbt:"hurt_sound"`                   // an id in minecraft:sound_event or the inline element
	DeathSound        Holder[SoundEvent] `json:"death_sound" nbt:"death_sound"`                 // an id in minecraft:sound_event or the inline element
	EatSound          Holder[SoundEvent] `json:"eat_sound" nbt:"eat_sound"`                     // an id in minecraft:sound_event or the inline element
	BegForFoodSound   Holder[SoundEvent] `json:"beg_for_food_sound" nbt:"beg_for_food_sound"`   // an id in minecraft:sound_event or the inline element
	PurrSound         Holder[SoundEvent] `json:"purr_sound" nbt:"purr_sound"`                   // an id in minecraft:sound_event or the inline element
	PurreowSound      Holder[SoundEvent] `json:"purreow_sound" nbt:"purreow_sound"`             // an id in minecraft:sound_event or the inline element
}

// CatVariant is Java CatVariant (the registry minecraft:cat_variant).
type CatVariant struct {
	AssetID     string `json:"asset_id" nbt:"asset_id"`
	BabyAssetID string `json:"baby_asset_id" nbt:"baby_asset_id"`
}

// ChatType is Java ChatType (the registry minecraft:chat_type).
type ChatType struct {
	Chat      chat.ChatTypeDecoration `json:"chat" nbt:"chat"`
	Narration chat.ChatTypeDecoration `json:"narration" nbt:"narration"`
}

// ChickenSoundVariant is Java ChickenSoundVariant (the registry minecraft:chicken_sound_variant).
type ChickenSoundVariant struct {
	AdultSounds ChickenSoundVariantChickenSoundSet `json:"adult_sounds" nbt:"adult_sounds"`
	BabySounds  ChickenSoundVariantChickenSoundSet `json:"baby_sounds" nbt:"baby_sounds"`
}

// ChickenSoundVariantChickenSoundSet is Java ChickenSoundVariant$ChickenSoundSet ().
type ChickenSoundVariantChickenSoundSet struct {
	AmbientSound Holder[SoundEvent] `json:"ambient_sound" nbt:"ambient_sound"` // an id in minecraft:sound_event or the inline element
	HurtSound    Holder[SoundEvent] `json:"hurt_sound" nbt:"hurt_sound"`       // an id in minecraft:sound_event or the inline element
	DeathSound   Holder[SoundEvent] `json:"death_sound" nbt:"death_sound"`     // an id in minecraft:sound_event or the inline element
	StepSound    Holder[SoundEvent] `json:"step_sound" nbt:"step_sound"`       // an id in minecraft:sound_event or the inline element
}

// ChickenVariant is Java ChickenVariant (the registry minecraft:chicken_variant).
type ChickenVariant struct {
	ModelAndTexture[ChickenVariantModelType]        // keys at this level
	BabyAssetID                              string `json:"baby_asset_id" nbt:"baby_asset_id"`
}

// CommonButtonData is Java CommonButtonData (inlined into ActionButton).
type CommonButtonData struct {
	Label   chat.Message  `json:"label" nbt:"label"`
	Tooltip *chat.Message `json:"tooltip,omitempty" nbt:"tooltip,omitempty"`
	Width   int32         `json:"width,omitempty" nbt:"width,omitempty"` // default 150
}

// CowSoundVariant is Java CowSoundVariant (the registry minecraft:cow_sound_variant).
type CowSoundVariant struct {
	AmbientSound Holder[SoundEvent] `json:"ambient_sound" nbt:"ambient_sound"` // an id in minecraft:sound_event or the inline element
	HurtSound    Holder[SoundEvent] `json:"hurt_sound" nbt:"hurt_sound"`       // an id in minecraft:sound_event or the inline element
	DeathSound   Holder[SoundEvent] `json:"death_sound" nbt:"death_sound"`     // an id in minecraft:sound_event or the inline element
	StepSound    Holder[SoundEvent] `json:"step_sound" nbt:"step_sound"`       // an id in minecraft:sound_event or the inline element
}

// CowVariant is Java CowVariant (the registry minecraft:cow_variant).
type CowVariant struct {
	Model       CowVariantModelType `json:"model,omitempty" nbt:"model,omitempty"` // default NORMAL
	AssetID     string              `json:"asset_id" nbt:"asset_id"`
	BabyAssetID string              `json:"baby_asset_id" nbt:"baby_asset_id"`
}

// DamageType is Java DamageType (the registry minecraft:damage_type).
type DamageType struct {
	MessageID        string           `json:"message_id" nbt:"message_id"`
	Scaling          DamageScaling    `json:"scaling" nbt:"scaling"`
	Exhaustion       float32          `json:"exhaustion" nbt:"exhaustion"`
	Effects          DamageEffects    `json:"effects,omitempty" nbt:"effects,omitempty"`                       // default HURT
	DeathMessageType DeathMessageType `json:"death_message_type,omitempty" nbt:"death_message_type,omitempty"` // default DEFAULT
}

// DimensionType is Java DimensionType (the registry minecraft:dimension_type).
type DimensionType struct {
	HasFixedTime                 bool                      `json:"has_fixed_time,omitempty" nbt:"has_fixed_time,omitempty"` // default false
	HasSkylight                  bool                      `json:"has_skylight" nbt:"has_skylight"`
	HasCeiling                   bool                      `json:"has_ceiling" nbt:"has_ceiling"`
	HasEnderDragonFight          bool                      `json:"has_ender_dragon_fight" nbt:"has_ender_dragon_fight"`
	CoordinateScale              float64                   `json:"coordinate_scale" nbt:"coordinate_scale"`
	MinY                         int32                     `json:"min_y" nbt:"min_y"`
	Height                       int32                     `json:"height" nbt:"height"`
	LogicalHeight                int32                     `json:"logical_height" nbt:"logical_height"`
	Infiniburn                   string                    `json:"infiniburn" nbt:"infiniburn"`
	AmbientLight                 float32                   `json:"ambient_light" nbt:"ambient_light"`
	DimensionTypeMonsterSettings                           // keys at this level
	Skybox                       DimensionTypeSkybox       `json:"skybox,omitempty" nbt:"skybox,omitempty"`                 // default OVERWORLD
	CardinalLight                CardinalLightingType      `json:"cardinal_light,omitempty" nbt:"cardinal_light,omitempty"` // default DEFAULT
	Attributes                   map[string]nbt.RawMessage `json:"attributes,omitempty" nbt:"attributes,omitempty"`         // keys: ids in minecraft:environment_attribute default EMPTY
	Timelines                    HolderSet                 `json:"timelines,omitempty" nbt:"timelines,omitempty"`           // elements of minecraft:timeline default []
	DefaultClock                 string                    `json:"default_clock,omitempty" nbt:"default_clock,omitempty"`   // id in minecraft:world_clock
}

// DimensionTypeMonsterSettings is Java DimensionType$MonsterSettings (inlined into DimensionType).
type DimensionTypeMonsterSettings struct {
	MonsterSpawnLightLevel      Either[int32, IntProviders] `json:"monster_spawn_light_level" nbt:"monster_spawn_light_level"` // either INT or dispatch IntProviders
	MonsterSpawnBlockLightLimit int32                       `json:"monster_spawn_block_light_limit" nbt:"monster_spawn_block_light_limit"`
}

// Enchantment is Java Enchantment (the registry minecraft:enchantment).
type Enchantment struct {
	Description           chat.Message              `json:"description" nbt:"description"`
	EnchantmentDefinition                           // keys at this level
	ExclusiveSet          HolderSet                 `json:"exclusive_set,omitempty" nbt:"exclusive_set,omitempty"` // elements of minecraft:enchantment default []
	Effects               map[string]nbt.RawMessage `json:"effects,omitempty" nbt:"effects,omitempty"`             // keys: ids in minecraft:enchantment_effect_component_type default EMPTY
}

// EnchantmentCost is Java Enchantment$Cost ().
type EnchantmentCost struct {
	Base               int32 `json:"base" nbt:"base"`
	PerLevelAboveFirst int32 `json:"per_level_above_first" nbt:"per_level_above_first"`
}

// EnchantmentDefinition is Java Enchantment$EnchantmentDefinition (inlined into Enchantment).
type EnchantmentDefinition struct {
	SupportedItems HolderSet            `json:"supported_items" nbt:"supported_items"`                 // elements of minecraft:item
	PrimaryItems   HolderSet            `json:"primary_items,omitempty" nbt:"primary_items,omitempty"` // elements of minecraft:item
	Weight         int32                `json:"weight" nbt:"weight"`
	MaxLevel       int32                `json:"max_level" nbt:"max_level"`
	MinCost        EnchantmentCost      `json:"min_cost" nbt:"min_cost"`
	MaxCost        EnchantmentCost      `json:"max_cost" nbt:"max_cost"`
	AnvilCost      int32                `json:"anvil_cost" nbt:"anvil_cost"`
	Slots          []EquipmentSlotGroup `json:"slots" nbt:"slots"`
}

// FrogVariant is Java FrogVariant (the registry minecraft:frog_variant).
type FrogVariant struct {
	AssetID string `json:"asset_id" nbt:"asset_id"`
}

// Input is Java Input ().
type Input struct {
	Key     string       `json:"key" nbt:"key"`
	Control InputControl `json:"-" nbt:"-"` // inline codec, not decoded:
}

// Instrument is Java Instrument (the registry minecraft:instrument).
type Instrument struct {
	SoundEvent  Holder[SoundEvent] `json:"sound_event" nbt:"sound_event"` // an id in minecraft:sound_event or the inline element
	UseDuration float32            `json:"use_duration" nbt:"use_duration"`
	Range       float32            `json:"range" nbt:"range"`
	Description chat.Message       `json:"description" nbt:"description"`
}

// ItemStackTemplate is Java ItemStackTemplate ().
type ItemStackTemplate struct {
	ID         string         `json:"id" nbt:"id"`                                     // id in minecraft:item
	Count      int32          `json:"count,omitempty" nbt:"count,omitempty"`           // default 1
	Components nbt.RawMessage `json:"components,omitempty" nbt:"components,omitempty"` // default EMPTY
}

// JukeboxSong is Java JukeboxSong (the registry minecraft:jukebox_song).
type JukeboxSong struct {
	SoundEvent       Holder[SoundEvent] `json:"sound_event" nbt:"sound_event"` // an id in minecraft:sound_event or the inline element
	Description      chat.Message       `json:"description" nbt:"description"`
	LengthInSeconds  float32            `json:"length_in_seconds" nbt:"length_in_seconds"`
	ComparatorOutput int32              `json:"comparator_output" nbt:"comparator_output"`
}

// MaterialAssetGroup is Java MaterialAssetGroup (inlined into TrimMaterial).
type MaterialAssetGroup struct {
	AssetName           string            `json:"asset_name" nbt:"asset_name"`
	OverrideArmorAssets map[string]string `json:"override_armor_assets,omitempty" nbt:"override_armor_assets,omitempty"` // keys: ids in minecraft:root_id default {}
}

// ModelAndTexture is Java ModelAndTexture (inlined into ChickenVariant). A generic record: T0 stand for the element types its uses give.
type ModelAndTexture[T0 any] struct {
	Model   T0     `json:"model,omitempty" nbt:"model,omitempty"` // the type parameter default NORMAL
	AssetID string `json:"asset_id" nbt:"asset_id"`
}

// PaintingVariant is Java PaintingVariant (the registry minecraft:painting_variant).
type PaintingVariant struct {
	Width   int32         `json:"width" nbt:"width"`
	Height  int32         `json:"height" nbt:"height"`
	AssetID string        `json:"asset_id" nbt:"asset_id"`
	Title   *chat.Message `json:"title,omitempty" nbt:"title,omitempty"`
	Author  *chat.Message `json:"author,omitempty" nbt:"author,omitempty"`
}

// PigSoundVariant is Java PigSoundVariant (the registry minecraft:pig_sound_variant).
type PigSoundVariant struct {
	AdultSounds PigSoundVariantPigSoundSet `json:"adult_sounds" nbt:"adult_sounds"`
	BabySounds  PigSoundVariantPigSoundSet `json:"baby_sounds" nbt:"baby_sounds"`
}

// PigSoundVariantPigSoundSet is Java PigSoundVariant$PigSoundSet ().
type PigSoundVariantPigSoundSet struct {
	AmbientSound Holder[SoundEvent] `json:"ambient_sound" nbt:"ambient_sound"` // an id in minecraft:sound_event or the inline element
	HurtSound    Holder[SoundEvent] `json:"hurt_sound" nbt:"hurt_sound"`       // an id in minecraft:sound_event or the inline element
	DeathSound   Holder[SoundEvent] `json:"death_sound" nbt:"death_sound"`     // an id in minecraft:sound_event or the inline element
	StepSound    Holder[SoundEvent] `json:"step_sound" nbt:"step_sound"`       // an id in minecraft:sound_event or the inline element
	EatSound     Holder[SoundEvent] `json:"eat_sound" nbt:"eat_sound"`         // an id in minecraft:sound_event or the inline element
}

// PigVariant is Java PigVariant (the registry minecraft:pig_variant).
type PigVariant struct {
	Model       PigVariantModelType `json:"model,omitempty" nbt:"model,omitempty"` // default NORMAL
	AssetID     string              `json:"asset_id" nbt:"asset_id"`
	BabyAssetID string              `json:"baby_asset_id" nbt:"baby_asset_id"`
}

// PlainMessage is Java PlainMessage ().
type PlainMessage struct {
	Contents chat.Message `json:"contents" nbt:"contents"`
	Width    int32        `json:"width,omitempty" nbt:"width,omitempty"` // default 200
}

// SingleOptionInputEntry is Java SingleOptionInput$Entry ().
type SingleOptionInputEntry struct {
	ID      string        `json:"id" nbt:"id"`
	Display *chat.Message `json:"display,omitempty" nbt:"display,omitempty"`
	Initial bool          `json:"initial,omitempty" nbt:"initial,omitempty"` // default false
}

// SoundEvent is Java SoundEvent ().
type SoundEvent struct {
	SoundID string  `json:"sound_id" nbt:"sound_id"`
	Range   float32 `json:"range,omitempty" nbt:"range,omitempty"`
}

// TextInputMultilineOptions is Java TextInput$MultilineOptions ().
type TextInputMultilineOptions struct {
	MaxLines int32 `json:"max_lines,omitempty" nbt:"max_lines,omitempty"`
	Height   int32 `json:"height,omitempty" nbt:"height,omitempty"`
}

// Timeline is Java Timeline (the registry minecraft:timeline).
type Timeline struct {
	Clock       string                                           `json:"clock" nbt:"clock"` // id in minecraft:world_clock
	PeriodTicks int32                                            `json:"period_ticks,omitempty" nbt:"period_ticks,omitempty"`
	Tracks      map[string]nbt.RawMessage                        `json:"tracks,omitempty" nbt:"tracks,omitempty"`             // keys: ids in minecraft:environment_attribute default {}
	TimeMarkers map[string]Either[int32, TimelineTimeMarkerInfo] `json:"time_markers,omitempty" nbt:"time_markers,omitempty"` // keys: ids in minecraft:root_id either INT or struct Timeline$TimeMarkerInfo default {}
}

// TimelineTimeMarkerInfo is Java Timeline$TimeMarkerInfo ().
type TimelineTimeMarkerInfo struct {
	Ticks          int32 `json:"ticks" nbt:"ticks"`
	ShowInCommands bool  `json:"show_in_commands,omitempty" nbt:"show_in_commands,omitempty"` // default false
}

// TrimMaterial is Java TrimMaterial (the registry minecraft:trim_material).
type TrimMaterial struct {
	MaterialAssetGroup              // keys at this level
	Description        chat.Message `json:"description" nbt:"description"`
}

// TrimPattern is Java TrimPattern (the registry minecraft:trim_pattern).
type TrimPattern struct {
	AssetID     string       `json:"asset_id" nbt:"asset_id"`
	Description chat.Message `json:"description" nbt:"description"`
	Decal       bool         `json:"decal" nbt:"decal"`
}

// Weighted is Java Weighted (). A generic record: T0 stand for the element types its uses give.
type Weighted[T0 any] struct {
	Data   *T0   `json:"data" nbt:"data"` // the type parameter either INT or a IntProviders again
	Weight int32 `json:"weight" nbt:"weight"`
}

// WolfSoundVariant is Java WolfSoundVariant (the registry minecraft:wolf_sound_variant).
type WolfSoundVariant struct {
	AdultSounds WolfSoundVariantWolfSoundSet `json:"adult_sounds" nbt:"adult_sounds"`
	BabySounds  WolfSoundVariantWolfSoundSet `json:"baby_sounds" nbt:"baby_sounds"`
}

// WolfSoundVariantWolfSoundSet is Java WolfSoundVariant$WolfSoundSet ().
type WolfSoundVariantWolfSoundSet struct {
	AmbientSound Holder[SoundEvent] `json:"ambient_sound" nbt:"ambient_sound"` // an id in minecraft:sound_event or the inline element
	DeathSound   Holder[SoundEvent] `json:"death_sound" nbt:"death_sound"`     // an id in minecraft:sound_event or the inline element
	GrowlSound   Holder[SoundEvent] `json:"growl_sound" nbt:"growl_sound"`     // an id in minecraft:sound_event or the inline element
	HurtSound    Holder[SoundEvent] `json:"hurt_sound" nbt:"hurt_sound"`       // an id in minecraft:sound_event or the inline element
	PantSound    Holder[SoundEvent] `json:"pant_sound" nbt:"pant_sound"`       // an id in minecraft:sound_event or the inline element
	WhineSound   Holder[SoundEvent] `json:"whine_sound" nbt:"whine_sound"`     // an id in minecraft:sound_event or the inline element
	StepSound    Holder[SoundEvent] `json:"step_sound" nbt:"step_sound"`       // an id in minecraft:sound_event or the inline element
}

// WolfVariant is Java WolfVariant (the registry minecraft:wolf_variant).
type WolfVariant struct {
	Assets     WolfVariantAssetInfo `json:"assets" nbt:"assets"`
	BabyAssets WolfVariantAssetInfo `json:"baby_assets" nbt:"baby_assets"`
}

// WolfVariantAssetInfo is Java WolfVariant$AssetInfo ().
type WolfVariantAssetInfo struct {
	Wild  string `json:"wild" nbt:"wild"`
	Tame  string `json:"tame" nbt:"tame"`
	Angry string `json:"angry" nbt:"angry"`
}

// WorldClock is an element of the registry minecraft:world_clock: Java WorldClock, a codec without fields.
type WorldClock struct {
}

// ZombieNautilusVariant is Java ZombieNautilusVariant (the registry minecraft:zombie_nautilus_variant).
type ZombieNautilusVariant struct {
	Model   ZombieNautilusVariantModelType `json:"model,omitempty" nbt:"model,omitempty"` // default NORMAL
	AssetID string                         `json:"asset_id" nbt:"asset_id"`
}

// Action is Java Action (): a union keyed by "type", rendered as the fields of every
// case; only those of the case in Type are set (minecraft:open_url: url; minecraft:run_command: command; minecraft:suggest_command: command; minecraft:show_dialog: dialog; minecraft:change_page: page; minecraft:copy_to_clipboard: value; minecraft:custom: id, payload; minecraft:dynamic/run_command: template; minecraft:dynamic/custom: id, additions).
type Action struct {
	Type      string           `json:"type" nbt:"type"`                               // selects the case
	URL       string           `json:"url,omitempty" nbt:"url,omitempty"`             // minecraft:open_url
	Command   string           `json:"command,omitempty" nbt:"command,omitempty"`     // minecraft:run_command, minecraft:suggest_command
	Dialog    *Holder[*Dialog] `json:"dialog,omitempty" nbt:"dialog,omitempty"`       // minecraft:show_dialog an id in minecraft:dialog or the inline element
	Page      int32            `json:"page,omitempty" nbt:"page,omitempty"`           // minecraft:change_page
	Value     string           `json:"value,omitempty" nbt:"value,omitempty"`         // minecraft:copy_to_clipboard
	ID        string           `json:"id,omitempty" nbt:"id,omitempty"`               // minecraft:custom, minecraft:dynamic/custom
	Payload   nbt.RawMessage   `json:"payload,omitempty" nbt:"payload,omitempty"`     // minecraft:custom
	Template  string           `json:"template,omitempty" nbt:"template,omitempty"`   // minecraft:dynamic/run_command
	Additions nbt.RawMessage   `json:"additions,omitempty" nbt:"additions,omitempty"` // minecraft:dynamic/custom
}

// Dialog is Java Dialog (the registry minecraft:dialog): a union keyed by "type", rendered as the fields of every
// case; only those of the case in Type are set (minecraft:notice: title, external_title, can_close_with_escape, pause, after_action, body, inputs, action; minecraft:server_links: title, external_title, can_close_with_escape, pause, after_action, body, inputs, exit_action, columns, button_width; minecraft:dialog_list: title, external_title, can_close_with_escape, pause, after_action, body, inputs, dialogs, exit_action, columns, button_width; minecraft:multi_action: title, external_title, can_close_with_escape, pause, after_action, body, inputs, actions, exit_action, columns; minecraft:confirmation: title, external_title, can_close_with_escape, pause, after_action, body, inputs, yes, no).
type Dialog struct {
	Type               string         `json:"type" nbt:"type"`                                                       // selects the case
	Title              *chat.Message  `json:"title,omitempty" nbt:"title,omitempty"`                                 // minecraft:notice, minecraft:server_links, minecraft:dialog_list, minecraft:multi_action, minecraft:confirmation
	ExternalTitle      *chat.Message  `json:"external_title,omitempty" nbt:"external_title,omitempty"`               // minecraft:notice, minecraft:server_links, minecraft:dialog_list, minecraft:multi_action, minecraft:confirmation
	CanCloseWithEscape bool           `json:"can_close_with_escape,omitempty" nbt:"can_close_with_escape,omitempty"` // minecraft:notice, minecraft:server_links, minecraft:dialog_list, minecraft:multi_action, minecraft:confirmation
	Pause              bool           `json:"pause,omitempty" nbt:"pause,omitempty"`                                 // minecraft:notice, minecraft:server_links, minecraft:dialog_list, minecraft:multi_action, minecraft:confirmation
	AfterAction        DialogAction   `json:"after_action,omitempty" nbt:"after_action,omitempty"`                   // minecraft:notice, minecraft:server_links, minecraft:dialog_list, minecraft:multi_action, minecraft:confirmation
	Body               []DialogBody   `json:"body,omitempty" nbt:"body,omitempty"`                                   // minecraft:notice, minecraft:server_links, minecraft:dialog_list, minecraft:multi_action, minecraft:confirmation
	Inputs             []Input        `json:"inputs,omitempty" nbt:"inputs,omitempty"`                               // minecraft:notice, minecraft:server_links, minecraft:dialog_list, minecraft:multi_action, minecraft:confirmation
	Action             *ActionButton  `json:"action,omitempty" nbt:"action,omitempty"`                               // minecraft:notice
	ExitAction         *ActionButton  `json:"exit_action,omitempty" nbt:"exit_action,omitempty"`                     // minecraft:server_links, minecraft:dialog_list, minecraft:multi_action
	Columns            int32          `json:"columns,omitempty" nbt:"columns,omitempty"`                             // minecraft:server_links, minecraft:dialog_list, minecraft:multi_action
	ButtonWidth        *int32         `json:"button_width,omitempty" nbt:"button_width,omitempty"`                   // minecraft:server_links, minecraft:dialog_list
	Dialogs            HolderSet      `json:"dialogs,omitempty" nbt:"dialogs,omitempty"`                             // minecraft:dialog_list elements of minecraft:dialog
	Actions            []ActionButton `json:"actions,omitempty" nbt:"actions,omitempty"`                             // minecraft:multi_action
	Yes                *ActionButton  `json:"yes,omitempty" nbt:"yes,omitempty"`                                     // minecraft:confirmation
	No                 *ActionButton  `json:"no,omitempty" nbt:"no,omitempty"`                                       // minecraft:confirmation
}

// DialogBody is Java DialogBody (): a union keyed by "type", rendered as the fields of every
// case; only those of the case in Type are set (minecraft:item: item, description, show_decorations, show_tooltip, width, height; minecraft:plain_message: contents, width).
type DialogBody struct {
	Type            string             `json:"type" nbt:"type"`                                             // selects the case
	Item            *ItemStackTemplate `json:"item,omitempty" nbt:"item,omitempty"`                         // minecraft:item
	Description     *PlainMessage      `json:"description,omitempty" nbt:"description,omitempty"`           // minecraft:item
	ShowDecorations bool               `json:"show_decorations,omitempty" nbt:"show_decorations,omitempty"` // minecraft:item
	ShowTooltip     bool               `json:"show_tooltip,omitempty" nbt:"show_tooltip,omitempty"`         // minecraft:item
	Width           int32              `json:"width,omitempty" nbt:"width,omitempty"`                       // minecraft:item, minecraft:plain_message
	Height          int32              `json:"height,omitempty" nbt:"height,omitempty"`                     // minecraft:item
	Contents        *chat.Message      `json:"contents,omitempty" nbt:"contents,omitempty"`                 // minecraft:plain_message
}

// GameTestInstance is Java GameTestInstance (the registry minecraft:test_instance): a union keyed by "type", rendered as the fields of every
// case; only those of the case in Type are set (minecraft:block_based: environment, structure, max_ticks, setup_ticks, required, rotation, manual_only, max_attempts, required_successes, sky_access, padding; minecraft:function: function, environment, structure, max_ticks, setup_ticks, required, rotation, manual_only, max_attempts, required_successes, sky_access, padding).
type GameTestInstance struct {
	Type              string                           `json:"type" nbt:"type"`                                                 // selects the case
	Environment       *TestEnvironmentDefinitionHolder `json:"environment,omitempty" nbt:"environment,omitempty"`               // minecraft:block_based, minecraft:function
	Structure         string                           `json:"structure,omitempty" nbt:"structure,omitempty"`                   // minecraft:block_based, minecraft:function
	MaxTicks          int32                            `json:"max_ticks,omitempty" nbt:"max_ticks,omitempty"`                   // minecraft:block_based, minecraft:function
	SetupTicks        int32                            `json:"setup_ticks,omitempty" nbt:"setup_ticks,omitempty"`               // minecraft:block_based, minecraft:function
	Required          bool                             `json:"required,omitempty" nbt:"required,omitempty"`                     // minecraft:block_based, minecraft:function
	Rotation          Rotation                         `json:"rotation,omitempty" nbt:"rotation,omitempty"`                     // minecraft:block_based, minecraft:function
	ManualOnly        bool                             `json:"manual_only,omitempty" nbt:"manual_only,omitempty"`               // minecraft:block_based, minecraft:function
	MaxAttempts       int32                            `json:"max_attempts,omitempty" nbt:"max_attempts,omitempty"`             // minecraft:block_based, minecraft:function
	RequiredSuccesses int32                            `json:"required_successes,omitempty" nbt:"required_successes,omitempty"` // minecraft:block_based, minecraft:function
	SkyAccess         bool                             `json:"sky_access,omitempty" nbt:"sky_access,omitempty"`                 // minecraft:block_based, minecraft:function
	Padding           int32                            `json:"padding,omitempty" nbt:"padding,omitempty"`                       // minecraft:block_based, minecraft:function
	Function          string                           `json:"function,omitempty" nbt:"function,omitempty"`                     // minecraft:function id in minecraft:test_function
}

// InputControl is Java InputControl (): a union keyed by "type", rendered as the fields of every
// case; only those of the case in Type are set (minecraft:boolean: label, initial, on_true, on_false; minecraft:number_range: width, label, label_format, start, end, initial, step; minecraft:single_option: width, options, label, label_visible; minecraft:text: width, label, label_visible, initial, max_length, multiline).
type InputControl struct {
	Type         string                     `json:"type" nbt:"type"`                                       // selects the case
	Label        *chat.Message              `json:"label,omitempty" nbt:"label,omitempty"`                 // minecraft:boolean, minecraft:number_range, minecraft:single_option, minecraft:text
	Initial      nbt.RawMessage             `json:"initial,omitempty" nbt:"initial,omitempty"`             // minecraft:boolean; minecraft:number_range: float32 (differs per case); minecraft:text: string (differs per case)
	OnTrue       string                     `json:"on_true,omitempty" nbt:"on_true,omitempty"`             // minecraft:boolean
	OnFalse      string                     `json:"on_false,omitempty" nbt:"on_false,omitempty"`           // minecraft:boolean
	Width        int32                      `json:"width,omitempty" nbt:"width,omitempty"`                 // minecraft:number_range, minecraft:single_option, minecraft:text
	LabelFormat  string                     `json:"label_format,omitempty" nbt:"label_format,omitempty"`   // minecraft:number_range
	Start        float32                    `json:"start,omitempty" nbt:"start,omitempty"`                 // minecraft:number_range
	End          float32                    `json:"end,omitempty" nbt:"end,omitempty"`                     // minecraft:number_range
	Step         float32                    `json:"step,omitempty" nbt:"step,omitempty"`                   // minecraft:number_range
	Options      []SingleOptionInputEntry   `json:"options,omitempty" nbt:"options,omitempty"`             // minecraft:single_option
	LabelVisible bool                       `json:"label_visible,omitempty" nbt:"label_visible,omitempty"` // minecraft:single_option, minecraft:text
	MaxLength    int32                      `json:"max_length,omitempty" nbt:"max_length,omitempty"`       // minecraft:text
	Multiline    *TextInputMultilineOptions `json:"multiline,omitempty" nbt:"multiline,omitempty"`         // minecraft:text
}

// IntProviders is Java IntProviders (): a union keyed by "type", rendered as the fields of every
// case; only those of the case in Type are set (minecraft:constant: value; minecraft:uniform: min_inclusive, max_inclusive; minecraft:biased_to_bottom: min_inclusive, max_inclusive; minecraft:clamped: source, min_inclusive, max_inclusive; minecraft:weighted_list: distribution; minecraft:clamped_normal: mean, deviation, min_inclusive, max_inclusive; minecraft:trapezoid: min, max, plateau).
type IntProviders struct {
	Type         string                                   `json:"type" nbt:"type"`                                       // selects the case
	Value        int32                                    `json:"value,omitempty" nbt:"value,omitempty"`                 // minecraft:constant
	MinInclusive int32                                    `json:"min_inclusive,omitempty" nbt:"min_inclusive,omitempty"` // minecraft:uniform, minecraft:biased_to_bottom, minecraft:clamped, minecraft:clamped_normal
	MaxInclusive int32                                    `json:"max_inclusive,omitempty" nbt:"max_inclusive,omitempty"` // minecraft:uniform, minecraft:biased_to_bottom, minecraft:clamped, minecraft:clamped_normal
	Source       *Either[int32, *IntProviders]            `json:"source,omitempty" nbt:"source,omitempty"`               // minecraft:clamped either INT or a IntProviders again
	Distribution []Weighted[Either[int32, *IntProviders]] `json:"distribution,omitempty" nbt:"distribution,omitempty"`   // minecraft:weighted_list
	Mean         float32                                  `json:"mean,omitempty" nbt:"mean,omitempty"`                   // minecraft:clamped_normal
	Deviation    float32                                  `json:"deviation,omitempty" nbt:"deviation,omitempty"`         // minecraft:clamped_normal
	Min          int32                                    `json:"min,omitempty" nbt:"min,omitempty"`                     // minecraft:trapezoid
	Max          int32                                    `json:"max,omitempty" nbt:"max,omitempty"`                     // minecraft:trapezoid
	Plateau      int32                                    `json:"plateau,omitempty" nbt:"plateau,omitempty"`             // minecraft:trapezoid
}

// TestEnvironmentDefinition is Java TestEnvironmentDefinition (the registry minecraft:test_environment): a union keyed by "type", rendered as the fields of every
// case; only those of the case in Type are set (minecraft:all_of: definitions; minecraft:game_rules: rules; minecraft:clock_time: clock, time; minecraft:timeline_attributes: timelines; minecraft:weather: weather; minecraft:function: setup, teardown).
type TestEnvironmentDefinition struct {
	Type        string                               `json:"type" nbt:"type"`                                   // selects the case
	Definitions []Holder[*TestEnvironmentDefinition] `json:"definitions,omitempty" nbt:"definitions,omitempty"` // minecraft:all_of an id in minecraft:test_environment or the inline element
	Rules       map[string]nbt.RawMessage            `json:"rules,omitempty" nbt:"rules,omitempty"`             // minecraft:game_rules keys: ids in minecraft:game_rule
	Clock       string                               `json:"clock,omitempty" nbt:"clock,omitempty"`             // minecraft:clock_time id in minecraft:world_clock
	Time        int32                                `json:"time,omitempty" nbt:"time,omitempty"`               // minecraft:clock_time
	Timelines   []string                             `json:"timelines,omitempty" nbt:"timelines,omitempty"`     // minecraft:timeline_attributes id in minecraft:timeline
	Weather     TestEnvironmentDefinitionWeatherType `json:"weather,omitempty" nbt:"weather,omitempty"`         // minecraft:weather
	Setup       string                               `json:"setup,omitempty" nbt:"setup,omitempty"`             // minecraft:function
	Teardown    string                               `json:"teardown,omitempty" nbt:"teardown,omitempty"`       // minecraft:function
}

// TestEnvironmentDefinitionHolder is the recursive codec TestEnvironmentDefinition: holder; a reference to it from inside is a *TestEnvironmentDefinitionHolder.
type TestEnvironmentDefinitionHolder struct {
	Holder[TestEnvironmentDefinition] // the codec itself an id in minecraft:test_environment or the inline element
}
