// Code generated by gen/gen_nbt.go from 26.2/nbt_schema.json; DO NOT EDIT.
package registry

import "github.com/mj41/go-mc26/nbt"

// Registries holds the registries a server sends in the configuration phase
// (registry_data packets; RegistryDataLoader.SYNCHRONIZED_REGISTRIES of Minecraft 26.2),
// decoded into the element types of elements_gen.go. A registry whose element the
// schema cannot type is kept as raw NBT; a registry this build does not know goes
// to ExtraRegistries.
type Registries struct {
	BannerPattern         Registry[BannerPattern]             `registry:"minecraft:banner_pattern"`
	CatSoundVariant       Registry[CatSoundVariant]           `registry:"minecraft:cat_sound_variant"`
	CatVariant            Registry[CatVariant]                `registry:"minecraft:cat_variant"`
	ChatType              Registry[ChatType]                  `registry:"minecraft:chat_type"`
	ChickenSoundVariant   Registry[ChickenSoundVariant]       `registry:"minecraft:chicken_sound_variant"`
	ChickenVariant        Registry[ChickenVariant]            `registry:"minecraft:chicken_variant"`
	CowSoundVariant       Registry[CowSoundVariant]           `registry:"minecraft:cow_sound_variant"`
	CowVariant            Registry[CowVariant]                `registry:"minecraft:cow_variant"`
	DamageType            Registry[DamageType]                `registry:"minecraft:damage_type"`
	Dialog                Registry[Dialog]                    `registry:"minecraft:dialog"`
	DimensionType         Registry[DimensionType]             `registry:"minecraft:dimension_type"`
	Enchantment           Registry[Enchantment]               `registry:"minecraft:enchantment"`
	FrogVariant           Registry[FrogVariant]               `registry:"minecraft:frog_variant"`
	Instrument            Registry[Instrument]                `registry:"minecraft:instrument"`
	JukeboxSong           Registry[JukeboxSong]               `registry:"minecraft:jukebox_song"`
	PaintingVariant       Registry[PaintingVariant]           `registry:"minecraft:painting_variant"`
	PigSoundVariant       Registry[PigSoundVariant]           `registry:"minecraft:pig_sound_variant"`
	PigVariant            Registry[PigVariant]                `registry:"minecraft:pig_variant"`
	SulfurCubeArchetype   Registry[SulfurCubeArchetype]       `registry:"minecraft:sulfur_cube_archetype"`
	TestEnvironment       Registry[TestEnvironmentDefinition] `registry:"minecraft:test_environment"`
	TestInstance          Registry[GameTestInstance]          `registry:"minecraft:test_instance"`
	Timeline              Registry[Timeline]                  `registry:"minecraft:timeline"`
	TrimMaterial          Registry[TrimMaterial]              `registry:"minecraft:trim_material"`
	TrimPattern           Registry[TrimPattern]               `registry:"minecraft:trim_pattern"`
	WolfSoundVariant      Registry[WolfSoundVariant]          `registry:"minecraft:wolf_sound_variant"`
	WolfVariant           Registry[WolfVariant]               `registry:"minecraft:wolf_variant"`
	WorldClock            Registry[WorldClock]                `registry:"minecraft:world_clock"`
	Biome                 Registry[Biome]                     `registry:"minecraft:worldgen/biome"`
	ZombieNautilusVariant Registry[ZombieNautilusVariant]     `registry:"minecraft:zombie_nautilus_variant"`

	ExtraRegistries map[string]*Registry[nbt.RawMessage]
}

// NewNetworkCodec returns empty registries ready to receive registry_data.
func NewNetworkCodec() Registries {
	return Registries{
		BannerPattern:         NewRegistry[BannerPattern](),
		CatSoundVariant:       NewRegistry[CatSoundVariant](),
		CatVariant:            NewRegistry[CatVariant](),
		ChatType:              NewRegistry[ChatType](),
		ChickenSoundVariant:   NewRegistry[ChickenSoundVariant](),
		ChickenVariant:        NewRegistry[ChickenVariant](),
		CowSoundVariant:       NewRegistry[CowSoundVariant](),
		CowVariant:            NewRegistry[CowVariant](),
		DamageType:            NewRegistry[DamageType](),
		Dialog:                NewRegistry[Dialog](),
		DimensionType:         NewRegistry[DimensionType](),
		Enchantment:           NewRegistry[Enchantment](),
		FrogVariant:           NewRegistry[FrogVariant](),
		Instrument:            NewRegistry[Instrument](),
		JukeboxSong:           NewRegistry[JukeboxSong](),
		PaintingVariant:       NewRegistry[PaintingVariant](),
		PigSoundVariant:       NewRegistry[PigSoundVariant](),
		PigVariant:            NewRegistry[PigVariant](),
		SulfurCubeArchetype:   NewRegistry[SulfurCubeArchetype](),
		TestEnvironment:       NewRegistry[TestEnvironmentDefinition](),
		TestInstance:          NewRegistry[GameTestInstance](),
		Timeline:              NewRegistry[Timeline](),
		TrimMaterial:          NewRegistry[TrimMaterial](),
		TrimPattern:           NewRegistry[TrimPattern](),
		WolfSoundVariant:      NewRegistry[WolfSoundVariant](),
		WolfVariant:           NewRegistry[WolfVariant](),
		WorldClock:            NewRegistry[WorldClock](),
		Biome:                 NewRegistry[Biome](),
		ZombieNautilusVariant: NewRegistry[ZombieNautilusVariant](),
		ExtraRegistries:       make(map[string]*Registry[nbt.RawMessage]),
	}
}
