// Code generated by gen/gen_packets.go from 26.2/packet_schema.json + packets.json; DO NOT EDIT.
// Package configuration holds the generated 26.2 packets of the configuration state.
package configuration

import (
	"io"

	"github.com/mj41/go-mc26/data/packetid"
	pk "github.com/mj41/go-mc26/net/packet"
	"github.com/mj41/go-mc26/protocol/types"
)

var (
	_ = io.EOF
	_ pk.Field
	_ types.Empty
)

// NewClientbound returns an empty configuration clientbound packet of the given id, or nil when this
// version has no such packet or it is not generated.
func NewClientbound(id packetid.ClientboundPacketID) pk.Field {
	switch id {
	case packetid.ClientboundConfigurationCookieRequest:
		return new(CookieRequest)
	case packetid.ClientboundConfigurationCustomPayload:
		return new(ClientboundCustomPayload)
	case packetid.ClientboundConfigurationDisconnect:
		return new(Disconnect)
	case packetid.ClientboundConfigurationFinishConfiguration:
		return new(ClientboundFinishConfiguration)
	case packetid.ClientboundConfigurationKeepAlive:
		return new(ClientboundKeepAlive)
	case packetid.ClientboundConfigurationPing:
		return new(Ping)
	case packetid.ClientboundConfigurationResetChat:
		return new(ResetChat)
	case packetid.ClientboundConfigurationRegistryData:
		return new(RegistryData)
	case packetid.ClientboundConfigurationResourcePackPop:
		return new(ResourcePackPop)
	case packetid.ClientboundConfigurationResourcePackPush:
		return new(ResourcePackPush)
	case packetid.ClientboundConfigurationStoreCookie:
		return new(StoreCookie)
	case packetid.ClientboundConfigurationTransfer:
		return new(Transfer)
	case packetid.ClientboundConfigurationUpdateEnabledFeatures:
		return new(UpdateEnabledFeatures)
	case packetid.ClientboundConfigurationUpdateTags:
		return new(UpdateTags)
	case packetid.ClientboundConfigurationSelectKnownPacks:
		return new(ClientboundSelectKnownPacks)
	case packetid.ClientboundConfigurationCustomReportDetails:
		return new(CustomReportDetails)
	case packetid.ClientboundConfigurationServerLinks:
		return new(ServerLinks)
	case packetid.ClientboundConfigurationClearDialog:
		return new(ClearDialog)
	case packetid.ClientboundConfigurationShowDialog:
		return new(ShowDialog)
	case packetid.ClientboundConfigurationCodeOfConduct:
		return new(CodeOfConduct)
	}
	return nil
}

// CookieRequest is clientbound/minecraft:cookie_request (0x00), Java ClientboundCookieRequestPacket.
type CookieRequest struct {
	Key pk.Identifier
}

// PacketID returns the clientbound id of CookieRequest.
func (CookieRequest) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundConfigurationCookieRequest
}

func (p *CookieRequest) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&p.Key}.ReadFrom(r)
}

func (p CookieRequest) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{p.Key}.WriteTo(w)
}

// ClientboundCustomPayload is clientbound/minecraft:custom_payload (0x01), Java ClientboundCustomPayloadPacket.
type ClientboundCustomPayload struct {
	Channel pk.Identifier
	Data    types.RestBytes
}

// PacketID returns the clientbound id of ClientboundCustomPayload.
func (ClientboundCustomPayload) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundConfigurationCustomPayload
}

func (p *ClientboundCustomPayload) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&p.Channel, &p.Data}.ReadFrom(r)
}

func (p ClientboundCustomPayload) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{p.Channel, p.Data}.WriteTo(w)
}

// Disconnect is clientbound/minecraft:disconnect (0x02), Java ClientboundDisconnectPacket.
type Disconnect struct {
	Value types.Text
}

// PacketID returns the clientbound id of Disconnect.
func (Disconnect) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundConfigurationDisconnect
}

func (p *Disconnect) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&p.Value}.ReadFrom(r)
}

func (p Disconnect) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{p.Value}.WriteTo(w)
}

// ClientboundFinishConfiguration is clientbound/minecraft:finish_configuration (0x03), Java ClientboundFinishConfigurationPacket.
type ClientboundFinishConfiguration struct{ types.Empty }

// PacketID returns the clientbound id of ClientboundFinishConfiguration.
func (ClientboundFinishConfiguration) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundConfigurationFinishConfiguration
}

// ClientboundKeepAlive is clientbound/minecraft:keep_alive (0x04), Java ClientboundKeepAlivePacket.
type ClientboundKeepAlive struct {
	ID pk.Long
}

// PacketID returns the clientbound id of ClientboundKeepAlive.
func (ClientboundKeepAlive) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundConfigurationKeepAlive
}

func (p *ClientboundKeepAlive) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&p.ID}.ReadFrom(r)
}

func (p ClientboundKeepAlive) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{p.ID}.WriteTo(w)
}

// Ping is clientbound/minecraft:ping (0x05), Java ClientboundPingPacket.
type Ping struct {
	ID pk.Int
}

// PacketID returns the clientbound id of Ping.
func (Ping) PacketID() packetid.ClientboundPacketID { return packetid.ClientboundConfigurationPing }

func (p *Ping) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&p.ID}.ReadFrom(r)
}

func (p Ping) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{p.ID}.WriteTo(w)
}

// ResetChat is clientbound/minecraft:reset_chat (0x06), Java ClientboundResetChatPacket.
type ResetChat struct{ types.Empty }

// PacketID returns the clientbound id of ResetChat.
func (ResetChat) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundConfigurationResetChat
}

// RegistryData is clientbound/minecraft:registry_data (0x07), Java ClientboundRegistryDataPacket.
type RegistryData struct {
	Registry pk.Identifier
	Entries  types.List[types.RegistrySynchronizationPackedRegistryEntry, *types.RegistrySynchronizationPackedRegistryEntry]
}

// PacketID returns the clientbound id of RegistryData.
func (RegistryData) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundConfigurationRegistryData
}

func (p *RegistryData) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&p.Registry, &p.Entries}.ReadFrom(r)
}

func (p RegistryData) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{p.Registry, p.Entries}.WriteTo(w)
}

// ResourcePackPop is clientbound/minecraft:resource_pack_pop (0x08), Java ClientboundResourcePackPopPacket.
type ResourcePackPop struct {
	ID pk.Option[pk.UUID, *pk.UUID]
}

// PacketID returns the clientbound id of ResourcePackPop.
func (ResourcePackPop) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundConfigurationResourcePackPop
}

func (p *ResourcePackPop) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&p.ID}.ReadFrom(r)
}

func (p ResourcePackPop) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{p.ID}.WriteTo(w)
}

// ResourcePackPush is clientbound/minecraft:resource_pack_push (0x09), Java ClientboundResourcePackPushPacket.
type ResourcePackPush struct {
	ID       pk.UUID
	URL      pk.String
	Hash     pk.String
	Required pk.Boolean
	Prompt   pk.Option[types.Text, *types.Text]
}

// PacketID returns the clientbound id of ResourcePackPush.
func (ResourcePackPush) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundConfigurationResourcePackPush
}

func (p *ResourcePackPush) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&p.ID, &p.URL, &p.Hash, &p.Required, &p.Prompt}.ReadFrom(r)
}

func (p ResourcePackPush) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{p.ID, p.URL, p.Hash, p.Required, p.Prompt}.WriteTo(w)
}

// StoreCookie is clientbound/minecraft:store_cookie (0x0A), Java ClientboundStoreCookiePacket.
type StoreCookie struct {
	Key     pk.Identifier
	Payload pk.ByteArray
}

// PacketID returns the clientbound id of StoreCookie.
func (StoreCookie) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundConfigurationStoreCookie
}

func (p *StoreCookie) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&p.Key, &p.Payload}.ReadFrom(r)
}

func (p StoreCookie) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{p.Key, p.Payload}.WriteTo(w)
}

// Transfer is clientbound/minecraft:transfer (0x0B), Java ClientboundTransferPacket.
type Transfer struct {
	Host pk.String
	Port pk.VarInt
}

// PacketID returns the clientbound id of Transfer.
func (Transfer) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundConfigurationTransfer
}

func (p *Transfer) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&p.Host, &p.Port}.ReadFrom(r)
}

func (p Transfer) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{p.Host, p.Port}.WriteTo(w)
}

// UpdateEnabledFeatures is clientbound/minecraft:update_enabled_features (0x0C), Java ClientboundUpdateEnabledFeaturesPacket.
type UpdateEnabledFeatures struct {
	Features types.List[pk.Identifier, *pk.Identifier]
}

// PacketID returns the clientbound id of UpdateEnabledFeatures.
func (UpdateEnabledFeatures) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundConfigurationUpdateEnabledFeatures
}

func (p *UpdateEnabledFeatures) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&p.Features}.ReadFrom(r)
}

func (p UpdateEnabledFeatures) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{p.Features}.WriteTo(w)
}

// UpdateTags is clientbound/minecraft:update_tags (0x0D), Java ClientboundUpdateTagsPacket.
type UpdateTags struct {
	Tags types.Map[pk.Identifier, *pk.Identifier, types.Map[pk.Identifier, *pk.Identifier, types.List[pk.VarInt, *pk.VarInt], *types.List[pk.VarInt, *pk.VarInt]], *types.Map[pk.Identifier, *pk.Identifier, types.List[pk.VarInt, *pk.VarInt], *types.List[pk.VarInt, *pk.VarInt]]]
}

// PacketID returns the clientbound id of UpdateTags.
func (UpdateTags) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundConfigurationUpdateTags
}

func (p *UpdateTags) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&p.Tags}.ReadFrom(r)
}

func (p UpdateTags) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{p.Tags}.WriteTo(w)
}

// ClientboundSelectKnownPacks is clientbound/minecraft:select_known_packs (0x0E), Java ClientboundSelectKnownPacks.
type ClientboundSelectKnownPacks struct {
	KnownPacks types.List[types.KnownPack, *types.KnownPack]
}

// PacketID returns the clientbound id of ClientboundSelectKnownPacks.
func (ClientboundSelectKnownPacks) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundConfigurationSelectKnownPacks
}

func (p *ClientboundSelectKnownPacks) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&p.KnownPacks}.ReadFrom(r)
}

func (p ClientboundSelectKnownPacks) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{p.KnownPacks}.WriteTo(w)
}

// CustomReportDetails is clientbound/minecraft:custom_report_details (0x0F), Java ClientboundCustomReportDetailsPacket.
type CustomReportDetails struct {
	Details types.Map[pk.String, *pk.String, pk.String, *pk.String]
}

// PacketID returns the clientbound id of CustomReportDetails.
func (CustomReportDetails) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundConfigurationCustomReportDetails
}

func (p *CustomReportDetails) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&p.Details}.ReadFrom(r)
}

func (p CustomReportDetails) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{p.Details}.WriteTo(w)
}

// ServerLinks is clientbound/minecraft:server_links (0x10), Java ClientboundServerLinksPacket.
type ServerLinks struct {
	Links types.List[types.ServerLinksUntrustedEntry, *types.ServerLinksUntrustedEntry]
}

// PacketID returns the clientbound id of ServerLinks.
func (ServerLinks) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundConfigurationServerLinks
}

func (p *ServerLinks) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&p.Links}.ReadFrom(r)
}

func (p ServerLinks) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{p.Links}.WriteTo(w)
}

// ClearDialog is clientbound/minecraft:clear_dialog (0x11), Java ClientboundClearDialogPacket.
type ClearDialog struct{ types.Empty }

// PacketID returns the clientbound id of ClearDialog.
func (ClearDialog) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundConfigurationClearDialog
}

// ShowDialog is clientbound/minecraft:show_dialog (0x12), Java ClientboundShowDialogPacket.
type ShowDialog struct {
	Dialog types.Holder[types.NBT, *types.NBT] // registry dialog
}

// PacketID returns the clientbound id of ShowDialog.
func (ShowDialog) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundConfigurationShowDialog
}

func (p *ShowDialog) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&p.Dialog}.ReadFrom(r)
}

func (p ShowDialog) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{p.Dialog}.WriteTo(w)
}

// CodeOfConduct is clientbound/minecraft:code_of_conduct (0x13), Java ClientboundCodeOfConductPacket.
type CodeOfConduct struct {
	CodeOfConduct pk.String
}

// PacketID returns the clientbound id of CodeOfConduct.
func (CodeOfConduct) PacketID() packetid.ClientboundPacketID {
	return packetid.ClientboundConfigurationCodeOfConduct
}

func (p *CodeOfConduct) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&p.CodeOfConduct}.ReadFrom(r)
}

func (p CodeOfConduct) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{p.CodeOfConduct}.WriteTo(w)
}
