// Code generated by gen/gen_nbt.go from 26.3/nbt_schema.json; DO NOT EDIT.

// The style of text components, click and hover events and the chat type
// decoration, typed from their codecs; json tags for text components, nbt tags
// for the registry data and the wire.
package chat

// ChatTypeDecorationParameter is Java ChatTypeDecoration$Parameter, stored as its serialized name.
type ChatTypeDecorationParameter string

const (
	ChatTypeDecorationParameterSender  ChatTypeDecorationParameter = "sender"
	ChatTypeDecorationParameterTarget  ChatTypeDecorationParameter = "target"
	ChatTypeDecorationParameterContent ChatTypeDecorationParameter = "content"
)

// ChatTypeDecorationParameterValues lists the constants in declaration order (the ordinals).
var ChatTypeDecorationParameterValues = []ChatTypeDecorationParameter{ChatTypeDecorationParameterSender, ChatTypeDecorationParameterTarget, ChatTypeDecorationParameterContent}

// ClickEventAction is Java ClickEvent$Action, stored as its serialized name.
type ClickEventAction string

const (
	ClickEventActionOpenURL         ClickEventAction = "open_url"
	ClickEventActionOpenFile        ClickEventAction = "open_file"
	ClickEventActionRunCommand      ClickEventAction = "run_command"
	ClickEventActionSuggestCommand  ClickEventAction = "suggest_command"
	ClickEventActionShowDialog      ClickEventAction = "show_dialog"
	ClickEventActionChangePage      ClickEventAction = "change_page"
	ClickEventActionCopyToClipboard ClickEventAction = "copy_to_clipboard"
	ClickEventActionCustom          ClickEventAction = "custom"
)

// ClickEventActionValues lists the constants in declaration order (the ordinals).
var ClickEventActionValues = []ClickEventAction{ClickEventActionOpenURL, ClickEventActionOpenFile, ClickEventActionRunCommand, ClickEventActionSuggestCommand, ClickEventActionShowDialog, ClickEventActionChangePage, ClickEventActionCopyToClipboard, ClickEventActionCustom}

// HoverEventAction is Java HoverEvent$Action, stored as its serialized name.
type HoverEventAction string

const (
	HoverEventActionShowText   HoverEventAction = "show_text"
	HoverEventActionShowItem   HoverEventAction = "show_item"
	HoverEventActionShowEntity HoverEventAction = "show_entity"
)

// HoverEventActionValues lists the constants in declaration order (the ordinals).
var HoverEventActionValues = []HoverEventAction{HoverEventActionShowText, HoverEventActionShowItem, HoverEventActionShowEntity}

// ChatTypeDecoration is Java ChatTypeDecoration (chat structure net.minecraft.network.chat.ChatTypeDecoration).
type ChatTypeDecoration struct {
	TranslationKey string                        `json:"translation_key" nbt:"translation_key"`
	Parameters     []ChatTypeDecorationParameter `json:"parameters" nbt:"parameters"`
	Style          *Style                        `json:"style,omitempty" nbt:"style,omitempty"` // default EMPTY
}

// Style is Java Style ().
type Style struct {
	Color         string      `json:"color,omitempty" nbt:"color,omitempty"`
	ShadowColor   int32       `json:"shadow_color,omitempty" nbt:"shadow_color,omitempty"`
	Bold          bool        `json:"bold,omitempty" nbt:"bold,omitempty"`
	Italic        bool        `json:"italic,omitempty" nbt:"italic,omitempty"`
	Underlined    bool        `json:"underlined,omitempty" nbt:"underlined,omitempty"`
	Strikethrough bool        `json:"strikethrough,omitempty" nbt:"strikethrough,omitempty"`
	Obfuscated    bool        `json:"obfuscated,omitempty" nbt:"obfuscated,omitempty"`
	ClickEvent    *ClickEvent `json:"click_event,omitempty" nbt:"click_event,omitempty"`
	HoverEvent    *HoverEvent `json:"hover_event,omitempty" nbt:"hover_event,omitempty"`
	Insertion     string      `json:"insertion,omitempty" nbt:"insertion,omitempty"`
	Font          string      `json:"font,omitempty" nbt:"font,omitempty"`
}

// ClickEvent is Java ClickEvent (): a union keyed by "action", rendered as the fields of every
// case; only those of the case in Action are set (open_url: url; open_file: path; run_command: command; suggest_command: command; show_dialog: dialog; change_page: page; copy_to_clipboard: value; custom: id, payload).
type ClickEvent struct {
	Action  ClickEventAction `json:"action" nbt:"action"`                       // selects the case
	URL     string           `json:"url,omitempty" nbt:"url,omitempty"`         // open_url
	Path    string           `json:"path,omitempty" nbt:"path,omitempty"`       // open_file
	Command string           `json:"command,omitempty" nbt:"command,omitempty"` // run_command, suggest_command
	Dialog  any              `json:"dialog,omitempty" nbt:"dialog,omitempty"`   // show_dialog an id in minecraft:dialog or the inline element
	Page    int32            `json:"page,omitempty" nbt:"page,omitempty"`       // change_page
	Value   string           `json:"value,omitempty" nbt:"value,omitempty"`     // copy_to_clipboard
	ID      string           `json:"id,omitempty" nbt:"id,omitempty"`           // custom
	Payload any              `json:"payload,omitempty" nbt:"payload,omitempty"` // custom
}

// HoverEvent is Java HoverEvent (): a union keyed by "action", rendered as the fields of every
// case; only those of the case in Action are set (show_text: value; show_item: id, count, components; show_entity: id, uuid, name).
type HoverEvent struct {
	Action     HoverEventAction `json:"action" nbt:"action"`                             // selects the case
	Value      *Message         `json:"value,omitempty" nbt:"value,omitempty"`           // show_text
	ID         string           `json:"id,omitempty" nbt:"id,omitempty"`                 // show_item id in minecraft:item, show_entity
	Count      int32            `json:"count,omitempty" nbt:"count,omitempty"`           // show_item
	Components any              `json:"components,omitempty" nbt:"components,omitempty"` // show_item
	UUID       any              `json:"uuid,omitempty" nbt:"uuid,omitempty"`             // show_entity a uuid as an int array or a string
	Name       *Message         `json:"name,omitempty" nbt:"name,omitempty"`             // show_entity
}
