// Code generated by gen/gen_packets.go from 26.1/packet_schema.json + packets.json; DO NOT EDIT.
// Package login holds the generated 26.1 packets of the login state.
package login

import (
	"io"

	"github.com/mj41/go-mc26/data/packetid"
	pk "github.com/mj41/go-mc26/net/packet"
	"github.com/mj41/go-mc26/protocol/types"
)

var (
	_ = io.EOF
	_ pk.Field
	_ types.Empty
)

// NewServerbound returns an empty login serverbound packet of the given id, or nil when this
// version has no such packet or it is not generated.
func NewServerbound(id packetid.ServerboundPacketID) pk.Field {
	switch id {
	case packetid.ServerboundLoginHello:
		return new(ServerboundHello)
	case packetid.ServerboundLoginKey:
		return new(Key)
	case packetid.ServerboundLoginCustomQueryAnswer:
		return new(CustomQueryAnswer)
	case packetid.ServerboundLoginLoginAcknowledged:
		return new(LoginAcknowledged)
	case packetid.ServerboundLoginCookieResponse:
		return new(CookieResponse)
	}
	return nil
}

// ServerboundHello is serverbound/minecraft:hello (0x00), Java ServerboundHelloPacket.
type ServerboundHello struct {
	Name      pk.String
	ProfileID pk.UUID
}

// PacketID returns the serverbound id of ServerboundHello.
func (ServerboundHello) PacketID() packetid.ServerboundPacketID {
	return packetid.ServerboundLoginHello
}

func (p *ServerboundHello) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&p.Name, &p.ProfileID}.ReadFrom(r)
}

func (p ServerboundHello) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{p.Name, p.ProfileID}.WriteTo(w)
}

// Key is serverbound/minecraft:key (0x01), Java ServerboundKeyPacket.
type Key struct {
	Keybytes           pk.ByteArray
	EncryptedChallenge pk.ByteArray
}

// PacketID returns the serverbound id of Key.
func (Key) PacketID() packetid.ServerboundPacketID { return packetid.ServerboundLoginKey }

func (p *Key) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&p.Keybytes, &p.EncryptedChallenge}.ReadFrom(r)
}

func (p Key) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{p.Keybytes, p.EncryptedChallenge}.WriteTo(w)
}

// CustomQueryAnswer is serverbound/minecraft:custom_query_answer (0x02), Java ServerboundCustomQueryAnswerPacket.
type CustomQueryAnswer struct {
	TransactionID pk.VarInt
	Payload       pk.Option[types.RestBytes, *types.RestBytes]
}

// PacketID returns the serverbound id of CustomQueryAnswer.
func (CustomQueryAnswer) PacketID() packetid.ServerboundPacketID {
	return packetid.ServerboundLoginCustomQueryAnswer
}

func (p *CustomQueryAnswer) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&p.TransactionID, &p.Payload}.ReadFrom(r)
}

func (p CustomQueryAnswer) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{p.TransactionID, p.Payload}.WriteTo(w)
}

// LoginAcknowledged is serverbound/minecraft:login_acknowledged (0x03), Java ServerboundLoginAcknowledgedPacket.
type LoginAcknowledged struct{ types.Empty }

// PacketID returns the serverbound id of LoginAcknowledged.
func (LoginAcknowledged) PacketID() packetid.ServerboundPacketID {
	return packetid.ServerboundLoginLoginAcknowledged
}

// CookieResponse is serverbound/minecraft:cookie_response (0x04), Java ServerboundCookieResponsePacket.
type CookieResponse struct {
	Key     pk.Identifier
	Payload pk.Option[pk.ByteArray, *pk.ByteArray]
}

// PacketID returns the serverbound id of CookieResponse.
func (CookieResponse) PacketID() packetid.ServerboundPacketID {
	return packetid.ServerboundLoginCookieResponse
}

func (p *CookieResponse) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&p.Key, &p.Payload}.ReadFrom(r)
}

func (p CookieResponse) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{p.Key, p.Payload}.WriteTo(w)
}
