// Code generated by gen/gen_registryid.go from 26.2/registries.json; DO NOT EDIT.

package registryid

var BlockPredicateType = []string{
	"minecraft:matching_blocks",
	"minecraft:matching_block_tag",
	"minecraft:matching_fluids",
	"minecraft:matching_biomes",
	"minecraft:has_sturdy_face",
	"minecraft:solid",
	"minecraft:replaceable",
	"minecraft:would_survive",
	"minecraft:inside_world_bounds",
	"minecraft:any_of",
	"minecraft:all_of",
	"minecraft:not",
	"minecraft:true",
	"minecraft:unobstructed",
}
