// Code generated by gen/gen_registryid.go from 26.1/registries.json; DO NOT EDIT.

package registryid

var ConsumeEffectType = []string{
	"minecraft:apply_effects",
	"minecraft:remove_effects",
	"minecraft:clear_all_effects",
	"minecraft:teleport_randomly",
	"minecraft:play_sound",
}
