// Code generated by gen/gen_registryid.go from 26.3/registries.json; DO NOT EDIT.

package registryid

var ContextFloatProviderType = []string{
	"minecraft:abs",
	"minecraft:avg",
	"minecraft:ceil",
	"minecraft:conditional",
	"minecraft:constant",
	"minecraft:cos",
	"minecraft:sub",
	"minecraft:enchantment_level",
	"minecraft:environment_attribute",
	"minecraft:floor",
	"minecraft:from_int",
	"minecraft:length",
	"minecraft:max",
	"minecraft:min",
	"minecraft:mod",
	"minecraft:negate",
	"minecraft:number_dispatcher",
	"minecraft:pow",
	"minecraft:mul",
	"minecraft:div",
	"minecraft:round",
	"minecraft:sin",
	"minecraft:sqrt",
	"minecraft:storage",
	"minecraft:add",
	"minecraft:truncate",
	"minecraft:uniform",
	"minecraft:weighted_list",
}
