// Code generated by gen/gen_registryid.go from 26.3/registries.json; DO NOT EDIT.

package registryid

var ContextIntProviderType = []string{
	"minecraft:abs",
	"minecraft:avg",
	"minecraft:binomial",
	"minecraft:conditional",
	"minecraft:constant",
	"minecraft:sub",
	"minecraft:environment_attribute",
	"minecraft:from_float",
	"minecraft:max",
	"minecraft:min",
	"minecraft:floor_mod",
	"minecraft:floor_div",
	"minecraft:mod",
	"minecraft:div",
	"minecraft:negate",
	"minecraft:number_dispatcher",
	"minecraft:pow",
	"minecraft:mul",
	"minecraft:score",
	"minecraft:storage",
	"minecraft:add",
	"minecraft:uniform",
	"minecraft:weighted_list",
}
