// Code generated by gen/gen_registryid.go from 26.3/registries.json; DO NOT EDIT.

package registryid

var DataComponentPredicateType = []string{
	"minecraft:damage",
	"minecraft:enchantments",
	"minecraft:stored_enchantments",
	"minecraft:potion_contents",
	"minecraft:custom_data",
	"minecraft:container",
	"minecraft:bundle_contents",
	"minecraft:firework_explosion",
	"minecraft:fireworks",
	"minecraft:writable_book_content",
	"minecraft:written_book_content",
	"minecraft:attribute_modifiers",
	"minecraft:trim",
	"minecraft:jukebox_playable",
	"minecraft:villager/variant",
}
