// Code generated by gen/gen_registryid.go from 26.3/registries.json; DO NOT EDIT.

package registryid

var DebugSubscription = []string{
	"minecraft:dedicated_server_tick_time",
	"minecraft:bees",
	"minecraft:brains",
	"minecraft:breezes",
	"minecraft:goal_selectors",
	"minecraft:entity_paths",
	"minecraft:entity_block_intersections",
	"minecraft:bee_hives",
	"minecraft:pois",
	"minecraft:redstone_wire_orientations",
	"minecraft:village_sections",
	"minecraft:raids",
	"minecraft:structures",
	"minecraft:game_event_listeners",
	"minecraft:neighbor_updates",
	"minecraft:game_events",
}
