// Code generated by gen/gen_registryid.go from 26.1/registries.json; DO NOT EDIT.

package registryid

var DialogType = []string{
	"minecraft:notice",
	"minecraft:server_links",
	"minecraft:dialog_list",
	"minecraft:multi_action",
	"minecraft:confirmation",
}
