// Code generated by gen/gen_registryid.go from 26.3/registries.json; DO NOT EDIT.

package registryid

var EnchantmentLevelBasedValueType = []string{
	"minecraft:clamped",
	"minecraft:fraction",
	"minecraft:levels_squared",
	"minecraft:linear",
	"minecraft:exponent",
	"minecraft:lookup",
}
