// Code generated by gen/gen_registryid.go from 26.1/registries.json; DO NOT EDIT.

package registryid

var EntitySubPredicateType = []string{
	"minecraft:lightning",
	"minecraft:fishing_hook",
	"minecraft:player",
	"minecraft:slime",
	"minecraft:raider",
	"minecraft:sheep",
}
