// Code generated by gen/gen_registryid.go from 26.2/registries.json; DO NOT EDIT.

package registryid

var EntitySubPredicateType = []string{
	"minecraft:entity_type",
	"minecraft:location",
	"minecraft:stepping_on",
	"minecraft:movement_affected_by",
	"minecraft:distance",
	"minecraft:movement",
	"minecraft:effects",
	"minecraft:nbt",
	"minecraft:flags",
	"minecraft:equipment",
	"minecraft:periodic_tick",
	"minecraft:vehicle",
	"minecraft:passenger",
	"minecraft:targeted_entity",
	"minecraft:team",
	"minecraft:slots",
	"minecraft:components",
	"minecraft:predicates",
	"minecraft:entity_tags",
	"minecraft:type_specific/lightning",
	"minecraft:type_specific/fishing_hook",
	"minecraft:type_specific/player",
	"minecraft:type_specific/cube_mob",
	"minecraft:type_specific/raider",
	"minecraft:type_specific/sheep",
}
