// Code generated by gen/gen_registryid.go from 26.3/registries.json; DO NOT EDIT.

package registryid

var FloatProviderType = []string{
	"minecraft:constant",
	"minecraft:uniform",
	"minecraft:clamped_normal",
	"minecraft:trapezoid",
}
