// Code generated by gen/gen_registryid.go from 26.2/registries.json; DO NOT EDIT.

package registryid

var HeightProviderType = []string{
	"minecraft:constant",
	"minecraft:uniform",
	"minecraft:biased_to_bottom",
	"minecraft:very_biased_to_bottom",
	"minecraft:trapezoid",
	"minecraft:weighted_list",
}
