// Code generated by gen/gen_registryid.go from 26.2/registries.json; DO NOT EDIT.

package registryid

var InputControlType = []string{
	"minecraft:boolean",
	"minecraft:number_range",
	"minecraft:single_option",
	"minecraft:text",
}
