// Code generated by gen/gen_registryid.go from 26.2/registries.json; DO NOT EDIT.

package registryid

var IntProviderType = []string{
	"minecraft:constant",
	"minecraft:uniform",
	"minecraft:biased_to_bottom",
	"minecraft:clamped",
	"minecraft:weighted_list",
	"minecraft:clamped_normal",
	"minecraft:trapezoid",
}
