// Code generated by gen/gen_registryid.go from 26.3/registries.json; DO NOT EDIT.

package registryid

var OutgoingRpcMethods = []string{
	"minecraft:notification/server/started",
	"minecraft:notification/server/stopping",
	"minecraft:notification/server/saving",
	"minecraft:notification/server/saved",
	"minecraft:notification/server/activity",
	"minecraft:notification/world/upgrade_started",
	"minecraft:notification/world/upgrade_progress",
	"minecraft:notification/world/upgrade_finished",
	"minecraft:notification/world/upgrade_failed",
	"minecraft:notification/players/joined",
	"minecraft:notification/players/left",
	"minecraft:notification/operators/added",
	"minecraft:notification/operators/removed",
	"minecraft:notification/allowlist/added",
	"minecraft:notification/allowlist/removed",
	"minecraft:notification/ip_bans/added",
	"minecraft:notification/ip_bans/removed",
	"minecraft:notification/bans/added",
	"minecraft:notification/bans/removed",
	"minecraft:notification/gamerules/updated",
	"minecraft:notification/server/status",
}
