// Code generated by gen/gen_registryid.go from 26.2/registries.json; DO NOT EDIT.

package registryid

var PosRuleTest = []string{
	"minecraft:always_true",
	"minecraft:linear_pos",
	"minecraft:axis_aligned_linear_pos",
}
