// Code generated by gen/gen_registryid.go from 26.2/registries.json; DO NOT EDIT.

package registryid

var RecipeType = []string{
	"minecraft:crafting",
	"minecraft:smelting",
	"minecraft:blasting",
	"minecraft:smoking",
	"minecraft:campfire_cooking",
	"minecraft:stonecutting",
	"minecraft:smithing",
}
