// Code generated by gen/gen_registryid.go from 26.2/registries.json; DO NOT EDIT.

package registryid

var RecipeDisplay = []string{
	"minecraft:crafting_shapeless",
	"minecraft:crafting_shaped",
	"minecraft:furnace",
	"minecraft:stonecutter",
	"minecraft:smithing",
}
