// Code generated by gen/gen_registryid.go from 26.3/registries.json; DO NOT EDIT.

package registryid

var RuleTest = []string{
	"minecraft:all_of",
	"minecraft:always_true",
	"minecraft:any_of",
	"minecraft:block_match",
	"minecraft:blockstate_match",
	"minecraft:not",
	"minecraft:tag_match",
	"minecraft:height_match",
	"minecraft:random_block_match",
	"minecraft:random_blockstate_match",
}
