// Code generated by gen/gen_registryid.go from 26.3/registries.json; DO NOT EDIT.

package registryid

var SensorType = []string{
	"minecraft:dummy",
	"minecraft:nearest_items",
	"minecraft:nearest_living_entities",
	"minecraft:nearest_players",
	"minecraft:nearest_bed",
	"minecraft:hurt_by",
	"minecraft:villager_hostiles",
	"minecraft:villager_babies",
	"minecraft:secondary_pois",
	"minecraft:golem_detected",
	"minecraft:armadillo_scare_detected",
	"minecraft:piglin_specific_sensor",
	"minecraft:piglin_brute_specific_sensor",
	"minecraft:hoglin_specific_sensor",
	"minecraft:nearest_adult",
	"minecraft:nearest_adult_any_type",
	"minecraft:axolotl_attackables",
	"minecraft:food_temptations",
	"minecraft:frog_temptations",
	"minecraft:nautilus_temptations",
	"minecraft:frog_attackables",
	"minecraft:is_in_water",
	"minecraft:warden_entity_sensor",
	"minecraft:breeze_attack_entity_sensor",
}
