// Code generated by gen/gen_registryid.go from 26.2/registries.json; DO NOT EDIT.

package registryid

var WorldgenStructurePlacement = []string{
	"minecraft:random_spread",
	"minecraft:concentric_rings",
}
