// Code generated by gen/gen_registryid.go from 26.1/registries.json; DO NOT EDIT.

package registryid

var WorldgenChunkGenerator = []string{
	"minecraft:noise",
	"minecraft:flat",
	"minecraft:debug",
}
