// Code generated by gen/gen_registryid.go from 26.1/registries.json; DO NOT EDIT.

package registryid

var WorldgenCarver = []string{
	"minecraft:cave",
	"minecraft:nether_cave",
	"minecraft:canyon",
}
