// Code generated by gen/gen_registryid.go from 26.3/registries.json; DO NOT EDIT.

package registryid

var WorldgenPoolAliasBinding = []string{
	"minecraft:random",
	"minecraft:random_group",
	"minecraft:direct",
}
