// Code generated by gen/gen_registryid.go from 26.3/registries.json; DO NOT EDIT.

package registryid

var WorldgenStructureProcessor = []string{
	"minecraft:blackstone_replace",
	"minecraft:block_age",
	"minecraft:block_ignore",
	"minecraft:block_rot",
	"minecraft:capped",
	"minecraft:gravity",
	"minecraft:jigsaw_replacement",
	"minecraft:lava_submerged_block",
	"minecraft:nop",
	"minecraft:protected_blocks",
	"minecraft:rule",
}
