// Code generated by gen/gen_registryid.go from 26.3/registries.json; DO NOT EDIT.

package registryid

var WorldgenPlacementModifierType = []string{
	"minecraft:block_predicate_filter",
	"minecraft:rarity_filter",
	"minecraft:random_chance",
	"minecraft:surface_relative_threshold_filter",
	"minecraft:surface_water_depth_filter",
	"minecraft:biome",
	"minecraft:count",
	"minecraft:noise_based_count",
	"minecraft:noise_threshold_count",
	"minecraft:count_on_every_layer",
	"minecraft:cuboid",
	"minecraft:environment_scan",
	"minecraft:heightmap",
	"minecraft:height_range",
	"minecraft:in_square",
	"minecraft:offset",
	"minecraft:randomly_selected",
	"minecraft:fixed_placement",
}
