// Code generated by gen/gen_registryid.go from 26.3/registries.json; DO NOT EDIT.

package registryid

var WorldgenMaterialConditionType = []string{
	"minecraft:biome",
	"minecraft:noise_threshold",
	"minecraft:vertical_gradient",
	"minecraft:y_above",
	"minecraft:water",
	"minecraft:temperature",
	"minecraft:steep",
	"minecraft:not",
	"minecraft:hole",
	"minecraft:above_preliminary_surface",
	"minecraft:stone_depth",
}
