// Code generated by gen/gen_registryid.go from 26.3/registries.json; DO NOT EDIT.

package registryid

var WorldgenMaterialRuleType = []string{
	"minecraft:block",
	"minecraft:bandlands",
	"minecraft:sequence",
	"minecraft:condition",
	"minecraft:ore_vein",
}
