// Code generated by gen/gen_version.go from 26.2/version.json; DO NOT EDIT.
// Package version holds the Minecraft version this module was generated from.
// Every protocol constant in the library derives from it.
package version

const (
	// Name is the Minecraft version id ("26.2").
	Name = "26.2"
	// ProtocolVersion is the network protocol number sent in the handshake.
	ProtocolVersion = 776
	// DataVersion is the world/data version written to level.dat and chunks.
	DataVersion = 4903
	// ResourcePackVersion and DataPackVersion are the pack format numbers.
	ResourcePackVersion = 88
	DataPackVersion     = 107
	// JavaVersion is the JDK major version the server requires.
	JavaVersion = 25
	// BuildTime is Mojang's build timestamp of this version.
	BuildTime = "2026-06-16T12:01:27+00:00"
	// Stable is false for snapshots and pre-releases.
	Stable = true

	// DataSource names the extracted data this build was generated from.
	DataSource = "mc26-data v0.262.0"
	// Generator names the generator commit that produced this build.
	Generator = "mc26 190a89967ae4"
)
