// Code generated by gen/gen_packets.go from 26.2/packet_schema.json; DO NOT EDIT.
package wire

import (
	"io"

	pk "github.com/mj41/go-mc26/net/packet"
)

var _ = io.EOF

// Direction is Java Direction, sent as a VarInt ordinal.
type Direction pk.VarInt

const (
	DirectionDown Direction = iota
	DirectionUp
	DirectionNorth
	DirectionSouth
	DirectionWest
	DirectionEast
)

func (e *Direction) ReadFrom(r io.Reader) (int64, error) { return (*pk.VarInt)(e).ReadFrom(r) }
func (e Direction) WriteTo(w io.Writer) (int64, error)   { return pk.VarInt(e).WriteTo(w) }

// Count is the number of constants (EnumSet[Direction] needs it for its bit set size).
func (Direction) Count() int { return 6 }

var directionNames = [...]string{"down", "up", "north", "south", "west", "east"}

// Name is the name the constant's codec writes, "" for a number out of range.
func (e Direction) Name() string {
	if e < 0 || int(e) >= len(directionNames) {
		return ""
	}
	return directionNames[e]
}
