// Code generated by gen/gen_packets.go from 26.1/packet_schema.json + packets.json; DO NOT EDIT.
package status

import (
	"bytes"
	"io"
	"testing"
)

// TestClientboundRoundTrip encodes the zero value of every generated clientbound packet,
// decodes it and encodes it again; the two encodings must match.
func TestClientboundRoundTrip(t *testing.T) {
	type codec interface {
		io.WriterTo
	}
	cases := []struct {
		name string
		zero codec
		read func(io.Reader) (codec, error)
	}{
		{"StatusResponse", StatusResponse{}, func(r io.Reader) (codec, error) { var v StatusResponse; _, err := v.ReadFrom(r); return v, err }},
		{"PongResponse", PongResponse{}, func(r io.Reader) (codec, error) { var v PongResponse; _, err := v.ReadFrom(r); return v, err }},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			var a bytes.Buffer
			if _, err := c.zero.WriteTo(&a); err != nil {
				t.Fatalf("encode: %v", err)
			}
			v, err := c.read(bytes.NewReader(a.Bytes()))
			if err != nil {
				t.Fatalf("decode %x: %v", a.Bytes(), err)
			}
			var b bytes.Buffer
			if _, err := v.WriteTo(&b); err != nil {
				t.Fatalf("re-encode: %v", err)
			}
			if !bytes.Equal(a.Bytes(), b.Bytes()) {
				t.Fatalf("round trip differs: %x vs %x", a.Bytes(), b.Bytes())
			}
		})
	}
}
