// Code generated by gen/gen_packets.go from 26.3/packet_schema.json + packets.json; DO NOT EDIT.
package play

import (
	"bytes"
	"io"
	"testing"
)

// TestClientboundRoundTrip encodes the zero value of every generated clientbound packet,
// decodes it and encodes it again; the two encodings must match.
func TestClientboundRoundTrip(t *testing.T) {
	type codec interface {
		io.WriterTo
	}
	cases := []struct {
		name string
		zero codec
		read func(io.Reader) (codec, error)
	}{
		{"AddEntity", AddEntity{}, func(r io.Reader) (codec, error) { var v AddEntity; _, err := v.ReadFrom(r); return v, err }},
		{"Animate", Animate{}, func(r io.Reader) (codec, error) { var v Animate; _, err := v.ReadFrom(r); return v, err }},
		{"AwardStats", AwardStats{}, func(r io.Reader) (codec, error) { var v AwardStats; _, err := v.ReadFrom(r); return v, err }},
		{"BlockChangedAck", BlockChangedAck{}, func(r io.Reader) (codec, error) { var v BlockChangedAck; _, err := v.ReadFrom(r); return v, err }},
		{"BlockDestruction", BlockDestruction{}, func(r io.Reader) (codec, error) { var v BlockDestruction; _, err := v.ReadFrom(r); return v, err }},
		{"BlockEntityData", BlockEntityData{}, func(r io.Reader) (codec, error) { var v BlockEntityData; _, err := v.ReadFrom(r); return v, err }},
		{"BlockEvent", BlockEvent{}, func(r io.Reader) (codec, error) { var v BlockEvent; _, err := v.ReadFrom(r); return v, err }},
		{"BlockUpdate", BlockUpdate{}, func(r io.Reader) (codec, error) { var v BlockUpdate; _, err := v.ReadFrom(r); return v, err }},
		{"BossEvent", BossEvent{}, func(r io.Reader) (codec, error) { var v BossEvent; _, err := v.ReadFrom(r); return v, err }},
		{"ClientboundChangeDifficulty", ClientboundChangeDifficulty{}, func(r io.Reader) (codec, error) {
			var v ClientboundChangeDifficulty
			_, err := v.ReadFrom(r)
			return v, err
		}},
		{"ChunkBatchFinished", ChunkBatchFinished{}, func(r io.Reader) (codec, error) { var v ChunkBatchFinished; _, err := v.ReadFrom(r); return v, err }},
		{"ChunksBiomes", ChunksBiomes{}, func(r io.Reader) (codec, error) { var v ChunksBiomes; _, err := v.ReadFrom(r); return v, err }},
		{"ClearTitles", ClearTitles{}, func(r io.Reader) (codec, error) { var v ClearTitles; _, err := v.ReadFrom(r); return v, err }},
		{"CommandSuggestions", CommandSuggestions{}, func(r io.Reader) (codec, error) { var v CommandSuggestions; _, err := v.ReadFrom(r); return v, err }},
		{"Commands", Commands{}, func(r io.Reader) (codec, error) { var v Commands; _, err := v.ReadFrom(r); return v, err }},
		{"ClientboundContainerClose", ClientboundContainerClose{}, func(r io.Reader) (codec, error) {
			var v ClientboundContainerClose
			_, err := v.ReadFrom(r)
			return v, err
		}},
		{"ContainerSetContent", ContainerSetContent{}, func(r io.Reader) (codec, error) { var v ContainerSetContent; _, err := v.ReadFrom(r); return v, err }},
		{"ContainerSetData", ContainerSetData{}, func(r io.Reader) (codec, error) { var v ContainerSetData; _, err := v.ReadFrom(r); return v, err }},
		{"ContainerSetSlot", ContainerSetSlot{}, func(r io.Reader) (codec, error) { var v ContainerSetSlot; _, err := v.ReadFrom(r); return v, err }},
		{"CookieRequest", CookieRequest{}, func(r io.Reader) (codec, error) { var v CookieRequest; _, err := v.ReadFrom(r); return v, err }},
		{"Cooldown", Cooldown{}, func(r io.Reader) (codec, error) { var v Cooldown; _, err := v.ReadFrom(r); return v, err }},
		{"CustomChatCompletions", CustomChatCompletions{}, func(r io.Reader) (codec, error) { var v CustomChatCompletions; _, err := v.ReadFrom(r); return v, err }},
		{"ClientboundCustomPayload", ClientboundCustomPayload{}, func(r io.Reader) (codec, error) {
			var v ClientboundCustomPayload
			_, err := v.ReadFrom(r)
			return v, err
		}},
		{"DamageEvent", DamageEvent{}, func(r io.Reader) (codec, error) { var v DamageEvent; _, err := v.ReadFrom(r); return v, err }},
		{"DebugBlockValue", DebugBlockValue{}, func(r io.Reader) (codec, error) { var v DebugBlockValue; _, err := v.ReadFrom(r); return v, err }},
		{"DebugChunkValue", DebugChunkValue{}, func(r io.Reader) (codec, error) { var v DebugChunkValue; _, err := v.ReadFrom(r); return v, err }},
		{"DebugEntityValue", DebugEntityValue{}, func(r io.Reader) (codec, error) { var v DebugEntityValue; _, err := v.ReadFrom(r); return v, err }},
		{"DebugEvent", DebugEvent{}, func(r io.Reader) (codec, error) { var v DebugEvent; _, err := v.ReadFrom(r); return v, err }},
		{"DebugSample", DebugSample{}, func(r io.Reader) (codec, error) { var v DebugSample; _, err := v.ReadFrom(r); return v, err }},
		{"DeleteChat", DeleteChat{}, func(r io.Reader) (codec, error) { var v DeleteChat; _, err := v.ReadFrom(r); return v, err }},
		{"Disconnect", Disconnect{}, func(r io.Reader) (codec, error) { var v Disconnect; _, err := v.ReadFrom(r); return v, err }},
		{"DisguisedChat", DisguisedChat{}, func(r io.Reader) (codec, error) { var v DisguisedChat; _, err := v.ReadFrom(r); return v, err }},
		{"EntityEvent", EntityEvent{}, func(r io.Reader) (codec, error) { var v EntityEvent; _, err := v.ReadFrom(r); return v, err }},
		{"EntityPositionSync", EntityPositionSync{}, func(r io.Reader) (codec, error) { var v EntityPositionSync; _, err := v.ReadFrom(r); return v, err }},
		{"Explode", Explode{}, func(r io.Reader) (codec, error) { var v Explode; _, err := v.ReadFrom(r); return v, err }},
		{"AddTransientBlock", AddTransientBlock{}, func(r io.Reader) (codec, error) { var v AddTransientBlock; _, err := v.ReadFrom(r); return v, err }},
		{"ForgetLevelChunk", ForgetLevelChunk{}, func(r io.Reader) (codec, error) { var v ForgetLevelChunk; _, err := v.ReadFrom(r); return v, err }},
		{"GameEvent", GameEvent{}, func(r io.Reader) (codec, error) { var v GameEvent; _, err := v.ReadFrom(r); return v, err }},
		{"GameRuleValues", GameRuleValues{}, func(r io.Reader) (codec, error) { var v GameRuleValues; _, err := v.ReadFrom(r); return v, err }},
		{"GameTestHighlightPos", GameTestHighlightPos{}, func(r io.Reader) (codec, error) { var v GameTestHighlightPos; _, err := v.ReadFrom(r); return v, err }},
		{"MountScreenOpen", MountScreenOpen{}, func(r io.Reader) (codec, error) { var v MountScreenOpen; _, err := v.ReadFrom(r); return v, err }},
		{"HurtAnimation", HurtAnimation{}, func(r io.Reader) (codec, error) { var v HurtAnimation; _, err := v.ReadFrom(r); return v, err }},
		{"InitializeBorder", InitializeBorder{}, func(r io.Reader) (codec, error) { var v InitializeBorder; _, err := v.ReadFrom(r); return v, err }},
		{"ClientboundKeepAlive", ClientboundKeepAlive{}, func(r io.Reader) (codec, error) { var v ClientboundKeepAlive; _, err := v.ReadFrom(r); return v, err }},
		{"LevelChunkWithLight", LevelChunkWithLight{}, func(r io.Reader) (codec, error) { var v LevelChunkWithLight; _, err := v.ReadFrom(r); return v, err }},
		{"LevelEvent", LevelEvent{}, func(r io.Reader) (codec, error) { var v LevelEvent; _, err := v.ReadFrom(r); return v, err }},
		{"LevelParticles", LevelParticles{}, func(r io.Reader) (codec, error) { var v LevelParticles; _, err := v.ReadFrom(r); return v, err }},
		{"LightUpdate", LightUpdate{}, func(r io.Reader) (codec, error) { var v LightUpdate; _, err := v.ReadFrom(r); return v, err }},
		{"Login", Login{}, func(r io.Reader) (codec, error) { var v Login; _, err := v.ReadFrom(r); return v, err }},
		{"MapItemData", MapItemData{}, func(r io.Reader) (codec, error) { var v MapItemData; _, err := v.ReadFrom(r); return v, err }},
		{"MerchantOffers", MerchantOffers{}, func(r io.Reader) (codec, error) { var v MerchantOffers; _, err := v.ReadFrom(r); return v, err }},
		{"MoveEntityPos", MoveEntityPos{}, func(r io.Reader) (codec, error) { var v MoveEntityPos; _, err := v.ReadFrom(r); return v, err }},
		{"MoveEntityPosRot", MoveEntityPosRot{}, func(r io.Reader) (codec, error) { var v MoveEntityPosRot; _, err := v.ReadFrom(r); return v, err }},
		{"MoveMinecart", MoveMinecart{}, func(r io.Reader) (codec, error) { var v MoveMinecart; _, err := v.ReadFrom(r); return v, err }},
		{"MoveEntityRot", MoveEntityRot{}, func(r io.Reader) (codec, error) { var v MoveEntityRot; _, err := v.ReadFrom(r); return v, err }},
		{"ClientboundMoveVehicle", ClientboundMoveVehicle{}, func(r io.Reader) (codec, error) { var v ClientboundMoveVehicle; _, err := v.ReadFrom(r); return v, err }},
		{"OpenBook", OpenBook{}, func(r io.Reader) (codec, error) { var v OpenBook; _, err := v.ReadFrom(r); return v, err }},
		{"OpenScreen", OpenScreen{}, func(r io.Reader) (codec, error) { var v OpenScreen; _, err := v.ReadFrom(r); return v, err }},
		{"OpenSignEditor", OpenSignEditor{}, func(r io.Reader) (codec, error) { var v OpenSignEditor; _, err := v.ReadFrom(r); return v, err }},
		{"Ping", Ping{}, func(r io.Reader) (codec, error) { var v Ping; _, err := v.ReadFrom(r); return v, err }},
		{"PongResponse", PongResponse{}, func(r io.Reader) (codec, error) { var v PongResponse; _, err := v.ReadFrom(r); return v, err }},
		{"PlaceGhostRecipe", PlaceGhostRecipe{}, func(r io.Reader) (codec, error) { var v PlaceGhostRecipe; _, err := v.ReadFrom(r); return v, err }},
		{"ClientboundPlayerAbilities", ClientboundPlayerAbilities{}, func(r io.Reader) (codec, error) {
			var v ClientboundPlayerAbilities
			_, err := v.ReadFrom(r)
			return v, err
		}},
		{"PlayerChat", PlayerChat{}, func(r io.Reader) (codec, error) { var v PlayerChat; _, err := v.ReadFrom(r); return v, err }},
		{"PlayerCombatEnd", PlayerCombatEnd{}, func(r io.Reader) (codec, error) { var v PlayerCombatEnd; _, err := v.ReadFrom(r); return v, err }},
		{"PlayerCombatKill", PlayerCombatKill{}, func(r io.Reader) (codec, error) { var v PlayerCombatKill; _, err := v.ReadFrom(r); return v, err }},
		{"PlayerInfoRemove", PlayerInfoRemove{}, func(r io.Reader) (codec, error) { var v PlayerInfoRemove; _, err := v.ReadFrom(r); return v, err }},
		{"PlayerInfoUpdate", PlayerInfoUpdate{}, func(r io.Reader) (codec, error) { var v PlayerInfoUpdate; _, err := v.ReadFrom(r); return v, err }},
		{"PlayerLookAt", PlayerLookAt{}, func(r io.Reader) (codec, error) { var v PlayerLookAt; _, err := v.ReadFrom(r); return v, err }},
		{"PlayerPosition", PlayerPosition{}, func(r io.Reader) (codec, error) { var v PlayerPosition; _, err := v.ReadFrom(r); return v, err }},
		{"PlayerRotation", PlayerRotation{}, func(r io.Reader) (codec, error) { var v PlayerRotation; _, err := v.ReadFrom(r); return v, err }},
		{"RecipeBookAdd", RecipeBookAdd{}, func(r io.Reader) (codec, error) { var v RecipeBookAdd; _, err := v.ReadFrom(r); return v, err }},
		{"RecipeBookRemove", RecipeBookRemove{}, func(r io.Reader) (codec, error) { var v RecipeBookRemove; _, err := v.ReadFrom(r); return v, err }},
		{"RecipeBookSettings", RecipeBookSettings{}, func(r io.Reader) (codec, error) { var v RecipeBookSettings; _, err := v.ReadFrom(r); return v, err }},
		{"RemoveEntities", RemoveEntities{}, func(r io.Reader) (codec, error) { var v RemoveEntities; _, err := v.ReadFrom(r); return v, err }},
		{"RemoveMobEffect", RemoveMobEffect{}, func(r io.Reader) (codec, error) { var v RemoveMobEffect; _, err := v.ReadFrom(r); return v, err }},
		{"ResetScore", ResetScore{}, func(r io.Reader) (codec, error) { var v ResetScore; _, err := v.ReadFrom(r); return v, err }},
		{"ResourcePackPop", ResourcePackPop{}, func(r io.Reader) (codec, error) { var v ResourcePackPop; _, err := v.ReadFrom(r); return v, err }},
		{"ResourcePackPush", ResourcePackPush{}, func(r io.Reader) (codec, error) { var v ResourcePackPush; _, err := v.ReadFrom(r); return v, err }},
		{"PostEffects", PostEffects{}, func(r io.Reader) (codec, error) { var v PostEffects; _, err := v.ReadFrom(r); return v, err }},
		{"Respawn", Respawn{}, func(r io.Reader) (codec, error) { var v Respawn; _, err := v.ReadFrom(r); return v, err }},
		{"RotateHead", RotateHead{}, func(r io.Reader) (codec, error) { var v RotateHead; _, err := v.ReadFrom(r); return v, err }},
		{"SectionBlocksUpdate", SectionBlocksUpdate{}, func(r io.Reader) (codec, error) { var v SectionBlocksUpdate; _, err := v.ReadFrom(r); return v, err }},
		{"SelectAdvancementsTab", SelectAdvancementsTab{}, func(r io.Reader) (codec, error) { var v SelectAdvancementsTab; _, err := v.ReadFrom(r); return v, err }},
		{"ServerData", ServerData{}, func(r io.Reader) (codec, error) { var v ServerData; _, err := v.ReadFrom(r); return v, err }},
		{"SetActionBarText", SetActionBarText{}, func(r io.Reader) (codec, error) { var v SetActionBarText; _, err := v.ReadFrom(r); return v, err }},
		{"SetBorderCenter", SetBorderCenter{}, func(r io.Reader) (codec, error) { var v SetBorderCenter; _, err := v.ReadFrom(r); return v, err }},
		{"SetBorderLerpSize", SetBorderLerpSize{}, func(r io.Reader) (codec, error) { var v SetBorderLerpSize; _, err := v.ReadFrom(r); return v, err }},
		{"SetBorderSize", SetBorderSize{}, func(r io.Reader) (codec, error) { var v SetBorderSize; _, err := v.ReadFrom(r); return v, err }},
		{"SetBorderWarningDelay", SetBorderWarningDelay{}, func(r io.Reader) (codec, error) { var v SetBorderWarningDelay; _, err := v.ReadFrom(r); return v, err }},
		{"SetBorderWarningDistance", SetBorderWarningDistance{}, func(r io.Reader) (codec, error) {
			var v SetBorderWarningDistance
			_, err := v.ReadFrom(r)
			return v, err
		}},
		{"SetCamera", SetCamera{}, func(r io.Reader) (codec, error) { var v SetCamera; _, err := v.ReadFrom(r); return v, err }},
		{"SetChunkCacheCenter", SetChunkCacheCenter{}, func(r io.Reader) (codec, error) { var v SetChunkCacheCenter; _, err := v.ReadFrom(r); return v, err }},
		{"SetChunkCacheRadius", SetChunkCacheRadius{}, func(r io.Reader) (codec, error) { var v SetChunkCacheRadius; _, err := v.ReadFrom(r); return v, err }},
		{"SetCursorItem", SetCursorItem{}, func(r io.Reader) (codec, error) { var v SetCursorItem; _, err := v.ReadFrom(r); return v, err }},
		{"SetDefaultSpawnPosition", SetDefaultSpawnPosition{}, func(r io.Reader) (codec, error) {
			var v SetDefaultSpawnPosition
			_, err := v.ReadFrom(r)
			return v, err
		}},
		{"SetDisplayObjective", SetDisplayObjective{}, func(r io.Reader) (codec, error) { var v SetDisplayObjective; _, err := v.ReadFrom(r); return v, err }},
		{"SetEntityData", SetEntityData{}, func(r io.Reader) (codec, error) { var v SetEntityData; _, err := v.ReadFrom(r); return v, err }},
		{"SetEntityLink", SetEntityLink{}, func(r io.Reader) (codec, error) { var v SetEntityLink; _, err := v.ReadFrom(r); return v, err }},
		{"SetEntityMotion", SetEntityMotion{}, func(r io.Reader) (codec, error) { var v SetEntityMotion; _, err := v.ReadFrom(r); return v, err }},
		{"SetExperience", SetExperience{}, func(r io.Reader) (codec, error) { var v SetExperience; _, err := v.ReadFrom(r); return v, err }},
		{"SetHealth", SetHealth{}, func(r io.Reader) (codec, error) { var v SetHealth; _, err := v.ReadFrom(r); return v, err }},
		{"SetHeldSlot", SetHeldSlot{}, func(r io.Reader) (codec, error) { var v SetHeldSlot; _, err := v.ReadFrom(r); return v, err }},
		{"SetObjective", SetObjective{}, func(r io.Reader) (codec, error) { var v SetObjective; _, err := v.ReadFrom(r); return v, err }},
		{"SetPassengers", SetPassengers{}, func(r io.Reader) (codec, error) { var v SetPassengers; _, err := v.ReadFrom(r); return v, err }},
		{"SetPlayerInventory", SetPlayerInventory{}, func(r io.Reader) (codec, error) { var v SetPlayerInventory; _, err := v.ReadFrom(r); return v, err }},
		{"SetPlayerTeam", SetPlayerTeam{}, func(r io.Reader) (codec, error) { var v SetPlayerTeam; _, err := v.ReadFrom(r); return v, err }},
		{"SetScore", SetScore{}, func(r io.Reader) (codec, error) { var v SetScore; _, err := v.ReadFrom(r); return v, err }},
		{"SetSimulationDistance", SetSimulationDistance{}, func(r io.Reader) (codec, error) { var v SetSimulationDistance; _, err := v.ReadFrom(r); return v, err }},
		{"SetSubtitleText", SetSubtitleText{}, func(r io.Reader) (codec, error) { var v SetSubtitleText; _, err := v.ReadFrom(r); return v, err }},
		{"SetTime", SetTime{}, func(r io.Reader) (codec, error) { var v SetTime; _, err := v.ReadFrom(r); return v, err }},
		{"SetTitleText", SetTitleText{}, func(r io.Reader) (codec, error) { var v SetTitleText; _, err := v.ReadFrom(r); return v, err }},
		{"SetTitlesAnimation", SetTitlesAnimation{}, func(r io.Reader) (codec, error) { var v SetTitlesAnimation; _, err := v.ReadFrom(r); return v, err }},
		{"SoundEntity", SoundEntity{}, func(r io.Reader) (codec, error) { var v SoundEntity; _, err := v.ReadFrom(r); return v, err }},
		{"Sound", Sound{}, func(r io.Reader) (codec, error) { var v Sound; _, err := v.ReadFrom(r); return v, err }},
		{"StopSound", StopSound{}, func(r io.Reader) (codec, error) { var v StopSound; _, err := v.ReadFrom(r); return v, err }},
		{"StoreCookie", StoreCookie{}, func(r io.Reader) (codec, error) { var v StoreCookie; _, err := v.ReadFrom(r); return v, err }},
		{"SwingAnimation", SwingAnimation{}, func(r io.Reader) (codec, error) { var v SwingAnimation; _, err := v.ReadFrom(r); return v, err }},
		{"SystemChat", SystemChat{}, func(r io.Reader) (codec, error) { var v SystemChat; _, err := v.ReadFrom(r); return v, err }},
		{"TabList", TabList{}, func(r io.Reader) (codec, error) { var v TabList; _, err := v.ReadFrom(r); return v, err }},
		{"TagQuery", TagQuery{}, func(r io.Reader) (codec, error) { var v TagQuery; _, err := v.ReadFrom(r); return v, err }},
		{"TakeItemEntity", TakeItemEntity{}, func(r io.Reader) (codec, error) { var v TakeItemEntity; _, err := v.ReadFrom(r); return v, err }},
		{"TeleportEntity", TeleportEntity{}, func(r io.Reader) (codec, error) { var v TeleportEntity; _, err := v.ReadFrom(r); return v, err }},
		{"TestInstanceBlockStatus", TestInstanceBlockStatus{}, func(r io.Reader) (codec, error) {
			var v TestInstanceBlockStatus
			_, err := v.ReadFrom(r)
			return v, err
		}},
		{"TickingState", TickingState{}, func(r io.Reader) (codec, error) { var v TickingState; _, err := v.ReadFrom(r); return v, err }},
		{"TickingStep", TickingStep{}, func(r io.Reader) (codec, error) { var v TickingStep; _, err := v.ReadFrom(r); return v, err }},
		{"Transfer", Transfer{}, func(r io.Reader) (codec, error) { var v Transfer; _, err := v.ReadFrom(r); return v, err }},
		{"UpdateAdvancements", UpdateAdvancements{}, func(r io.Reader) (codec, error) { var v UpdateAdvancements; _, err := v.ReadFrom(r); return v, err }},
		{"UpdateAttributes", UpdateAttributes{}, func(r io.Reader) (codec, error) { var v UpdateAttributes; _, err := v.ReadFrom(r); return v, err }},
		{"UpdateMobEffect", UpdateMobEffect{}, func(r io.Reader) (codec, error) { var v UpdateMobEffect; _, err := v.ReadFrom(r); return v, err }},
		{"UpdateRecipes", UpdateRecipes{}, func(r io.Reader) (codec, error) { var v UpdateRecipes; _, err := v.ReadFrom(r); return v, err }},
		{"UpdateTags", UpdateTags{}, func(r io.Reader) (codec, error) { var v UpdateTags; _, err := v.ReadFrom(r); return v, err }},
		{"ProjectilePower", ProjectilePower{}, func(r io.Reader) (codec, error) { var v ProjectilePower; _, err := v.ReadFrom(r); return v, err }},
		{"CustomReportDetails", CustomReportDetails{}, func(r io.Reader) (codec, error) { var v CustomReportDetails; _, err := v.ReadFrom(r); return v, err }},
		{"ServerLinks", ServerLinks{}, func(r io.Reader) (codec, error) { var v ServerLinks; _, err := v.ReadFrom(r); return v, err }},
		{"TrackedWaypoint", TrackedWaypoint{}, func(r io.Reader) (codec, error) { var v TrackedWaypoint; _, err := v.ReadFrom(r); return v, err }},
		{"ShowDialog", ShowDialog{}, func(r io.Reader) (codec, error) { var v ShowDialog; _, err := v.ReadFrom(r); return v, err }},
		// no zero value to round-trip: SetEquipment (SetEquipmentEntryList is never empty on the wire)
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			var a bytes.Buffer
			if _, err := c.zero.WriteTo(&a); err != nil {
				t.Fatalf("encode: %v", err)
			}
			v, err := c.read(bytes.NewReader(a.Bytes()))
			if err != nil {
				t.Fatalf("decode %x: %v", a.Bytes(), err)
			}
			var b bytes.Buffer
			if _, err := v.WriteTo(&b); err != nil {
				t.Fatalf("re-encode: %v", err)
			}
			if !bytes.Equal(a.Bytes(), b.Bytes()) {
				t.Fatalf("round trip differs: %x vs %x", a.Bytes(), b.Bytes())
			}
		})
	}
}
