// Code generated by gen/gen_entitydata.go from 26.2/entity_data.json; DO NOT EDIT.

// The entity metadata serializers: what a set_entity_data value is, by serializer id.
package types

import (
	"fmt"

	pk "github.com/mj41/go-mc26/net/packet"
)

// EntityDataSerializers names the entity data serializer ids of Minecraft 26.2
// (EntityDataSerializers, in registration order).
var EntityDataSerializers = []string{"BYTE", "INT", "LONG", "FLOAT", "STRING", "COMPONENT", "OPTIONAL_COMPONENT", "ITEM_STACK", "BOOLEAN", "ROTATIONS", "BLOCK_POS", "OPTIONAL_BLOCK_POS", "DIRECTION", "OPTIONAL_LIVING_ENTITY_REFERENCE", "BLOCK_STATE", "OPTIONAL_BLOCK_STATE", "PARTICLE", "PARTICLES", "VILLAGER_DATA", "OPTIONAL_UNSIGNED_INT", "POSE", "CAT_VARIANT", "CAT_SOUND_VARIANT", "COW_VARIANT", "COW_SOUND_VARIANT", "WOLF_VARIANT", "WOLF_SOUND_VARIANT", "FROG_VARIANT", "PIG_VARIANT", "PIG_SOUND_VARIANT", "CHICKEN_VARIANT", "CHICKEN_SOUND_VARIANT", "ZOMBIE_NAUTILUS_VARIANT", "OPTIONAL_GLOBAL_POS", "PAINTING_VARIANT", "SNIFFER_STATE", "ARMADILLO_STATE", "COPPER_GOLEM_STATE", "WEATHERING_COPPER_STATE", "VECTOR3", "QUATERNION", "RESOLVABLE_PROFILE", "HUMANOID_ARM"}

// NewEntityDataValue returns an empty value of the Go type a serializer id
// carries, ready to ReadFrom, or an error for a serializer whose wire form the
// schema does not type.
func NewEntityDataValue(serializer int32) (pk.Field, error) {
	switch serializer {
	case 0: // BYTE
		return new(pk.Byte), nil
	case 1: // INT
		return new(pk.VarInt), nil
	case 2: // LONG
		return new(pk.VarLong), nil
	case 3: // FLOAT
		return new(pk.Float), nil
	case 4: // STRING
		return new(pk.String), nil
	case 5: // COMPONENT
		return new(Text), nil
	case 6: // OPTIONAL_COMPONENT
		return new(pk.Option[Text, *Text]), nil
	case 7: // ITEM_STACK
		return new(ItemStack), nil
	case 8: // BOOLEAN
		return new(pk.Boolean), nil
	case 9: // ROTATIONS
		return new(Rotations), nil
	case 10: // BLOCK_POS
		return new(pk.Position), nil
	case 11: // OPTIONAL_BLOCK_POS
		return new(pk.Option[pk.Position, *pk.Position]), nil
	case 12: // DIRECTION
		return new(Direction), nil
	case 13: // OPTIONAL_LIVING_ENTITY_REFERENCE
		return new(pk.Option[pk.UUID, *pk.UUID]), nil
	case 14: // BLOCK_STATE
		return new(pk.VarInt), nil
	case 15: // OPTIONAL_BLOCK_STATE
		return new(OptionalVarInt), nil
	case 16: // PARTICLE
		return new(ParticleOptions), nil
	case 17: // PARTICLES
		return new(List[ParticleOptions, *ParticleOptions]), nil
	case 18: // VILLAGER_DATA
		return new(VillagerData), nil
	case 19: // OPTIONAL_UNSIGNED_INT
		return new(OptionalVarInt), nil
	case 20: // POSE
		return new(Pose), nil
	case 21: // CAT_VARIANT
		return new(pk.VarInt), nil
	case 22: // CAT_SOUND_VARIANT
		return new(pk.VarInt), nil
	case 23: // COW_VARIANT
		return new(pk.VarInt), nil
	case 24: // COW_SOUND_VARIANT
		return new(pk.VarInt), nil
	case 25: // WOLF_VARIANT
		return new(pk.VarInt), nil
	case 26: // WOLF_SOUND_VARIANT
		return new(pk.VarInt), nil
	case 27: // FROG_VARIANT
		return new(pk.VarInt), nil
	case 28: // PIG_VARIANT
		return new(pk.VarInt), nil
	case 29: // PIG_SOUND_VARIANT
		return new(pk.VarInt), nil
	case 30: // CHICKEN_VARIANT
		return new(pk.VarInt), nil
	case 31: // CHICKEN_SOUND_VARIANT
		return new(pk.VarInt), nil
	case 32: // ZOMBIE_NAUTILUS_VARIANT
		return new(pk.VarInt), nil
	case 33: // OPTIONAL_GLOBAL_POS
		return new(pk.Option[GlobalPos, *GlobalPos]), nil
	case 34: // PAINTING_VARIANT
		return new(Holder[PaintingVariant, *PaintingVariant]), nil
	case 35: // SNIFFER_STATE
		return new(SnifferState), nil
	case 36: // ARMADILLO_STATE
		return new(ArmadilloArmadilloState), nil
	case 37: // COPPER_GOLEM_STATE
		return new(CopperGolemState), nil
	case 38: // WEATHERING_COPPER_STATE
		return new(WeatheringCopperWeatherState), nil
	case 39: // VECTOR3
		return new(Vector3f), nil
	case 40: // QUATERNION
		return new(Quaternionf), nil
	case 41: // RESOLVABLE_PROFILE
		return new(ResolvableProfile), nil
	case 42: // HUMANOID_ARM
		return new(HumanoidArm), nil
	}
	return nil, fmt.Errorf("entity data serializer %d: %s", serializer, entityDataSerializerNote(serializer))
}

func entityDataSerializerNote(serializer int32) string {
	if int(serializer) < len(EntityDataSerializers) {
		return EntityDataSerializers[serializer] + " is not typed by the schema"
	}
	return "unknown"
}
