// Code generated by gen/gen_packets.go from 26.3/packet_schema.json; DO NOT EDIT.
package types

import (
	"fmt"
	"io"

	"github.com/mj41/go-mc26/level"
	pk "github.com/mj41/go-mc26/net/packet"
	"github.com/mj41/go-mc26/yggdrasil/user"
)

var _ = io.EOF

// Stat is Java Stat: a dispatch on the registry stat_type — the id, then the fields of
// that element's own codec; only the fields of the case in Type are on the wire.
type Stat struct {
	Type     pk.VarInt // id in stat_type
	Mined    pk.VarInt // minecraft:mined registry block
	Crafted  pk.VarInt // minecraft:crafted registry item
	Used     pk.VarInt // minecraft:used registry item
	Broken   pk.VarInt // minecraft:broken registry item
	PickedUp pk.VarInt // minecraft:picked_up registry item
	Dropped  pk.VarInt // minecraft:dropped registry item
	Killed   pk.VarInt // minecraft:killed registry entity_type
	KilledBy pk.VarInt // minecraft:killed_by registry entity_type
	Custom   pk.VarInt // minecraft:custom registry custom_stat
}

// fields returns the fields the case in Type carries, as one tuple to read or write.
func (v *Stat) fields() (pk.Tuple, error) {
	switch v.Type {
	case 0: // minecraft:mined
		return pk.Tuple{&v.Mined}, nil
	case 1: // minecraft:crafted
		return pk.Tuple{&v.Crafted}, nil
	case 2: // minecraft:used
		return pk.Tuple{&v.Used}, nil
	case 3: // minecraft:broken
		return pk.Tuple{&v.Broken}, nil
	case 4: // minecraft:picked_up
		return pk.Tuple{&v.PickedUp}, nil
	case 5: // minecraft:dropped
		return pk.Tuple{&v.Dropped}, nil
	case 6: // minecraft:killed
		return pk.Tuple{&v.Killed}, nil
	case 7: // minecraft:killed_by
		return pk.Tuple{&v.KilledBy}, nil
	case 8: // minecraft:custom
		return pk.Tuple{&v.Custom}, nil
	}
	return nil, fmt.Errorf("stat_type %d: unknown id", v.Type)
}

func (v *Stat) ReadFrom(r io.Reader) (int64, error) {
	n, err := v.Type.ReadFrom(r)
	if err != nil {
		return n, err
	}
	t, err := v.fields()
	if err != nil {
		return n, err
	}
	m, err := t.ReadFrom(r)
	return n + m, err
}

func (v Stat) WriteTo(w io.Writer) (int64, error) {
	n, err := v.Type.WriteTo(w)
	if err != nil {
		return n, err
	}
	t, err := v.fields()
	if err != nil {
		return n, err
	}
	m, err := t.WriteTo(w)
	return n + m, err
}

// BossEventPacketPayload is Java ClientboundBossEventPacketPayload: a dispatch on ClientboundBossEventPacket$OperationType — the constant, then the fields the reader it
// holds reads; only the fields of the case in Type are on the wire.
type BossEventPacketPayload struct {
	Type     BossEventOperationType  // which case is on the wire
	Name     Text                    // ADD, UPDATE_NAME
	Progress pk.Float                // ADD, UPDATE_PROGRESS
	Color    BossEventBossBarColor   // ADD, UPDATE_STYLE
	Overlay  BossEventBossBarOverlay // ADD, UPDATE_STYLE
	Flags    pk.UnsignedByte         // ADD
	Input    pk.UnsignedByte         // UPDATE_PROPERTIES
}

// fields returns the fields the case in Type carries, as one tuple to read or write.
func (v *BossEventPacketPayload) fields() (pk.Tuple, error) {
	switch v.Type {
	case 0: // ADD
		return pk.Tuple{&v.Name, &v.Progress, &v.Color, &v.Overlay, &v.Flags}, nil
	case 2: // UPDATE_PROGRESS
		return pk.Tuple{&v.Progress}, nil
	case 3: // UPDATE_NAME
		return pk.Tuple{&v.Name}, nil
	case 4: // UPDATE_STYLE
		return pk.Tuple{&v.Color, &v.Overlay}, nil
	case 5: // UPDATE_PROPERTIES
		return pk.Tuple{&v.Input}, nil
	case 1:
		return nil, nil // no data
	}
	return nil, fmt.Errorf("ClientboundBossEventPacket$OperationType %d: unknown id", v.Type)
}

func (v *BossEventPacketPayload) ReadFrom(r io.Reader) (int64, error) {
	n, err := v.Type.ReadFrom(r)
	if err != nil {
		return n, err
	}
	t, err := v.fields()
	if err != nil {
		return n, err
	}
	m, err := t.ReadFrom(r)
	return n + m, err
}

func (v BossEventPacketPayload) WriteTo(w io.Writer) (int64, error) {
	n, err := v.Type.WriteTo(w)
	if err != nil {
		return n, err
	}
	t, err := v.fields()
	if err != nil {
		return n, err
	}
	m, err := t.WriteTo(w)
	return n + m, err
}

// ArgumentTypeInfo is Java ArgumentTypeInfo: a dispatch on the registry command_argument_type — the id, then the fields of
// that element's own codec; only the fields of the case in Type are on the wire.
type ArgumentTypeInfo struct {
	Type             pk.VarInt                    // id in command_argument_type
	Float            FloatArgumentInfoTemplate    // brigadier:float
	Double           DoubleArgumentInfoTemplate   // brigadier:double
	Integer          IntegerArgumentInfoTemplate  // brigadier:integer
	Long             LongArgumentInfoTemplate     // brigadier:long
	String           StringArgumentTypeStringType // brigadier:string
	Entity           pk.Byte                      // minecraft:entity
	ScoreHolder      pk.Byte                      // minecraft:score_holder
	Time             pk.Int                       // minecraft:time
	ResourceOrTag    pk.Identifier                // minecraft:resource_or_tag
	ResourceOrTagKey pk.Identifier                // minecraft:resource_or_tag_key
	Resource         pk.Identifier                // minecraft:resource
	ResourceKey      pk.Identifier                // minecraft:resource_key
	ResourceSelector pk.Identifier                // minecraft:resource_selector
}

// fields returns the fields the case in Type carries, as one tuple to read or write.
func (v *ArgumentTypeInfo) fields() (pk.Tuple, error) {
	switch v.Type {
	case 1: // brigadier:float
		return pk.Tuple{&v.Float}, nil
	case 2: // brigadier:double
		return pk.Tuple{&v.Double}, nil
	case 3: // brigadier:integer
		return pk.Tuple{&v.Integer}, nil
	case 4: // brigadier:long
		return pk.Tuple{&v.Long}, nil
	case 5: // brigadier:string
		return pk.Tuple{&v.String}, nil
	case 6: // minecraft:entity
		return pk.Tuple{&v.Entity}, nil
	case 31: // minecraft:score_holder
		return pk.Tuple{&v.ScoreHolder}, nil
	case 43: // minecraft:time
		return pk.Tuple{&v.Time}, nil
	case 44: // minecraft:resource_or_tag
		return pk.Tuple{&v.ResourceOrTag}, nil
	case 45: // minecraft:resource_or_tag_key
		return pk.Tuple{&v.ResourceOrTagKey}, nil
	case 46: // minecraft:resource
		return pk.Tuple{&v.Resource}, nil
	case 47: // minecraft:resource_key
		return pk.Tuple{&v.ResourceKey}, nil
	case 48: // minecraft:resource_selector
		return pk.Tuple{&v.ResourceSelector}, nil
	case 0, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61:
		return nil, nil // no data
	}
	return nil, fmt.Errorf("command_argument_type %d: unknown id", v.Type)
}

func (v *ArgumentTypeInfo) ReadFrom(r io.Reader) (int64, error) {
	n, err := v.Type.ReadFrom(r)
	if err != nil {
		return n, err
	}
	t, err := v.fields()
	if err != nil {
		return n, err
	}
	m, err := t.ReadFrom(r)
	return n + m, err
}

func (v ArgumentTypeInfo) WriteTo(w io.Writer) (int64, error) {
	n, err := v.Type.WriteTo(w)
	if err != nil {
		return n, err
	}
	t, err := v.fields()
	if err != nil {
		return n, err
	}
	m, err := t.WriteTo(w)
	return n + m, err
}

// DebugSubscriptionUpdate is Java DebugSubscription$Update: a dispatch on the registry debug_subscription — the id, then the fields of
// that element's own codec; only the fields of the case in Type are on the wire.
type DebugSubscriptionUpdate struct {
	Type                     pk.VarInt                                                                                                // id in debug_subscription
	DedicatedServerTickTime  pk.Option[Empty, *Empty]                                                                                 // minecraft:dedicated_server_tick_time
	Bees                     pk.Option[DebugBeeInfo, *DebugBeeInfo]                                                                   // minecraft:bees
	Brains                   pk.Option[DebugBrainDump, *DebugBrainDump]                                                               // minecraft:brains
	Breezes                  pk.Option[DebugBreezeInfo, *DebugBreezeInfo]                                                             // minecraft:breezes
	GoalSelectors            pk.Option[DebugGoalInfo, *DebugGoalInfo]                                                                 // minecraft:goal_selectors
	EntityPaths              pk.Option[DebugPathInfo, *DebugPathInfo]                                                                 // minecraft:entity_paths
	EntityBlockIntersections pk.Option[DebugEntityBlockIntersection, *DebugEntityBlockIntersection]                                   // minecraft:entity_block_intersections
	BeeHives                 pk.Option[DebugHiveInfo, *DebugHiveInfo]                                                                 // minecraft:bee_hives
	Pois                     pk.Option[DebugPoiInfo, *DebugPoiInfo]                                                                   // minecraft:pois
	RedstoneWireOrientations pk.Option[pk.VarInt, *pk.VarInt]                                                                         // minecraft:redstone_wire_orientations
	VillageSections          pk.Option[Empty, *Empty]                                                                                 // minecraft:village_sections
	Raids                    pk.Option[List[pk.Position, *pk.Position], *List[pk.Position, *pk.Position]]                             // minecraft:raids
	Structures               pk.Option[List[DebugStructureInfo, *DebugStructureInfo], *List[DebugStructureInfo, *DebugStructureInfo]] // minecraft:structures
	GameEventListeners       pk.Option[DebugGameEventListenerInfo, *DebugGameEventListenerInfo]                                       // minecraft:game_event_listeners
	NeighborUpdates          pk.Option[pk.Position, *pk.Position]                                                                     // minecraft:neighbor_updates
	GameEvents               pk.Option[DebugGameEventInfo, *DebugGameEventInfo]                                                       // minecraft:game_events
}

// fields returns the fields the case in Type carries, as one tuple to read or write.
func (v *DebugSubscriptionUpdate) fields() (pk.Tuple, error) {
	switch v.Type {
	case 0: // minecraft:dedicated_server_tick_time
		return pk.Tuple{&v.DedicatedServerTickTime}, nil
	case 1: // minecraft:bees
		return pk.Tuple{&v.Bees}, nil
	case 2: // minecraft:brains
		return pk.Tuple{&v.Brains}, nil
	case 3: // minecraft:breezes
		return pk.Tuple{&v.Breezes}, nil
	case 4: // minecraft:goal_selectors
		return pk.Tuple{&v.GoalSelectors}, nil
	case 5: // minecraft:entity_paths
		return pk.Tuple{&v.EntityPaths}, nil
	case 6: // minecraft:entity_block_intersections
		return pk.Tuple{&v.EntityBlockIntersections}, nil
	case 7: // minecraft:bee_hives
		return pk.Tuple{&v.BeeHives}, nil
	case 8: // minecraft:pois
		return pk.Tuple{&v.Pois}, nil
	case 9: // minecraft:redstone_wire_orientations
		return pk.Tuple{&v.RedstoneWireOrientations}, nil
	case 10: // minecraft:village_sections
		return pk.Tuple{&v.VillageSections}, nil
	case 11: // minecraft:raids
		return pk.Tuple{&v.Raids}, nil
	case 12: // minecraft:structures
		return pk.Tuple{&v.Structures}, nil
	case 13: // minecraft:game_event_listeners
		return pk.Tuple{&v.GameEventListeners}, nil
	case 14: // minecraft:neighbor_updates
		return pk.Tuple{&v.NeighborUpdates}, nil
	case 15: // minecraft:game_events
		return pk.Tuple{&v.GameEvents}, nil
	}
	return nil, fmt.Errorf("debug_subscription %d: unknown id", v.Type)
}

func (v *DebugSubscriptionUpdate) ReadFrom(r io.Reader) (int64, error) {
	n, err := v.Type.ReadFrom(r)
	if err != nil {
		return n, err
	}
	t, err := v.fields()
	if err != nil {
		return n, err
	}
	m, err := t.ReadFrom(r)
	return n + m, err
}

func (v DebugSubscriptionUpdate) WriteTo(w io.Writer) (int64, error) {
	n, err := v.Type.WriteTo(w)
	if err != nil {
		return n, err
	}
	t, err := v.fields()
	if err != nil {
		return n, err
	}
	m, err := t.WriteTo(w)
	return n + m, err
}

// DebugSubscriptionEvent is Java DebugSubscription$Event: a dispatch on the registry debug_subscription — the id, then the fields of
// that element's own codec; only the fields of the case in Type are on the wire.
type DebugSubscriptionEvent struct {
	Type                     pk.VarInt                                             // id in debug_subscription
	HivePos                  pk.Option[pk.Position, *pk.Position]                  // minecraft:bees
	FlowerPos                pk.Option[pk.Position, *pk.Position]                  // minecraft:bees
	TravelTicks              pk.VarInt                                             // minecraft:bees
	BlacklistedHives         List[pk.Position, *pk.Position]                       // minecraft:bees
	Name                     pk.String                                             // minecraft:brains
	Profession               pk.String                                             // minecraft:brains
	XP                       pk.Int                                                // minecraft:brains
	Health                   pk.Float                                              // minecraft:brains
	MaxHealth                pk.Float                                              // minecraft:brains
	Inventory                pk.String                                             // minecraft:brains
	WantsGolem               pk.Boolean                                            // minecraft:brains
	AngerLevel               pk.Int                                                // minecraft:brains
	Activities               List[pk.String, *pk.String]                           // minecraft:brains
	Behaviors                List[pk.String, *pk.String]                           // minecraft:brains
	Memories                 List[pk.String, *pk.String]                           // minecraft:brains
	Gossips                  List[pk.String, *pk.String]                           // minecraft:brains
	Pois                     List[pk.Position, *pk.Position]                       // minecraft:brains
	PotentialPois            List[pk.Position, *pk.Position]                       // minecraft:brains
	AttackTarget             pk.Option[pk.VarInt, *pk.VarInt]                      // minecraft:breezes
	JumpTarget               pk.Option[pk.Position, *pk.Position]                  // minecraft:breezes
	Goals                    List[DebugGoalInfoDebugGoal, *DebugGoalInfoDebugGoal] // minecraft:goal_selectors
	Path                     Path                                                  // minecraft:entity_paths
	MaxNodeDistance          pk.Float                                              // minecraft:entity_paths
	EntityBlockIntersections DebugEntityBlockIntersection                          // minecraft:entity_block_intersections
	TypeBeeHives             pk.VarInt                                             // minecraft:bee_hives registry block
	OccupantCount            pk.VarInt                                             // minecraft:bee_hives
	HoneyLevel               pk.VarInt                                             // minecraft:bee_hives
	Sedated                  pk.Boolean                                            // minecraft:bee_hives
	Pos                      pk.Position                                           // minecraft:pois
	PoiType                  pk.VarInt                                             // minecraft:pois holder in point_of_interest_type
	FreeTicketCount          pk.VarInt                                             // minecraft:pois
	RedstoneWireOrientations pk.VarInt                                             // minecraft:redstone_wire_orientations registry Orientation
	Raids                    List[pk.Position, *pk.Position]                       // minecraft:raids
	Structures               List[DebugStructureInfo, *DebugStructureInfo]         // minecraft:structures
	ListenerRadius           pk.VarInt                                             // minecraft:game_event_listeners
	NeighborUpdates          pk.Position                                           // minecraft:neighbor_updates
	Event                    pk.VarInt                                             // minecraft:game_events holder in game_event
	PosGameEvents            Vec3                                                  // minecraft:game_events
}

// fields returns the fields the case in Type carries, as one tuple to read or write.
func (v *DebugSubscriptionEvent) fields() (pk.Tuple, error) {
	switch v.Type {
	case 1: // minecraft:bees
		return pk.Tuple{&v.HivePos, &v.FlowerPos, &v.TravelTicks, &v.BlacklistedHives}, nil
	case 2: // minecraft:brains
		return pk.Tuple{&v.Name, &v.Profession, &v.XP, &v.Health, &v.MaxHealth, &v.Inventory, &v.WantsGolem, &v.AngerLevel, &v.Activities, &v.Behaviors, &v.Memories, &v.Gossips, &v.Pois, &v.PotentialPois}, nil
	case 3: // minecraft:breezes
		return pk.Tuple{&v.AttackTarget, &v.JumpTarget}, nil
	case 4: // minecraft:goal_selectors
		return pk.Tuple{&v.Goals}, nil
	case 5: // minecraft:entity_paths
		return pk.Tuple{&v.Path, &v.MaxNodeDistance}, nil
	case 6: // minecraft:entity_block_intersections
		return pk.Tuple{&v.EntityBlockIntersections}, nil
	case 7: // minecraft:bee_hives
		return pk.Tuple{&v.TypeBeeHives, &v.OccupantCount, &v.HoneyLevel, &v.Sedated}, nil
	case 8: // minecraft:pois
		return pk.Tuple{&v.Pos, &v.PoiType, &v.FreeTicketCount}, nil
	case 9: // minecraft:redstone_wire_orientations
		return pk.Tuple{&v.RedstoneWireOrientations}, nil
	case 11: // minecraft:raids
		return pk.Tuple{&v.Raids}, nil
	case 12: // minecraft:structures
		return pk.Tuple{&v.Structures}, nil
	case 13: // minecraft:game_event_listeners
		return pk.Tuple{&v.ListenerRadius}, nil
	case 14: // minecraft:neighbor_updates
		return pk.Tuple{&v.NeighborUpdates}, nil
	case 15: // minecraft:game_events
		return pk.Tuple{&v.Event, &v.PosGameEvents}, nil
	case 0, 10:
		return nil, nil // no data
	}
	return nil, fmt.Errorf("debug_subscription %d: unknown id", v.Type)
}

func (v *DebugSubscriptionEvent) ReadFrom(r io.Reader) (int64, error) {
	n, err := v.Type.ReadFrom(r)
	if err != nil {
		return n, err
	}
	t, err := v.fields()
	if err != nil {
		return n, err
	}
	m, err := t.ReadFrom(r)
	return n + m, err
}

func (v DebugSubscriptionEvent) WriteTo(w io.Writer) (int64, error) {
	n, err := v.Type.WriteTo(w)
	if err != nil {
		return n, err
	}
	t, err := v.fields()
	if err != nil {
		return n, err
	}
	m, err := t.WriteTo(w)
	return n + m, err
}

// PositionPath is Java PositionPath: a dispatch on PositionPath$Type — the constant, then the fields the reader it
// holds reads; only the fields of the case in Type are on the wire.
type PositionPath struct {
	Type    PositionPathType                  // which case is on the wire
	X       pk.Double                         // LINEAR
	Y       pk.Double                         // LINEAR
	Z       pk.Double                         // LINEAR
	Stepped List[PositionStep, *PositionStep] // STEPPED
}

// fields returns the fields the case in Type carries, as one tuple to read or write.
func (v *PositionPath) fields() (pk.Tuple, error) {
	switch v.Type {
	case 0: // LINEAR
		return pk.Tuple{&v.X, &v.Y, &v.Z}, nil
	case 1: // STEPPED
		return pk.Tuple{&v.Stepped}, nil
	}
	return nil, fmt.Errorf("PositionPath$Type %d: unknown id", v.Type)
}

func (v *PositionPath) ReadFrom(r io.Reader) (int64, error) {
	n, err := v.Type.ReadFrom(r)
	if err != nil {
		return n, err
	}
	t, err := v.fields()
	if err != nil {
		return n, err
	}
	m, err := t.ReadFrom(r)
	return n + m, err
}

func (v PositionPath) WriteTo(w io.Writer) (int64, error) {
	n, err := v.Type.WriteTo(w)
	if err != nil {
		return n, err
	}
	t, err := v.fields()
	if err != nil {
		return n, err
	}
	m, err := t.WriteTo(w)
	return n + m, err
}

// ParticleOptions is Java ParticleOptions: a dispatch on the registry particle_type — the id, then the fields of
// that element's own codec; only the fields of the case in Type are on the wire.
type ParticleOptions struct {
	Type             pk.VarInt      // id in particle_type
	Block            pk.VarInt      // minecraft:block registry Block.BLOCK_STATE_REGISTRY
	BlockMarker      pk.VarInt      // minecraft:block_marker registry Block.BLOCK_STATE_REGISTRY
	WaterBlocks      pk.Int         // minecraft:geyser, minecraft:geyser_base, minecraft:geyser_poof, minecraft:geyser_plume
	BurstImpulseBase pk.Float       // minecraft:geyser_base, minecraft:geyser_poof
	DragonBreath     pk.Float       // minecraft:dragon_breath
	Color            pk.Int         // minecraft:dust, minecraft:effect, minecraft:instant_effect, minecraft:trail
	Scale            pk.Float       // minecraft:dust, minecraft:dust_color_transition
	FromColor        pk.Int         // minecraft:dust_color_transition
	ToColor          pk.Int         // minecraft:dust_color_transition
	Power            pk.Float       // minecraft:effect, minecraft:instant_effect
	EntityEffect     pk.Int         // minecraft:entity_effect
	FallingDust      pk.VarInt      // minecraft:falling_dust registry Block.BLOCK_STATE_REGISTRY
	TintedLeaves     pk.Int         // minecraft:tinted_leaves
	Roll             pk.Float       // minecraft:sculk_charge
	Flash            pk.Int         // minecraft:flash
	Item             pk.VarInt      // minecraft:item holder in item
	Count            pk.VarInt      // minecraft:item
	Components       ComponentPatch // minecraft:item
	Destination      PositionSource // minecraft:vibration
	ArrivalInTicks   pk.VarInt      // minecraft:vibration
	Target           Vec3           // minecraft:trail
	Duration         pk.VarInt      // minecraft:trail
	Delay            pk.VarInt      // minecraft:shriek
	DustPillar       pk.VarInt      // minecraft:dust_pillar registry Block.BLOCK_STATE_REGISTRY
	BlockCrumble     pk.VarInt      // minecraft:block_crumble registry Block.BLOCK_STATE_REGISTRY
}

// fields returns the fields the case in Type carries, as one tuple to read or write.
func (v *ParticleOptions) fields() (pk.Tuple, error) {
	switch v.Type {
	case 1: // minecraft:block
		return pk.Tuple{&v.Block}, nil
	case 2: // minecraft:block_marker
		return pk.Tuple{&v.BlockMarker}, nil
	case 7, 10: // minecraft:geyser, minecraft:geyser_plume
		return pk.Tuple{&v.WaterBlocks}, nil
	case 8, 9: // minecraft:geyser_base, minecraft:geyser_poof
		return pk.Tuple{&v.WaterBlocks, &v.BurstImpulseBase}, nil
	case 15: // minecraft:dragon_breath
		return pk.Tuple{&v.DragonBreath}, nil
	case 21: // minecraft:dust
		return pk.Tuple{&v.Color, &v.Scale}, nil
	case 22: // minecraft:dust_color_transition
		return pk.Tuple{&v.FromColor, &v.ToColor, &v.Scale}, nil
	case 23, 56: // minecraft:effect, minecraft:instant_effect
		return pk.Tuple{&v.Color, &v.Power}, nil
	case 28: // minecraft:entity_effect
		return pk.Tuple{&v.EntityEffect}, nil
	case 36: // minecraft:falling_dust
		return pk.Tuple{&v.FallingDust}, nil
	case 46: // minecraft:tinted_leaves
		return pk.Tuple{&v.TintedLeaves}, nil
	case 48: // minecraft:sculk_charge
		return pk.Tuple{&v.Roll}, nil
	case 52: // minecraft:flash
		return pk.Tuple{&v.Flash}, nil
	case 57: // minecraft:item
		return pk.Tuple{&v.Item, &v.Count, &v.Components}, nil
	case 58: // minecraft:vibration
		return pk.Tuple{&v.Destination, &v.ArrivalInTicks}, nil
	case 59: // minecraft:trail
		return pk.Tuple{&v.Target, &v.Color, &v.Duration}, nil
	case 115: // minecraft:shriek
		return pk.Tuple{&v.Delay}, nil
	case 121: // minecraft:dust_pillar
		return pk.Tuple{&v.DustPillar}, nil
	case 125: // minecraft:block_crumble
		return pk.Tuple{&v.BlockCrumble}, nil
	case 0, 3, 4, 5, 6, 11, 12, 13, 14, 16, 17, 18, 19, 20, 24, 25, 26, 27, 29, 30, 31, 32, 33, 34, 35, 37, 38, 39, 40, 41, 42, 43, 44, 45, 47, 49, 50, 51, 53, 54, 55, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 116, 117, 118, 119, 120, 122, 123, 124, 126, 127:
		return nil, nil // no data
	}
	return nil, fmt.Errorf("particle_type %d: unknown id", v.Type)
}

func (v *ParticleOptions) ReadFrom(r io.Reader) (int64, error) {
	n, err := v.Type.ReadFrom(r)
	if err != nil {
		return n, err
	}
	t, err := v.fields()
	if err != nil {
		return n, err
	}
	m, err := t.ReadFrom(r)
	return n + m, err
}

func (v ParticleOptions) WriteTo(w io.Writer) (int64, error) {
	n, err := v.Type.WriteTo(w)
	if err != nil {
		return n, err
	}
	t, err := v.fields()
	if err != nil {
		return n, err
	}
	m, err := t.WriteTo(w)
	return n + m, err
}

// PositionSource is Java PositionSource: a dispatch on the registry position_source_type — the id, then the fields of
// that element's own codec; only the fields of the case in Type are on the wire.
type PositionSource struct {
	Type    pk.VarInt   // id in position_source_type
	Pos     pk.Position // minecraft:block
	ID      pk.VarInt   // minecraft:entity
	YOffset pk.Float    // minecraft:entity
}

// fields returns the fields the case in Type carries, as one tuple to read or write.
func (v *PositionSource) fields() (pk.Tuple, error) {
	switch v.Type {
	case 0: // minecraft:block
		return pk.Tuple{&v.Pos}, nil
	case 1: // minecraft:entity
		return pk.Tuple{&v.ID, &v.YOffset}, nil
	}
	return nil, fmt.Errorf("position_source_type %d: unknown id", v.Type)
}

func (v *PositionSource) ReadFrom(r io.Reader) (int64, error) {
	n, err := v.Type.ReadFrom(r)
	if err != nil {
		return n, err
	}
	t, err := v.fields()
	if err != nil {
		return n, err
	}
	m, err := t.ReadFrom(r)
	return n + m, err
}

func (v PositionSource) WriteTo(w io.Writer) (int64, error) {
	n, err := v.Type.WriteTo(w)
	if err != nil {
		return n, err
	}
	t, err := v.fields()
	if err != nil {
		return n, err
	}
	m, err := t.WriteTo(w)
	return n + m, err
}

// RecipeDisplay is Java RecipeDisplay: a dispatch on the registry recipe_display — the id, then the fields of
// that element's own codec; only the fields of the case in Type are on the wire.
type RecipeDisplay struct {
	Type            pk.VarInt                       // id in recipe_display
	Ingredients     List[SlotDisplay, *SlotDisplay] // minecraft:crafting_shapeless, minecraft:crafting_shaped
	Result          SlotDisplay                     // minecraft:crafting_shapeless, minecraft:crafting_shaped, minecraft:furnace, minecraft:stonecutter, minecraft:smithing
	CraftingStation SlotDisplay                     // minecraft:crafting_shapeless, minecraft:crafting_shaped, minecraft:furnace, minecraft:stonecutter, minecraft:smithing
	Width           pk.VarInt                       // minecraft:crafting_shaped
	Height          pk.VarInt                       // minecraft:crafting_shaped
	Ingredient      SlotDisplay                     // minecraft:furnace
	Fuel            SlotDisplay                     // minecraft:furnace
	Duration        pk.VarInt                       // minecraft:furnace
	Experience      pk.Float                        // minecraft:furnace
	Input           SlotDisplay                     // minecraft:stonecutter
	Template        SlotDisplay                     // minecraft:smithing
	Base            SlotDisplay                     // minecraft:smithing
	Addition        SlotDisplay                     // minecraft:smithing
}

// fields returns the fields the case in Type carries, as one tuple to read or write.
func (v *RecipeDisplay) fields() (pk.Tuple, error) {
	switch v.Type {
	case 0: // minecraft:crafting_shapeless
		return pk.Tuple{&v.Ingredients, &v.Result, &v.CraftingStation}, nil
	case 1: // minecraft:crafting_shaped
		return pk.Tuple{&v.Width, &v.Height, &v.Ingredients, &v.Result, &v.CraftingStation}, nil
	case 2: // minecraft:furnace
		return pk.Tuple{&v.Ingredient, &v.Fuel, &v.Result, &v.CraftingStation, &v.Duration, &v.Experience}, nil
	case 3: // minecraft:stonecutter
		return pk.Tuple{&v.Input, &v.Result, &v.CraftingStation}, nil
	case 4: // minecraft:smithing
		return pk.Tuple{&v.Template, &v.Base, &v.Addition, &v.Result, &v.CraftingStation}, nil
	}
	return nil, fmt.Errorf("recipe_display %d: unknown id", v.Type)
}

func (v *RecipeDisplay) ReadFrom(r io.Reader) (int64, error) {
	n, err := v.Type.ReadFrom(r)
	if err != nil {
		return n, err
	}
	t, err := v.fields()
	if err != nil {
		return n, err
	}
	m, err := t.ReadFrom(r)
	return n + m, err
}

func (v RecipeDisplay) WriteTo(w io.Writer) (int64, error) {
	n, err := v.Type.WriteTo(w)
	if err != nil {
		return n, err
	}
	t, err := v.fields()
	if err != nil {
		return n, err
	}
	m, err := t.WriteTo(w)
	return n + m, err
}

// SlotDisplay is Java SlotDisplay: a dispatch on the registry slot_display — the id, then the fields of
// that element's own codec; only the fields of the case in Type are on the wire.
type SlotDisplay struct {
	Type      pk.VarInt                         // id in slot_display
	Display   Box[SlotDisplay, *SlotDisplay]    // minecraft:with_any_potion
	Source    Box[SlotDisplay, *SlotDisplay]    // minecraft:only_with_component
	Component pk.VarInt                         // minecraft:only_with_component registry data_component_type
	Item      pk.VarInt                         // minecraft:item holder in item
	Stack     ItemStackTemplate                 // minecraft:item_stack
	Tag       IDSet                             // minecraft:tag registry item
	Dye       Box[SlotDisplay, *SlotDisplay]    // minecraft:dyed
	Target    Box[SlotDisplay, *SlotDisplay]    // minecraft:dyed
	Base      Box[SlotDisplay, *SlotDisplay]    // minecraft:smithing_trim
	Material  Box[SlotDisplay, *SlotDisplay]    // minecraft:smithing_trim
	Pattern   Holder[TrimPattern, *TrimPattern] // minecraft:smithing_trim registry trim_pattern
	Input     Box[SlotDisplay, *SlotDisplay]    // minecraft:with_remainder
	Remainder Box[SlotDisplay, *SlotDisplay]    // minecraft:with_remainder
	Contents  List[SlotDisplay, *SlotDisplay]   // minecraft:composite
}

// fields returns the fields the case in Type carries, as one tuple to read or write.
func (v *SlotDisplay) fields() (pk.Tuple, error) {
	switch v.Type {
	case 2: // minecraft:with_any_potion
		return pk.Tuple{&v.Display}, nil
	case 3: // minecraft:only_with_component
		return pk.Tuple{&v.Source, &v.Component}, nil
	case 4: // minecraft:item
		return pk.Tuple{&v.Item}, nil
	case 5: // minecraft:item_stack
		return pk.Tuple{&v.Stack}, nil
	case 6: // minecraft:tag
		return pk.Tuple{&v.Tag}, nil
	case 7: // minecraft:dyed
		return pk.Tuple{&v.Dye, &v.Target}, nil
	case 8: // minecraft:smithing_trim
		return pk.Tuple{&v.Base, &v.Material, &v.Pattern}, nil
	case 9: // minecraft:with_remainder
		return pk.Tuple{&v.Input, &v.Remainder}, nil
	case 10: // minecraft:composite
		return pk.Tuple{&v.Contents}, nil
	case 0, 1:
		return nil, nil // no data
	}
	return nil, fmt.Errorf("slot_display %d: unknown id", v.Type)
}

func (v *SlotDisplay) ReadFrom(r io.Reader) (int64, error) {
	n, err := v.Type.ReadFrom(r)
	if err != nil {
		return n, err
	}
	t, err := v.fields()
	if err != nil {
		return n, err
	}
	m, err := t.ReadFrom(r)
	return n + m, err
}

func (v SlotDisplay) WriteTo(w io.Writer) (int64, error) {
	n, err := v.Type.WriteTo(w)
	if err != nil {
		return n, err
	}
	t, err := v.fields()
	if err != nil {
		return n, err
	}
	m, err := t.WriteTo(w)
	return n + m, err
}

// FilterMask is Java FilterMask: a dispatch on FilterMask$Type — the constant, then the fields the reader it
// holds reads; only the fields of the case in Type are on the wire.
type FilterMask struct {
	Type              FilterMaskType // which case is on the wire
	PartiallyFiltered ByteBitSet     // PARTIALLY_FILTERED
}

// fields returns the fields the case in Type carries, as one tuple to read or write.
func (v *FilterMask) fields() (pk.Tuple, error) {
	switch v.Type {
	case 2: // PARTIALLY_FILTERED
		return pk.Tuple{&v.PartiallyFiltered}, nil
	case 0, 1:
		return nil, nil // no data
	}
	return nil, fmt.Errorf("FilterMask$Type %d: unknown id", v.Type)
}

func (v *FilterMask) ReadFrom(r io.Reader) (int64, error) {
	n, err := v.Type.ReadFrom(r)
	if err != nil {
		return n, err
	}
	t, err := v.fields()
	if err != nil {
		return n, err
	}
	m, err := t.ReadFrom(r)
	return n + m, err
}

func (v FilterMask) WriteTo(w io.Writer) (int64, error) {
	n, err := v.Type.WriteTo(w)
	if err != nil {
		return n, err
	}
	t, err := v.fields()
	if err != nil {
		return n, err
	}
	m, err := t.WriteTo(w)
	return n + m, err
}

// NumberFormat is Java NumberFormat: a dispatch on the registry number_format_type — the id, then the fields of
// that element's own codec; only the fields of the case in Type are on the wire.
type NumberFormat struct {
	Type  pk.VarInt // id in number_format_type
	Style NBT       // minecraft:styled
	Value Text      // minecraft:fixed
}

// fields returns the fields the case in Type carries, as one tuple to read or write.
func (v *NumberFormat) fields() (pk.Tuple, error) {
	switch v.Type {
	case 1: // minecraft:styled
		return pk.Tuple{&v.Style}, nil
	case 2: // minecraft:fixed
		return pk.Tuple{&v.Value}, nil
	case 0:
		return nil, nil // no data
	}
	return nil, fmt.Errorf("number_format_type %d: unknown id", v.Type)
}

func (v *NumberFormat) ReadFrom(r io.Reader) (int64, error) {
	n, err := v.Type.ReadFrom(r)
	if err != nil {
		return n, err
	}
	t, err := v.fields()
	if err != nil {
		return n, err
	}
	m, err := t.ReadFrom(r)
	return n + m, err
}

func (v NumberFormat) WriteTo(w io.Writer) (int64, error) {
	n, err := v.Type.WriteTo(w)
	if err != nil {
		return n, err
	}
	t, err := v.fields()
	if err != nil {
		return n, err
	}
	m, err := t.WriteTo(w)
	return n + m, err
}

// TrackedWaypointPayload is Java TrackedWaypointPayload: a dispatch on TrackedWaypoint$Type — the constant, then the fields the reader it
// holds reads; only the fields of the case in Type are on the wire.
type TrackedWaypointPayload struct {
	Type     TrackedWaypointType // which case is on the wire
	Vector   Vec3i               // VEC3I
	ChunkPos ChunkPosRecord      // CHUNK
	Angle    pk.Float            // AZIMUTH
}

// fields returns the fields the case in Type carries, as one tuple to read or write.
func (v *TrackedWaypointPayload) fields() (pk.Tuple, error) {
	switch v.Type {
	case 1: // VEC3I
		return pk.Tuple{&v.Vector}, nil
	case 2: // CHUNK
		return pk.Tuple{&v.ChunkPos}, nil
	case 3: // AZIMUTH
		return pk.Tuple{&v.Angle}, nil
	case 0:
		return nil, nil // no data
	}
	return nil, fmt.Errorf("TrackedWaypoint$Type %d: unknown id", v.Type)
}

func (v *TrackedWaypointPayload) ReadFrom(r io.Reader) (int64, error) {
	n, err := v.Type.ReadFrom(r)
	if err != nil {
		return n, err
	}
	t, err := v.fields()
	if err != nil {
		return n, err
	}
	m, err := t.ReadFrom(r)
	return n + m, err
}

func (v TrackedWaypointPayload) WriteTo(w io.Writer) (int64, error) {
	n, err := v.Type.WriteTo(w)
	if err != nil {
		return n, err
	}
	t, err := v.fields()
	if err != nil {
		return n, err
	}
	m, err := t.WriteTo(w)
	return n + m, err
}

// ArgumentUtilsPacked is Java ArgumentUtils$Packed: one pk.Byte whose bits are separate values.
type ArgumentUtilsPacked struct {
	NumberHasMin bool   // bit 0
	NumberHasMax bool   // bit 1
	rest         uint32 // the bits no name accounts for, kept so the value writes back as it was read
}

func (v *ArgumentUtilsPacked) ReadFrom(r io.Reader) (int64, error) {
	var raw pk.Byte
	n, err := raw.ReadFrom(r)
	if err != nil {
		return n, err
	}
	u := uint32(raw) & 0xff
	v.NumberHasMin = (u>>0)&1 != 0
	v.NumberHasMax = (u>>1)&1 != 0
	v.rest = u & 0xfc
	return n, nil
}

func (v ArgumentUtilsPacked) WriteTo(w io.Writer) (int64, error) {
	var u uint32
	if v.NumberHasMin {
		u |= 1 << 0
	}
	if v.NumberHasMax {
		u |= 1 << 1
	}
	u |= v.rest
	return pk.Byte(u).WriteTo(w)
}

// MoveEntityPosPacked is Java ClientboundMoveEntityPacket$Pos$Packed: one pk.VarInt whose bits are separate values.
type MoveEntityPosPacked struct {
	OnGround  bool  // bit 0
	StepCount int32 // bits 1-31
}

func (v *MoveEntityPosPacked) ReadFrom(r io.Reader) (int64, error) {
	var raw pk.VarInt
	n, err := raw.ReadFrom(r)
	if err != nil {
		return n, err
	}
	u := uint32(raw) & 0xffffffff
	v.OnGround = (u>>0)&1 != 0
	v.StepCount = int32((u >> 1) & 0x7fffffff)
	return n, nil
}

func (v MoveEntityPosPacked) WriteTo(w io.Writer) (int64, error) {
	var u uint32
	if v.OnGround {
		u |= 1 << 0
	}
	u |= (uint32(v.StepCount) & 0x7fffffff) << 1
	return pk.VarInt(u).WriteTo(w)
}

// MoveEntityPosRotPacked is Java ClientboundMoveEntityPacket$PosRot$Packed: one pk.VarInt whose bits are separate values.
type MoveEntityPosRotPacked struct {
	OnGround  bool  // bit 0
	StepCount int32 // bits 1-31
}

func (v *MoveEntityPosRotPacked) ReadFrom(r io.Reader) (int64, error) {
	var raw pk.VarInt
	n, err := raw.ReadFrom(r)
	if err != nil {
		return n, err
	}
	u := uint32(raw) & 0xffffffff
	v.OnGround = (u>>0)&1 != 0
	v.StepCount = int32((u >> 1) & 0x7fffffff)
	return n, nil
}

func (v MoveEntityPosRotPacked) WriteTo(w io.Writer) (int64, error) {
	var u uint32
	if v.OnGround {
		u |= 1 << 0
	}
	u |= (uint32(v.StepCount) & 0x7fffffff) << 1
	return pk.VarInt(u).WriteTo(w)
}

// MovePlayerPacked is Java ServerboundMovePlayerPacket$Packed: one pk.UnsignedByte whose bits are separate values.
type MovePlayerPacked struct {
	OnGround            bool   // bit 0
	HorizontalCollision bool   // bit 1
	rest                uint32 // the bits no name accounts for, kept so the value writes back as it was read
}

func (v *MovePlayerPacked) ReadFrom(r io.Reader) (int64, error) {
	var raw pk.UnsignedByte
	n, err := raw.ReadFrom(r)
	if err != nil {
		return n, err
	}
	u := uint32(raw) & 0xff
	v.OnGround = (u>>0)&1 != 0
	v.HorizontalCollision = (u>>1)&1 != 0
	v.rest = u & 0xfc
	return n, nil
}

func (v MovePlayerPacked) WriteTo(w io.Writer) (int64, error) {
	var u uint32
	if v.OnGround {
		u |= 1 << 0
	}
	if v.HorizontalCollision {
		u |= 1 << 1
	}
	u |= v.rest
	return pk.UnsignedByte(u).WriteTo(w)
}

// SetEquipmentEntryList is a list of SetEquipmentEntry with no count: every entry but the last has the -128 bit of
// SlotID set to say another follows. ReadFrom clears it, WriteTo sets it, so SlotID holds
// only the value.
type SetEquipmentEntryList []SetEquipmentEntry

func (l *SetEquipmentEntryList) ReadFrom(r io.Reader) (int64, error) {
	*l = (*l)[:0]
	var n int64
	for {
		var e SetEquipmentEntry
		m, err := e.ReadFrom(r)
		n += m
		if err != nil {
			return n, err
		}
		last := e.SlotID&-128 == 0
		e.SlotID &^= -128
		*l = append(*l, e)
		if last {
			return n, nil
		}
	}
}

func (l SetEquipmentEntryList) WriteTo(w io.Writer) (int64, error) {
	if len(l) == 0 {
		return 0, fmt.Errorf("SetEquipmentEntryList: the wire form has at least one entry")
	}
	var n int64
	for i, e := range l {
		if i == len(l)-1 {
			e.SlotID &^= -128
		} else {
			e.SlotID |= -128
		}
		m, err := e.WriteTo(w)
		n += m
		if err != nil {
			return n, err
		}
	}
	return n, nil
}

// RegistrySynchronizationPackedRegistryEntry is Java RegistrySynchronization$PackedRegistryEntry.
type RegistrySynchronizationPackedRegistryEntry struct {
	ID   pk.Identifier
	Data pk.Option[NBT, *NBT]
}

func (v *RegistrySynchronizationPackedRegistryEntry) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.ID, &v.Data}.ReadFrom(r)
}

func (v RegistrySynchronizationPackedRegistryEntry) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.ID, v.Data}.WriteTo(w)
}

// KnownPack is Java KnownPack.
type KnownPack struct {
	Namespace pk.String
	ID        pk.String
	Version   pk.String
}

func (v *KnownPack) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Namespace, &v.ID, &v.Version}.ReadFrom(r)
}

func (v KnownPack) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Namespace, v.ID, v.Version}.WriteTo(w)
}

// ServerLinksUntrustedEntry is Java ServerLinks$UntrustedEntry.
type ServerLinksUntrustedEntry struct {
	Type Either[ServerLinksKnownLinkType, *ServerLinksKnownLinkType, Text, *Text]
	Link pk.String
}

func (v *ServerLinksUntrustedEntry) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Type, &v.Link}.ReadFrom(r)
}

func (v ServerLinksUntrustedEntry) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Type, v.Link}.WriteTo(w)
}

// TagNetworkSerializationNetworkPayload is Java TagNetworkSerialization$NetworkPayload.
type TagNetworkSerializationNetworkPayload struct {
	Tags Map[pk.Identifier, *pk.Identifier, List[pk.VarInt, *pk.VarInt], *List[pk.VarInt, *pk.VarInt]]
}

func (v *TagNetworkSerializationNetworkPayload) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Tags}.ReadFrom(r)
}

func (v TagNetworkSerializationNetworkPayload) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Tags}.WriteTo(w)
}

// ClientInformation is Java ClientInformation.
type ClientInformation struct {
	Language             pk.String
	ViewDistance         pk.Byte
	ChatVisibility       ChatVisiblity
	ChatColors           pk.Boolean
	ModelCustomisation   pk.UnsignedByte
	MainHand             HumanoidArm
	TextFilteringEnabled pk.Boolean
	AllowsListing        pk.Boolean
	ParticleStatus       ParticleStatus
}

func (v *ClientInformation) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Language, &v.ViewDistance, &v.ChatVisibility, &v.ChatColors, &v.ModelCustomisation, &v.MainHand, &v.TextFilteringEnabled, &v.AllowsListing, &v.ParticleStatus}.ReadFrom(r)
}

func (v ClientInformation) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Language, v.ViewDistance, v.ChatVisibility, v.ChatColors, v.ModelCustomisation, v.MainHand, v.TextFilteringEnabled, v.AllowsListing, v.ParticleStatus}.WriteTo(w)
}

// ChunksBiomesChunkBiomeData is Java ClientboundChunksBiomesPacket$ChunkBiomeData.
type ChunksBiomesChunkBiomeData struct {
	Pos    ChunkPos
	Buffer pk.ByteArray
}

func (v *ChunksBiomesChunkBiomeData) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Pos, &v.Buffer}.ReadFrom(r)
}

func (v ChunksBiomesChunkBiomeData) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Pos, v.Buffer}.WriteTo(w)
}

// CommandSuggestionsEntry is Java ClientboundCommandSuggestionsPacket$Entry.
type CommandSuggestionsEntry struct {
	Text    pk.String
	Tooltip pk.Option[Text, *Text]
}

func (v *CommandSuggestionsEntry) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Text, &v.Tooltip}.ReadFrom(r)
}

func (v CommandSuggestionsEntry) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Text, v.Tooltip}.WriteTo(w)
}

// FloatArgumentInfoTemplate is Java FloatArgumentInfo$Template.
type FloatArgumentInfoTemplate struct {
	Flags ArgumentUtilsPacked
	Min   pk.Float
	Max   pk.Float
}

func (v *FloatArgumentInfoTemplate) ReadFrom(r io.Reader) (n int64, err error) {
	var m int64
	m, err = pk.Tuple{&v.Flags}.ReadFrom(r)
	n += m
	if err != nil {
		return n, err
	}
	if v.Flags.NumberHasMin {
		m, err = pk.Tuple{&v.Min}.ReadFrom(r)
		n += m
		if err != nil {
			return n, err
		}
	}
	if v.Flags.NumberHasMax {
		m, err = pk.Tuple{&v.Max}.ReadFrom(r)
		n += m
		if err != nil {
			return n, err
		}
	}
	return n, nil
}

func (v FloatArgumentInfoTemplate) WriteTo(w io.Writer) (n int64, err error) {
	var m int64
	m, err = pk.Tuple{v.Flags}.WriteTo(w)
	n += m
	if err != nil {
		return n, err
	}
	if v.Flags.NumberHasMin {
		m, err = pk.Tuple{v.Min}.WriteTo(w)
		n += m
		if err != nil {
			return n, err
		}
	}
	if v.Flags.NumberHasMax {
		m, err = pk.Tuple{v.Max}.WriteTo(w)
		n += m
		if err != nil {
			return n, err
		}
	}
	return n, nil
}

// DoubleArgumentInfoTemplate is Java DoubleArgumentInfo$Template.
type DoubleArgumentInfoTemplate struct {
	Flags ArgumentUtilsPacked
	Min   pk.Double
	Max   pk.Double
}

func (v *DoubleArgumentInfoTemplate) ReadFrom(r io.Reader) (n int64, err error) {
	var m int64
	m, err = pk.Tuple{&v.Flags}.ReadFrom(r)
	n += m
	if err != nil {
		return n, err
	}
	if v.Flags.NumberHasMin {
		m, err = pk.Tuple{&v.Min}.ReadFrom(r)
		n += m
		if err != nil {
			return n, err
		}
	}
	if v.Flags.NumberHasMax {
		m, err = pk.Tuple{&v.Max}.ReadFrom(r)
		n += m
		if err != nil {
			return n, err
		}
	}
	return n, nil
}

func (v DoubleArgumentInfoTemplate) WriteTo(w io.Writer) (n int64, err error) {
	var m int64
	m, err = pk.Tuple{v.Flags}.WriteTo(w)
	n += m
	if err != nil {
		return n, err
	}
	if v.Flags.NumberHasMin {
		m, err = pk.Tuple{v.Min}.WriteTo(w)
		n += m
		if err != nil {
			return n, err
		}
	}
	if v.Flags.NumberHasMax {
		m, err = pk.Tuple{v.Max}.WriteTo(w)
		n += m
		if err != nil {
			return n, err
		}
	}
	return n, nil
}

// IntegerArgumentInfoTemplate is Java IntegerArgumentInfo$Template.
type IntegerArgumentInfoTemplate struct {
	Flags ArgumentUtilsPacked
	Min   pk.Int
	Max   pk.Int
}

func (v *IntegerArgumentInfoTemplate) ReadFrom(r io.Reader) (n int64, err error) {
	var m int64
	m, err = pk.Tuple{&v.Flags}.ReadFrom(r)
	n += m
	if err != nil {
		return n, err
	}
	if v.Flags.NumberHasMin {
		m, err = pk.Tuple{&v.Min}.ReadFrom(r)
		n += m
		if err != nil {
			return n, err
		}
	}
	if v.Flags.NumberHasMax {
		m, err = pk.Tuple{&v.Max}.ReadFrom(r)
		n += m
		if err != nil {
			return n, err
		}
	}
	return n, nil
}

func (v IntegerArgumentInfoTemplate) WriteTo(w io.Writer) (n int64, err error) {
	var m int64
	m, err = pk.Tuple{v.Flags}.WriteTo(w)
	n += m
	if err != nil {
		return n, err
	}
	if v.Flags.NumberHasMin {
		m, err = pk.Tuple{v.Min}.WriteTo(w)
		n += m
		if err != nil {
			return n, err
		}
	}
	if v.Flags.NumberHasMax {
		m, err = pk.Tuple{v.Max}.WriteTo(w)
		n += m
		if err != nil {
			return n, err
		}
	}
	return n, nil
}

// LongArgumentInfoTemplate is Java LongArgumentInfo$Template.
type LongArgumentInfoTemplate struct {
	Flags ArgumentUtilsPacked
	Min   pk.Long
	Max   pk.Long
}

func (v *LongArgumentInfoTemplate) ReadFrom(r io.Reader) (n int64, err error) {
	var m int64
	m, err = pk.Tuple{&v.Flags}.ReadFrom(r)
	n += m
	if err != nil {
		return n, err
	}
	if v.Flags.NumberHasMin {
		m, err = pk.Tuple{&v.Min}.ReadFrom(r)
		n += m
		if err != nil {
			return n, err
		}
	}
	if v.Flags.NumberHasMax {
		m, err = pk.Tuple{&v.Max}.ReadFrom(r)
		n += m
		if err != nil {
			return n, err
		}
	}
	return n, nil
}

func (v LongArgumentInfoTemplate) WriteTo(w io.Writer) (n int64, err error) {
	var m int64
	m, err = pk.Tuple{v.Flags}.WriteTo(w)
	n += m
	if err != nil {
		return n, err
	}
	if v.Flags.NumberHasMin {
		m, err = pk.Tuple{v.Min}.WriteTo(w)
		n += m
		if err != nil {
			return n, err
		}
	}
	if v.Flags.NumberHasMax {
		m, err = pk.Tuple{v.Max}.WriteTo(w)
		n += m
		if err != nil {
			return n, err
		}
	}
	return n, nil
}

// CommandsLiteralNodeStub is Java ClientboundCommandsPacket$LiteralNodeStub.
type CommandsLiteralNodeStub struct {
	ID pk.String
}

func (v *CommandsLiteralNodeStub) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.ID}.ReadFrom(r)
}

func (v CommandsLiteralNodeStub) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.ID}.WriteTo(w)
}

// CommandsEntry is Java ClientboundCommandsPacket$Entry.
type CommandsEntry struct {
	Flags                                    pk.Byte
	Children                                 List[pk.VarInt, *pk.VarInt]
	Redirect                                 pk.VarInt
	ID                                       pk.String
	ArgumentType                             ArgumentTypeInfo
	SuggestionID                             pk.Identifier
	ClientboundCommandsPacketLiteralNodeStub CommandsLiteralNodeStub
}

func (v *CommandsEntry) ReadFrom(r io.Reader) (n int64, err error) {
	var m int64
	m, err = pk.Tuple{&v.Flags, &v.Children}.ReadFrom(r)
	n += m
	if err != nil {
		return n, err
	}
	if v.Flags&8 != 0 {
		m, err = pk.Tuple{&v.Redirect}.ReadFrom(r)
		n += m
		if err != nil {
			return n, err
		}
	}
	if v.Flags&3 == 2 {
		m, err = pk.Tuple{&v.ID, &v.ArgumentType}.ReadFrom(r)
		n += m
		if err != nil {
			return n, err
		}
	}
	if v.Flags&3 == 2 && v.Flags&16 != 0 {
		m, err = pk.Tuple{&v.SuggestionID}.ReadFrom(r)
		n += m
		if err != nil {
			return n, err
		}
	}
	if v.Flags&3 == 1 {
		m, err = pk.Tuple{&v.ClientboundCommandsPacketLiteralNodeStub}.ReadFrom(r)
		n += m
		if err != nil {
			return n, err
		}
	}
	return n, nil
}

func (v CommandsEntry) WriteTo(w io.Writer) (n int64, err error) {
	var m int64
	m, err = pk.Tuple{v.Flags, v.Children}.WriteTo(w)
	n += m
	if err != nil {
		return n, err
	}
	if v.Flags&8 != 0 {
		m, err = pk.Tuple{v.Redirect}.WriteTo(w)
		n += m
		if err != nil {
			return n, err
		}
	}
	if v.Flags&3 == 2 {
		m, err = pk.Tuple{v.ID, v.ArgumentType}.WriteTo(w)
		n += m
		if err != nil {
			return n, err
		}
	}
	if v.Flags&3 == 2 && v.Flags&16 != 0 {
		m, err = pk.Tuple{v.SuggestionID}.WriteTo(w)
		n += m
		if err != nil {
			return n, err
		}
	}
	if v.Flags&3 == 1 {
		m, err = pk.Tuple{v.ClientboundCommandsPacketLiteralNodeStub}.WriteTo(w)
		n += m
		if err != nil {
			return n, err
		}
	}
	return n, nil
}

// DebugBeeInfo is Java DebugBeeInfo.
type DebugBeeInfo struct {
	HivePos          pk.Option[pk.Position, *pk.Position]
	FlowerPos        pk.Option[pk.Position, *pk.Position]
	TravelTicks      pk.VarInt
	BlacklistedHives List[pk.Position, *pk.Position]
}

func (v *DebugBeeInfo) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.HivePos, &v.FlowerPos, &v.TravelTicks, &v.BlacklistedHives}.ReadFrom(r)
}

func (v DebugBeeInfo) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.HivePos, v.FlowerPos, v.TravelTicks, v.BlacklistedHives}.WriteTo(w)
}

// DebugBrainDump is Java DebugBrainDump.
type DebugBrainDump struct {
	Name          pk.String
	Profession    pk.String
	XP            pk.Int
	Health        pk.Float
	MaxHealth     pk.Float
	Inventory     pk.String
	WantsGolem    pk.Boolean
	AngerLevel    pk.Int
	Activities    List[pk.String, *pk.String]
	Behaviors     List[pk.String, *pk.String]
	Memories      List[pk.String, *pk.String]
	Gossips       List[pk.String, *pk.String]
	Pois          List[pk.Position, *pk.Position]
	PotentialPois List[pk.Position, *pk.Position]
}

func (v *DebugBrainDump) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Name, &v.Profession, &v.XP, &v.Health, &v.MaxHealth, &v.Inventory, &v.WantsGolem, &v.AngerLevel, &v.Activities, &v.Behaviors, &v.Memories, &v.Gossips, &v.Pois, &v.PotentialPois}.ReadFrom(r)
}

func (v DebugBrainDump) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Name, v.Profession, v.XP, v.Health, v.MaxHealth, v.Inventory, v.WantsGolem, v.AngerLevel, v.Activities, v.Behaviors, v.Memories, v.Gossips, v.Pois, v.PotentialPois}.WriteTo(w)
}

// DebugBreezeInfo is Java DebugBreezeInfo.
type DebugBreezeInfo struct {
	AttackTarget pk.Option[pk.VarInt, *pk.VarInt]
	JumpTarget   pk.Option[pk.Position, *pk.Position]
}

func (v *DebugBreezeInfo) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.AttackTarget, &v.JumpTarget}.ReadFrom(r)
}

func (v DebugBreezeInfo) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.AttackTarget, v.JumpTarget}.WriteTo(w)
}

// DebugGoalInfoDebugGoal is Java DebugGoalInfo$DebugGoal.
type DebugGoalInfoDebugGoal struct {
	Priority  pk.VarInt
	IsRunning pk.Boolean
	Name      pk.String
}

func (v *DebugGoalInfoDebugGoal) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Priority, &v.IsRunning, &v.Name}.ReadFrom(r)
}

func (v DebugGoalInfoDebugGoal) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Priority, v.IsRunning, v.Name}.WriteTo(w)
}

// DebugGoalInfo is Java DebugGoalInfo.
type DebugGoalInfo struct {
	Goals List[DebugGoalInfoDebugGoal, *DebugGoalInfoDebugGoal]
}

func (v *DebugGoalInfo) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Goals}.ReadFrom(r)
}

func (v DebugGoalInfo) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Goals}.WriteTo(w)
}

// Node is Java Node.
type Node struct {
	X              pk.Int
	Y              pk.Int
	Z              pk.Int
	WalkedDistance pk.Float
	CostMalus      pk.Float
	Closed         pk.Boolean
	Type           PathType
	F              pk.Float
}

func (v *Node) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.X, &v.Y, &v.Z, &v.WalkedDistance, &v.CostMalus, &v.Closed, &v.Type, &v.F}.ReadFrom(r)
}

func (v Node) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.X, v.Y, v.Z, v.WalkedDistance, v.CostMalus, v.Closed, v.Type, v.F}.WriteTo(w)
}

// PathDebugData is Java Path$DebugData.
type PathDebugData struct {
	OpenSet     List[Node, *Node]
	ClosedSet   List[Node, *Node]
	TargetNodes List[Node, *Node]
}

func (v *PathDebugData) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.OpenSet, &v.ClosedSet, &v.TargetNodes}.ReadFrom(r)
}

func (v PathDebugData) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.OpenSet, v.ClosedSet, v.TargetNodes}.WriteTo(w)
}

// Path is Java Path.
type Path struct {
	Reached       pk.Boolean
	NextNodeIndex pk.Int
	Target        pk.Position
	Nodes         List[Node, *Node]
	DebugData     PathDebugData
}

func (v *Path) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Reached, &v.NextNodeIndex, &v.Target, &v.Nodes, &v.DebugData}.ReadFrom(r)
}

func (v Path) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Reached, v.NextNodeIndex, v.Target, v.Nodes, v.DebugData}.WriteTo(w)
}

// DebugPathInfo is Java DebugPathInfo.
type DebugPathInfo struct {
	Path            Path
	MaxNodeDistance pk.Float
}

func (v *DebugPathInfo) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Path, &v.MaxNodeDistance}.ReadFrom(r)
}

func (v DebugPathInfo) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Path, v.MaxNodeDistance}.WriteTo(w)
}

// DebugHiveInfo is Java DebugHiveInfo.
type DebugHiveInfo struct {
	Type          pk.VarInt // registry block
	OccupantCount pk.VarInt
	HoneyLevel    pk.VarInt
	Sedated       pk.Boolean
}

func (v *DebugHiveInfo) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Type, &v.OccupantCount, &v.HoneyLevel, &v.Sedated}.ReadFrom(r)
}

func (v DebugHiveInfo) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Type, v.OccupantCount, v.HoneyLevel, v.Sedated}.WriteTo(w)
}

// DebugPoiInfo is Java DebugPoiInfo.
type DebugPoiInfo struct {
	Pos             pk.Position
	PoiType         pk.VarInt // holder in point_of_interest_type
	FreeTicketCount pk.VarInt
}

func (v *DebugPoiInfo) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Pos, &v.PoiType, &v.FreeTicketCount}.ReadFrom(r)
}

func (v DebugPoiInfo) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Pos, v.PoiType, v.FreeTicketCount}.WriteTo(w)
}

// BoundingBox is Java BoundingBox.
type BoundingBox struct {
	MinX pk.Position
	MaxX pk.Position
}

func (v *BoundingBox) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.MinX, &v.MaxX}.ReadFrom(r)
}

func (v BoundingBox) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.MinX, v.MaxX}.WriteTo(w)
}

// DebugStructureInfoPiece is Java DebugStructureInfo$Piece.
type DebugStructureInfoPiece struct {
	BoundingBox BoundingBox
	IsStart     pk.Boolean
}

func (v *DebugStructureInfoPiece) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.BoundingBox, &v.IsStart}.ReadFrom(r)
}

func (v DebugStructureInfoPiece) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.BoundingBox, v.IsStart}.WriteTo(w)
}

// DebugStructureInfo is Java DebugStructureInfo.
type DebugStructureInfo struct {
	BoundingBox BoundingBox
	Pieces      List[DebugStructureInfoPiece, *DebugStructureInfoPiece]
}

func (v *DebugStructureInfo) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.BoundingBox, &v.Pieces}.ReadFrom(r)
}

func (v DebugStructureInfo) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.BoundingBox, v.Pieces}.WriteTo(w)
}

// DebugGameEventListenerInfo is Java DebugGameEventListenerInfo.
type DebugGameEventListenerInfo struct {
	ListenerRadius pk.VarInt
}

func (v *DebugGameEventListenerInfo) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.ListenerRadius}.ReadFrom(r)
}

func (v DebugGameEventListenerInfo) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.ListenerRadius}.WriteTo(w)
}

// DebugGameEventInfo is Java DebugGameEventInfo.
type DebugGameEventInfo struct {
	Event pk.VarInt // holder in game_event
	Pos   Vec3
}

func (v *DebugGameEventInfo) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Event, &v.Pos}.ReadFrom(r)
}

func (v DebugGameEventInfo) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Event, v.Pos}.WriteTo(w)
}

// MessageSignaturePacked is Java MessageSignature$Packed.
type MessageSignaturePacked struct {
	ID            pk.VarInt
	FullSignature MessageSignature
}

func (v *MessageSignaturePacked) ReadFrom(r io.Reader) (n int64, err error) {
	var m int64
	m, err = pk.Tuple{&v.ID}.ReadFrom(r)
	n += m
	if err != nil {
		return n, err
	}
	if v.ID == 0 {
		m, err = pk.Tuple{&v.FullSignature}.ReadFrom(r)
		n += m
		if err != nil {
			return n, err
		}
	}
	return n, nil
}

func (v MessageSignaturePacked) WriteTo(w io.Writer) (n int64, err error) {
	var m int64
	m, err = pk.Tuple{v.ID}.WriteTo(w)
	n += m
	if err != nil {
		return n, err
	}
	if v.ID == 0 {
		m, err = pk.Tuple{v.FullSignature}.WriteTo(w)
		n += m
		if err != nil {
			return n, err
		}
	}
	return n, nil
}

// PositionStep is Java PositionStep.
type PositionStep struct {
	Position   Vec3
	TickOffset pk.VarInt
}

func (v *PositionStep) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Position, &v.TickOffset}.ReadFrom(r)
}

func (v PositionStep) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Position, v.TickOffset}.WriteTo(w)
}

// SoundEvent is Java SoundEvent.
type SoundEvent struct {
	Location   pk.Identifier
	FixedRange pk.Option[pk.Float, *pk.Float]
}

func (v *SoundEvent) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Location, &v.FixedRange}.ReadFrom(r)
}

func (v SoundEvent) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Location, v.FixedRange}.WriteTo(w)
}

// ExplosionParticleInfo is Java ExplosionParticleInfo.
type ExplosionParticleInfo struct {
	Particle ParticleOptions
	Scaling  pk.Float
	Speed    pk.Float
}

func (v *ExplosionParticleInfo) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Particle, &v.Scaling, &v.Speed}.ReadFrom(r)
}

func (v ExplosionParticleInfo) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Particle, v.Scaling, v.Speed}.WriteTo(w)
}

// Weighted is Java Weighted.
type Weighted struct {
	Value  ExplosionParticleInfo
	Weight pk.VarInt
}

func (v *Weighted) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Value, &v.Weight}.ReadFrom(r)
}

func (v Weighted) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Value, v.Weight}.WriteTo(w)
}

// LevelChunkPacketData is Java ClientboundLevelChunkPacketData.
type LevelChunkPacketData struct {
	Heightmaps        Map[HeightmapTypes, *HeightmapTypes, List[pk.Long, *pk.Long], *List[pk.Long, *pk.Long]]
	Buffer            LenPrefixed[Rest[level.LevelChunkSection, *level.LevelChunkSection], *Rest[level.LevelChunkSection, *level.LevelChunkSection]]
	BlockEntitiesData List[LevelChunkPacketDataBlockEntityInfo, *LevelChunkPacketDataBlockEntityInfo]
}

func (v *LevelChunkPacketData) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Heightmaps, &v.Buffer, &v.BlockEntitiesData}.ReadFrom(r)
}

func (v LevelChunkPacketData) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Heightmaps, v.Buffer, v.BlockEntitiesData}.WriteTo(w)
}

// LightUpdatePacketData is Java ClientboundLightUpdatePacketData.
type LightUpdatePacketData struct {
	SkyYMask        ByteBitSet
	BlockYMask      ByteBitSet
	EmptySkyYMask   ByteBitSet
	EmptyBlockYMask ByteBitSet
	SkyUpdates      List[pk.ByteArray, *pk.ByteArray]
	BlockUpdates    List[pk.ByteArray, *pk.ByteArray]
}

func (v *LightUpdatePacketData) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.SkyYMask, &v.BlockYMask, &v.EmptySkyYMask, &v.EmptyBlockYMask, &v.SkyUpdates, &v.BlockUpdates}.ReadFrom(r)
}

func (v LightUpdatePacketData) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.SkyYMask, v.BlockYMask, v.EmptySkyYMask, v.EmptyBlockYMask, v.SkyUpdates, v.BlockUpdates}.WriteTo(w)
}

// CommonPlayerSpawnInfo is Java CommonPlayerSpawnInfo.
type CommonPlayerSpawnInfo struct {
	DimensionType     pk.VarInt     // holder in dimension_type
	Dimension         pk.Identifier // resource key in dimension
	Seed              pk.Long
	GameType          GameType
	PreviousGameType  OptionalVarInt
	IsDebug           pk.Boolean
	IsFlat            pk.Boolean
	LastDeathLocation pk.Option[GlobalPos, *GlobalPos]
	PortalCooldown    pk.VarInt
	SeaLevel          pk.VarInt
}

func (v *CommonPlayerSpawnInfo) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.DimensionType, &v.Dimension, &v.Seed, &v.GameType, &v.PreviousGameType, &v.IsDebug, &v.IsFlat, &v.LastDeathLocation, &v.PortalCooldown, &v.SeaLevel}.ReadFrom(r)
}

func (v CommonPlayerSpawnInfo) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.DimensionType, v.Dimension, v.Seed, v.GameType, v.PreviousGameType, v.IsDebug, v.IsFlat, v.LastDeathLocation, v.PortalCooldown, v.SeaLevel}.WriteTo(w)
}

// MapDecoration is Java MapDecoration.
type MapDecoration struct {
	Type pk.VarInt // holder in map_decoration_type
	X    pk.Byte
	Y    pk.Byte
	Rot  pk.Byte
	Name pk.Option[Text, *Text]
}

func (v *MapDecoration) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Type, &v.X, &v.Y, &v.Rot, &v.Name}.ReadFrom(r)
}

func (v MapDecoration) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Type, v.X, v.Y, v.Rot, v.Name}.WriteTo(w)
}

// MapItemSavedDataMapPatch is Java MapItemSavedData$MapPatch.
type MapItemSavedDataMapPatch struct {
	Width     pk.UnsignedByte
	Height    pk.UnsignedByte
	StartX    pk.UnsignedByte
	StartY    pk.UnsignedByte
	MapColors pk.ByteArray
}

func (v *MapItemSavedDataMapPatch) ReadFrom(r io.Reader) (n int64, err error) {
	var m int64
	m, err = pk.Tuple{&v.Width}.ReadFrom(r)
	n += m
	if err != nil {
		return n, err
	}
	if v.Width > 0 {
		m, err = pk.Tuple{&v.Height, &v.StartX, &v.StartY, &v.MapColors}.ReadFrom(r)
		n += m
		if err != nil {
			return n, err
		}
	}
	return n, nil
}

func (v MapItemSavedDataMapPatch) WriteTo(w io.Writer) (n int64, err error) {
	var m int64
	m, err = pk.Tuple{v.Width}.WriteTo(w)
	n += m
	if err != nil {
		return n, err
	}
	if v.Width > 0 {
		m, err = pk.Tuple{v.Height, v.StartX, v.StartY, v.MapColors}.WriteTo(w)
		n += m
		if err != nil {
			return n, err
		}
	}
	return n, nil
}

// ItemCost is Java ItemCost.
type ItemCost struct {
	Item       pk.VarInt // holder in item
	Count      pk.VarInt
	Components List[AddedComponent, *AddedComponent]
}

func (v *ItemCost) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Item, &v.Count, &v.Components}.ReadFrom(r)
}

func (v ItemCost) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Item, v.Count, v.Components}.WriteTo(w)
}

// MerchantOffer is Java MerchantOffer.
type MerchantOffer struct {
	Buy              ItemCost
	Sell             ItemStack
	BuyB             pk.Option[ItemCost, *ItemCost]
	IsExhausted      pk.Boolean
	Uses             pk.Int
	MaxUses          pk.Int
	XP               pk.Int
	SpecialPriceDiff pk.Int
	PriceMultiplier  pk.Float
	Demand           pk.Int
}

func (v *MerchantOffer) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Buy, &v.Sell, &v.BuyB, &v.IsExhausted, &v.Uses, &v.MaxUses, &v.XP, &v.SpecialPriceDiff, &v.PriceMultiplier, &v.Demand}.ReadFrom(r)
}

func (v MerchantOffer) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Buy, v.Sell, v.BuyB, v.IsExhausted, v.Uses, v.MaxUses, v.XP, v.SpecialPriceDiff, v.PriceMultiplier, v.Demand}.WriteTo(w)
}

// VecDeltaSteppedDeltaStep is Java VecDelta$Stepped$DeltaStep.
type VecDeltaSteppedDeltaStep struct {
	Ticks pk.VarInt
	Xa    pk.Short
	Ya    pk.Short
	Za    pk.Short
}

func (v *VecDeltaSteppedDeltaStep) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Ticks, &v.Xa, &v.Ya, &v.Za}.ReadFrom(r)
}

func (v VecDeltaSteppedDeltaStep) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Ticks, v.Xa, v.Ya, v.Za}.WriteTo(w)
}

// VecDeltaLinear is Java VecDelta$Linear.
type VecDeltaLinear struct {
	Xa pk.Short
	Ya pk.Short
	Za pk.Short
}

func (v *VecDeltaLinear) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Xa, &v.Ya, &v.Za}.ReadFrom(r)
}

func (v VecDeltaLinear) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Xa, v.Ya, v.Za}.WriteTo(w)
}

// NewMinecartBehaviorMinecartStep is Java NewMinecartBehavior$MinecartStep.
type NewMinecartBehaviorMinecartStep struct {
	Position Vec3
	Movement Vec3
	YRot     pk.Angle
	XRot     pk.Angle
	Weight   pk.Float
}

func (v *NewMinecartBehaviorMinecartStep) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Position, &v.Movement, &v.YRot, &v.XRot, &v.Weight}.ReadFrom(r)
}

func (v NewMinecartBehaviorMinecartStep) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Position, v.Movement, v.YRot, v.XRot, v.Weight}.WriteTo(w)
}

// ItemStackTemplate is Java ItemStackTemplate.
type ItemStackTemplate struct {
	Item       pk.VarInt // holder in item
	Count      pk.VarInt
	Components ComponentPatch
}

func (v *ItemStackTemplate) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Item, &v.Count, &v.Components}.ReadFrom(r)
}

func (v ItemStackTemplate) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Item, v.Count, v.Components}.WriteTo(w)
}

// TrimPattern is Java TrimPattern.
type TrimPattern struct {
	AssetID     pk.Identifier
	Description Text
	Decal       pk.Boolean
}

func (v *TrimPattern) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.AssetID, &v.Description, &v.Decal}.ReadFrom(r)
}

func (v TrimPattern) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.AssetID, v.Description, v.Decal}.WriteTo(w)
}

// LastSeenMessagesPacked is Java LastSeenMessages$Packed.
type LastSeenMessagesPacked struct {
	Entries List[MessageSignaturePacked, *MessageSignaturePacked]
}

func (v *LastSeenMessagesPacked) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Entries}.ReadFrom(r)
}

func (v LastSeenMessagesPacked) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Entries}.WriteTo(w)
}

// SignedMessageBodyPacked is Java SignedMessageBody$Packed.
type SignedMessageBodyPacked struct {
	Content   pk.String
	TimeStamp Instant
	Salt      pk.Long
	LastSeen  LastSeenMessagesPacked
}

func (v *SignedMessageBodyPacked) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Content, &v.TimeStamp, &v.Salt, &v.LastSeen}.ReadFrom(r)
}

func (v SignedMessageBodyPacked) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Content, v.TimeStamp, v.Salt, v.LastSeen}.WriteTo(w)
}

// ProfilePublicKeyData is Java ProfilePublicKey$Data.
type ProfilePublicKeyData struct {
	ExpiresAt    Instant
	Key          PublicKey
	KeySignature pk.ByteArray
}

func (v *ProfilePublicKeyData) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.ExpiresAt, &v.Key, &v.KeySignature}.ReadFrom(r)
}

func (v ProfilePublicKeyData) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.ExpiresAt, v.Key, v.KeySignature}.WriteTo(w)
}

// RemoteChatSessionData is Java RemoteChatSession$Data.
type RemoteChatSessionData struct {
	SessionID        pk.UUID
	ProfilePublicKey ProfilePublicKeyData
}

func (v *RemoteChatSessionData) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.SessionID, &v.ProfilePublicKey}.ReadFrom(r)
}

func (v RemoteChatSessionData) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.SessionID, v.ProfilePublicKey}.WriteTo(w)
}

// PositionMoveRotation is Java PositionMoveRotation.
type PositionMoveRotation struct {
	Position      Vec3
	DeltaMovement Vec3
	YRot          pk.Float
	XRot          pk.Float
}

func (v *PositionMoveRotation) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Position, &v.DeltaMovement, &v.YRot, &v.XRot}.ReadFrom(r)
}

func (v PositionMoveRotation) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Position, v.DeltaMovement, v.YRot, v.XRot}.WriteTo(w)
}

// RecipeDisplayId is Java RecipeDisplayId.
type RecipeDisplayId struct {
	Index pk.VarInt
}

func (v *RecipeDisplayId) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Index}.ReadFrom(r)
}

func (v RecipeDisplayId) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Index}.WriteTo(w)
}

// RecipeDisplayEntry is Java RecipeDisplayEntry.
type RecipeDisplayEntry struct {
	ID                   RecipeDisplayId
	Display              RecipeDisplay
	Group                OptionalVarInt
	Category             pk.VarInt // registry recipe_book_category
	CraftingRequirements pk.Option[List[IDSet, *IDSet], *List[IDSet, *IDSet]]
}

func (v *RecipeDisplayEntry) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.ID, &v.Display, &v.Group, &v.Category, &v.CraftingRequirements}.ReadFrom(r)
}

func (v RecipeDisplayEntry) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.ID, v.Display, v.Group, v.Category, v.CraftingRequirements}.WriteTo(w)
}

// RecipeBookAddEntry is Java ClientboundRecipeBookAddPacket$Entry.
type RecipeBookAddEntry struct {
	Contents RecipeDisplayEntry
	Flags    pk.Byte
}

func (v *RecipeBookAddEntry) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Contents, &v.Flags}.ReadFrom(r)
}

func (v RecipeBookAddEntry) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Contents, v.Flags}.WriteTo(w)
}

// RecipeBookSettingsTypeSettings is Java RecipeBookSettings$TypeSettings.
type RecipeBookSettingsTypeSettings struct {
	Open      pk.Boolean
	Filtering pk.Boolean
}

func (v *RecipeBookSettingsTypeSettings) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Open, &v.Filtering}.ReadFrom(r)
}

func (v RecipeBookSettingsTypeSettings) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Open, v.Filtering}.WriteTo(w)
}

// RecipeBookSettings is Java RecipeBookSettings.
type RecipeBookSettings struct {
	Crafting     RecipeBookSettingsTypeSettings
	Furnace      RecipeBookSettingsTypeSettings
	BlastFurnace RecipeBookSettingsTypeSettings
	Smoker       RecipeBookSettingsTypeSettings
}

func (v *RecipeBookSettings) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Crafting, &v.Furnace, &v.BlastFurnace, &v.Smoker}.ReadFrom(r)
}

func (v RecipeBookSettings) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Crafting, v.Furnace, v.BlastFurnace, v.Smoker}.WriteTo(w)
}

// LevelDataRespawnData is Java LevelData$RespawnData.
type LevelDataRespawnData struct {
	GlobalPos GlobalPos
	Yaw       pk.Float
	Pitch     pk.Float
}

func (v *LevelDataRespawnData) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.GlobalPos, &v.Yaw, &v.Pitch}.ReadFrom(r)
}

func (v LevelDataRespawnData) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.GlobalPos, v.Yaw, v.Pitch}.WriteTo(w)
}

// SetEquipmentEntry is Java ClientboundSetEquipmentEntry.
type SetEquipmentEntry struct {
	SlotID    pk.Byte
	ItemStack ItemStack
}

func (v *SetEquipmentEntry) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.SlotID, &v.ItemStack}.ReadFrom(r)
}

func (v SetEquipmentEntry) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.SlotID, v.ItemStack}.WriteTo(w)
}

// SetPlayerTeamParameters is Java ClientboundSetPlayerTeamPacket$Parameters.
type SetPlayerTeamParameters struct {
	DisplayName       Text
	PlayerPrefix      Text
	PlayerSuffix      Text
	NameTagVisibility TeamVisibility
	CollisionRule     TeamCollisionRule
	Color             pk.Option[TeamColor, *TeamColor]
	Options           pk.Byte
}

func (v *SetPlayerTeamParameters) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.DisplayName, &v.PlayerPrefix, &v.PlayerSuffix, &v.NameTagVisibility, &v.CollisionRule, &v.Color, &v.Options}.ReadFrom(r)
}

func (v SetPlayerTeamParameters) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.DisplayName, v.PlayerPrefix, v.PlayerSuffix, v.NameTagVisibility, v.CollisionRule, v.Color, v.Options}.WriteTo(w)
}

// ClockNetworkState is Java ClockNetworkState.
type ClockNetworkState struct {
	TotalTicks  pk.VarLong
	PartialTick pk.Float
	Rate        pk.Float
}

func (v *ClockNetworkState) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.TotalTicks, &v.PartialTick, &v.Rate}.ReadFrom(r)
}

func (v ClockNetworkState) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.TotalTicks, v.PartialTick, v.Rate}.WriteTo(w)
}

// SwingAnimation is Java SwingAnimation.
type SwingAnimation struct {
	Type     SwingAnimationType
	Duration pk.VarInt
}

func (v *SwingAnimation) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Type, &v.Duration}.ReadFrom(r)
}

func (v SwingAnimation) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Type, v.Duration}.WriteTo(w)
}

// Vec3i is Java Vec3i.
type Vec3i struct {
	X pk.VarInt
	Y pk.VarInt
	Z pk.VarInt
}

func (v *Vec3i) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.X, &v.Y, &v.Z}.ReadFrom(r)
}

func (v Vec3i) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.X, v.Y, v.Z}.WriteTo(w)
}

// ClientAssetResourceTexture is Java ClientAsset$ResourceTexture.
type ClientAssetResourceTexture struct {
	Texture pk.Identifier
}

func (v *ClientAssetResourceTexture) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Texture}.ReadFrom(r)
}

func (v ClientAssetResourceTexture) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Texture}.WriteTo(w)
}

// DisplayInfo is Java DisplayInfo.
type DisplayInfo struct {
	Title       Text
	Description Text
	Icon        ItemStackTemplate
	Frame       AdvancementType
	Flags       pk.Int
	Background  ClientAssetResourceTexture
}

func (v *DisplayInfo) ReadFrom(r io.Reader) (n int64, err error) {
	var m int64
	m, err = pk.Tuple{&v.Title, &v.Description, &v.Icon, &v.Frame, &v.Flags}.ReadFrom(r)
	n += m
	if err != nil {
		return n, err
	}
	if v.Flags&1 != 0 {
		m, err = pk.Tuple{&v.Background}.ReadFrom(r)
		n += m
		if err != nil {
			return n, err
		}
	}
	return n, nil
}

func (v DisplayInfo) WriteTo(w io.Writer) (n int64, err error) {
	var m int64
	m, err = pk.Tuple{v.Title, v.Description, v.Icon, v.Frame, v.Flags}.WriteTo(w)
	n += m
	if err != nil {
		return n, err
	}
	if v.Flags&1 != 0 {
		m, err = pk.Tuple{v.Background}.WriteTo(w)
		n += m
		if err != nil {
			return n, err
		}
	}
	return n, nil
}

// Advancement is Java Advancement.
type Advancement struct {
	Parent              pk.Option[pk.Identifier, *pk.Identifier]
	Display             pk.Option[DisplayInfo, *DisplayInfo]
	Requirements        List[List[pk.String, *pk.String], *List[pk.String, *pk.String]]
	SendsTelemetryEvent pk.Boolean
}

func (v *Advancement) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Parent, &v.Display, &v.Requirements, &v.SendsTelemetryEvent}.ReadFrom(r)
}

func (v Advancement) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Parent, v.Display, v.Requirements, v.SendsTelemetryEvent}.WriteTo(w)
}

// AdvancementHolder is Java AdvancementHolder.
type AdvancementHolder struct {
	ID    pk.Identifier
	Value Advancement
}

func (v *AdvancementHolder) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.ID, &v.Value}.ReadFrom(r)
}

func (v AdvancementHolder) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.ID, v.Value}.WriteTo(w)
}

// UpdateAdvancementsPositionedAdvancement is Java ClientboundUpdateAdvancementsPacket$PositionedAdvancement.
type UpdateAdvancementsPositionedAdvancement struct {
	Advancement AdvancementHolder
	X           pk.Float
	Y           pk.Float
}

func (v *UpdateAdvancementsPositionedAdvancement) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Advancement, &v.X, &v.Y}.ReadFrom(r)
}

func (v UpdateAdvancementsPositionedAdvancement) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Advancement, v.X, v.Y}.WriteTo(w)
}

// AdvancementProgress is Java AdvancementProgress.
type AdvancementProgress struct {
	Criteria Map[pk.String, *pk.String, pk.Option[Instant, *Instant], *pk.Option[Instant, *Instant]]
}

func (v *AdvancementProgress) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Criteria}.ReadFrom(r)
}

func (v AdvancementProgress) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Criteria}.WriteTo(w)
}

// AttributeModifier is Java AttributeModifier.
type AttributeModifier struct {
	ID        pk.Identifier
	Amount    pk.Double
	Operation AttributeModifierOperation
}

func (v *AttributeModifier) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.ID, &v.Amount, &v.Operation}.ReadFrom(r)
}

func (v AttributeModifier) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.ID, v.Amount, v.Operation}.WriteTo(w)
}

// UpdateAttributesAttributeSnapshot is Java ClientboundUpdateAttributesPacket$AttributeSnapshot.
type UpdateAttributesAttributeSnapshot struct {
	Attribute pk.VarInt // holder in attribute
	Base      pk.Double
	Modifiers List[AttributeModifier, *AttributeModifier]
}

func (v *UpdateAttributesAttributeSnapshot) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Attribute, &v.Base, &v.Modifiers}.ReadFrom(r)
}

func (v UpdateAttributesAttributeSnapshot) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Attribute, v.Base, v.Modifiers}.WriteTo(w)
}

// SelectableRecipe is Java SelectableRecipe.
type SelectableRecipe struct {
	OptionDisplay SlotDisplay
}

func (v *SelectableRecipe) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.OptionDisplay}.ReadFrom(r)
}

func (v SelectableRecipe) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.OptionDisplay}.WriteTo(w)
}

// SelectableRecipeSingleInputEntry is Java SelectableRecipe$SingleInputEntry.
type SelectableRecipeSingleInputEntry struct {
	Input  IDSet // registry item
	Recipe SelectableRecipe
}

func (v *SelectableRecipeSingleInputEntry) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Input, &v.Recipe}.ReadFrom(r)
}

func (v SelectableRecipeSingleInputEntry) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Input, v.Recipe}.WriteTo(w)
}

// SelectableRecipeSingleInputSet is Java SelectableRecipe$SingleInputSet.
type SelectableRecipeSingleInputSet struct {
	Entries List[SelectableRecipeSingleInputEntry, *SelectableRecipeSingleInputEntry]
}

func (v *SelectableRecipeSingleInputSet) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Entries}.ReadFrom(r)
}

func (v SelectableRecipeSingleInputSet) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Entries}.WriteTo(w)
}

// RGBColor is Java RGBColor.
type RGBColor struct {
	Red   pk.UnsignedByte
	Green pk.UnsignedByte
	Blue  pk.UnsignedByte
}

func (v *RGBColor) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Red, &v.Green, &v.Blue}.ReadFrom(r)
}

func (v RGBColor) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Red, v.Green, v.Blue}.WriteTo(w)
}

// WaypointIcon is Java Waypoint$Icon.
type WaypointIcon struct {
	Style pk.Identifier // resource key in root_id
	Color pk.Option[RGBColor, *RGBColor]
}

func (v *WaypointIcon) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Style, &v.Color}.ReadFrom(r)
}

func (v WaypointIcon) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Style, v.Color}.WriteTo(w)
}

// ChunkPosRecord is Java ChunkPos.
type ChunkPosRecord struct {
	X pk.VarInt
	Z pk.VarInt
}

func (v *ChunkPosRecord) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.X, &v.Z}.ReadFrom(r)
}

func (v ChunkPosRecord) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.X, v.Z}.WriteTo(w)
}

// TrackedWaypoint is Java TrackedWaypoint.
type TrackedWaypoint struct {
	Identifier Either[pk.UUID, *pk.UUID, pk.String, *pk.String]
	Icon       WaypointIcon
	Type       TrackedWaypointPayload
}

func (v *TrackedWaypoint) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Identifier, &v.Icon, &v.Type}.ReadFrom(r)
}

func (v TrackedWaypoint) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Identifier, v.Icon, v.Type}.WriteTo(w)
}

// LastSeenMessagesUpdate is Java LastSeenMessages$Update.
type LastSeenMessagesUpdate struct {
	Offset       pk.VarInt
	Acknowledged FixedBits20
	Checksum     pk.Byte
}

func (v *LastSeenMessagesUpdate) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Offset, &v.Acknowledged, &v.Checksum}.ReadFrom(r)
}

func (v LastSeenMessagesUpdate) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Offset, v.Acknowledged, v.Checksum}.WriteTo(w)
}

// ArgumentSignaturesEntry is Java ArgumentSignatures$Entry.
type ArgumentSignaturesEntry struct {
	Name      pk.String
	Signature MessageSignature
}

func (v *ArgumentSignaturesEntry) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Name, &v.Signature}.ReadFrom(r)
}

func (v ArgumentSignaturesEntry) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Name, v.Signature}.WriteTo(w)
}

// ArgumentSignatures is Java ArgumentSignatures.
type ArgumentSignatures struct {
	Entries List[ArgumentSignaturesEntry, *ArgumentSignaturesEntry]
}

func (v *ArgumentSignatures) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Entries}.ReadFrom(r)
}

func (v ArgumentSignatures) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Entries}.WriteTo(w)
}

// HashedPatchMap is Java HashedPatchMap.
type HashedPatchMap struct {
	AddedComponents   Map[pk.VarInt, *pk.VarInt, pk.Int, *pk.Int]
	RemovedComponents List[pk.VarInt, *pk.VarInt]
}

func (v *HashedPatchMap) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.AddedComponents, &v.RemovedComponents}.ReadFrom(r)
}

func (v HashedPatchMap) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.AddedComponents, v.RemovedComponents}.WriteTo(w)
}

// HashedStackActualItem is Java HashedStack$ActualItem.
type HashedStackActualItem struct {
	Item       pk.VarInt // holder in item
	Count      pk.VarInt
	Components HashedPatchMap
}

func (v *HashedStackActualItem) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Item, &v.Count, &v.Components}.ReadFrom(r)
}

func (v HashedStackActualItem) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Item, v.Count, v.Components}.WriteTo(w)
}

// PositionAndRotation is Java PositionAndRotation.
type PositionAndRotation struct {
	Position Vec3
	YRot     pk.Float
	XRot     pk.Float
}

func (v *PositionAndRotation) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Position, &v.YRot, &v.XRot}.ReadFrom(r)
}

func (v PositionAndRotation) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Position, v.YRot, v.XRot}.WriteTo(w)
}

// SetGameRuleEntry is Java ServerboundSetGameRulePacket$Entry.
type SetGameRuleEntry struct {
	GameRuleKey pk.Identifier // resource key in game_rule
	Value       pk.String
}

func (v *SetGameRuleEntry) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.GameRuleKey, &v.Value}.ReadFrom(r)
}

func (v SetGameRuleEntry) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.GameRuleKey, v.Value}.WriteTo(w)
}

// BlockPos is Java BlockPos.
type BlockPos struct {
	X pk.Byte
	Y pk.Byte
	Z pk.Byte
}

func (v *BlockPos) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.X, &v.Y, &v.Z}.ReadFrom(r)
}

func (v BlockPos) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.X, v.Y, v.Z}.WriteTo(w)
}

// Vec3iByte is Java Vec3i.
type Vec3iByte struct {
	X pk.Byte
	Y pk.Byte
	Z pk.Byte
}

func (v *Vec3iByte) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.X, &v.Y, &v.Z}.ReadFrom(r)
}

func (v Vec3iByte) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.X, v.Y, v.Z}.WriteTo(w)
}

// TestInstanceBlockEntityData is Java TestInstanceBlockEntity$Data.
type TestInstanceBlockEntityData struct {
	Test           pk.Option[pk.Identifier, *pk.Identifier]
	Size           Vec3i
	Rotation       Rotation
	IgnoreEntities pk.Boolean
	Status         TestInstanceBlockEntityStatus
	ErrorMessage   pk.Option[Text, *Text]
}

func (v *TestInstanceBlockEntityData) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Test, &v.Size, &v.Rotation, &v.IgnoreEntities, &v.Status, &v.ErrorMessage}.ReadFrom(r)
}

func (v TestInstanceBlockEntityData) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Test, v.Size, v.Rotation, v.IgnoreEntities, v.Status, v.ErrorMessage}.WriteTo(w)
}

// Rotations is Java Rotations.
type Rotations struct {
	X pk.Float
	Y pk.Float
	Z pk.Float
}

func (v *Rotations) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.X, &v.Y, &v.Z}.ReadFrom(r)
}

func (v Rotations) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.X, v.Y, v.Z}.WriteTo(w)
}

// VillagerData is Java VillagerData.
type VillagerData struct {
	Type       pk.VarInt // holder in villager_type
	Profession pk.VarInt // holder in villager_profession
	Level      pk.VarInt
}

func (v *VillagerData) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Type, &v.Profession, &v.Level}.ReadFrom(r)
}

func (v VillagerData) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Type, v.Profession, v.Level}.WriteTo(w)
}

// PaintingVariant is Java PaintingVariant.
type PaintingVariant struct {
	Width   pk.VarInt
	Height  pk.VarInt
	AssetID pk.Identifier
	Title   pk.Option[Text, *Text]
	Author  pk.Option[Text, *Text]
}

func (v *PaintingVariant) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Width, &v.Height, &v.AssetID, &v.Title, &v.Author}.ReadFrom(r)
}

func (v PaintingVariant) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Width, v.Height, v.AssetID, v.Title, v.Author}.WriteTo(w)
}

// ResolvableProfilePartial is Java ResolvableProfile$Partial.
type ResolvableProfilePartial struct {
	Name       pk.Option[pk.String, *pk.String]
	ID         pk.Option[pk.UUID, *pk.UUID]
	Properties List[user.Property, *user.Property]
}

func (v *ResolvableProfilePartial) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Name, &v.ID, &v.Properties}.ReadFrom(r)
}

func (v ResolvableProfilePartial) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Name, v.ID, v.Properties}.WriteTo(w)
}

// PlayerSkinPatch is Java PlayerSkin$Patch.
type PlayerSkinPatch struct {
	Body   pk.Option[pk.Identifier, *pk.Identifier]
	Cape   pk.Option[pk.Identifier, *pk.Identifier]
	Elytra pk.Option[pk.Identifier, *pk.Identifier]
	Model  pk.Option[pk.Boolean, *pk.Boolean]
}

func (v *PlayerSkinPatch) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Body, &v.Cape, &v.Elytra, &v.Model}.ReadFrom(r)
}

func (v PlayerSkinPatch) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Body, v.Cape, v.Elytra, v.Model}.WriteTo(w)
}

// ResolvableProfile is Java ResolvableProfile.
type ResolvableProfile struct {
	Unpack    Either[GameProfile, *GameProfile, ResolvableProfilePartial, *ResolvableProfilePartial]
	SkinPatch PlayerSkinPatch
}

func (v *ResolvableProfile) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Unpack, &v.SkinPatch}.ReadFrom(r)
}

func (v ResolvableProfile) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Unpack, v.SkinPatch}.WriteTo(w)
}
