// Code generated by gen/gen_packets.go from 26.2/packet_schema.json; DO NOT EDIT.
package types

import "github.com/mj41/go-mc26/wire"

// The shared structures and enums generated into package wire, under the names the packets use.
type (
	BlockHitResult                      = wire.BlockHitResult
	GameProfile                         = wire.GameProfile
	GlobalPos                           = wire.GlobalPos
	LevelChunkPacketDataBlockEntityInfo = wire.LevelChunkPacketDataBlockEntityInfo
	Quaternionf                         = wire.Quaternionf
	Vec3                                = wire.Vec3
	Vector3f                            = wire.Vector3f
	Direction                           = wire.Direction
)
