// Code generated by gen/gen_components.go from 26.3/packet_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/mj41/go-mc26/net/packet"
	"io"
)

// AdditionalTradeCost is the data component minecraft:additional_trade_cost.
type AdditionalTradeCost struct{ Value pk.VarInt }

func (v *AdditionalTradeCost) ReadFrom(r io.Reader) (int64, error) { return v.Value.ReadFrom(r) }
func (v AdditionalTradeCost) WriteTo(w io.Writer) (int64, error)   { return v.Value.WriteTo(w) }

// ID returns the registry name of the component.
func (AdditionalTradeCost) ID() string { return "minecraft:additional_trade_cost" }

var _ DataComponent = (*AdditionalTradeCost)(nil)
