// Code generated by gen/gen_components.go from 26.3/packet_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/mj41/go-mc26/net/packet"
	"io"
)

// AttackAnimation is the data component minecraft:attack_animation (Java SwingAnimation).
type AttackAnimation struct {
	Type     SwingAnimationType
	Duration pk.VarInt
}

func (v *AttackAnimation) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Type, &v.Duration}.ReadFrom(r)
}

func (v AttackAnimation) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Type, v.Duration}.WriteTo(w)
}

// ID returns the registry name of the component.
func (AttackAnimation) ID() string { return "minecraft:attack_animation" }

var _ DataComponent = (*AttackAnimation)(nil)
