// Code generated by gen/gen_components.go from 26.1/packet_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/mj41/go-mc26/net/packet"
	"io"
)

// AttackRange is the data component minecraft:attack_range (Java AttackRange).
type AttackRange struct {
	MinReach         pk.Float
	MaxReach         pk.Float
	MinCreativeReach pk.Float
	MaxCreativeReach pk.Float
	HitboxMargin     pk.Float
	MobFactor        pk.Float
}

func (v *AttackRange) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.MinReach, &v.MaxReach, &v.MinCreativeReach, &v.MaxCreativeReach, &v.HitboxMargin, &v.MobFactor}.ReadFrom(r)
}

func (v AttackRange) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.MinReach, v.MaxReach, v.MinCreativeReach, v.MaxCreativeReach, v.HitboxMargin, v.MobFactor}.WriteTo(w)
}

// ID returns the registry name of the component.
func (AttackRange) ID() string { return "minecraft:attack_range" }

var _ DataComponent = (*AttackRange)(nil)
