// Code generated by gen/gen_components.go from 26.3/packet_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/mj41/go-mc26/net/packet"
	"github.com/mj41/go-mc26/wire"
	"io"
)

// AttributeModifiers is the data component minecraft:attribute_modifiers (Java ItemAttributeModifiers).
type AttributeModifiers struct {
	Modifiers wire.List[ItemAttributeModifiersEntry, *ItemAttributeModifiersEntry]
}

func (v *AttributeModifiers) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Modifiers}.ReadFrom(r)
}

func (v AttributeModifiers) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Modifiers}.WriteTo(w)
}

// ID returns the registry name of the component.
func (AttributeModifiers) ID() string { return "minecraft:attribute_modifiers" }

var _ DataComponent = (*AttributeModifiers)(nil)
