// Code generated by gen/gen_components.go from 26.3/packet_schema.json; DO NOT EDIT.
package component

// AxolotlVariant is the data component minecraft:axolotl/variant (Java Axolotl$Variant).
// ID returns the registry name of the component.
func (AxolotlVariant) ID() string { return "minecraft:axolotl/variant" }

var _ DataComponent = (*AxolotlVariant)(nil)
