// Code generated by gen/gen_components.go from 26.2/packet_schema.json; DO NOT EDIT.
package component

import (
	"io"
)

// BaseColor is the data component minecraft:base_color.
// Value: DyeColor.
type BaseColor struct{ Value DyeColor }

func (v *BaseColor) ReadFrom(r io.Reader) (int64, error) { return v.Value.ReadFrom(r) }
func (v BaseColor) WriteTo(w io.Writer) (int64, error)   { return v.Value.WriteTo(w) }

// ID returns the registry name of the component.
func (BaseColor) ID() string { return "minecraft:base_color" }

var _ DataComponent = (*BaseColor)(nil)
