// Code generated by gen/gen_components.go from 26.1/packet_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/mj41/go-mc26/net/packet"
	"github.com/mj41/go-mc26/wire"
	"io"
)

// BlockState is the data component minecraft:block_state.
type BlockState struct {
	Value wire.Map[pk.String, *pk.String, pk.String, *pk.String]
}

func (v *BlockState) ReadFrom(r io.Reader) (int64, error) { return v.Value.ReadFrom(r) }
func (v BlockState) WriteTo(w io.Writer) (int64, error)   { return v.Value.WriteTo(w) }

// ID returns the registry name of the component.
func (BlockState) ID() string { return "minecraft:block_state" }

var _ DataComponent = (*BlockState)(nil)
