// Code generated by gen/gen_components.go from 26.3/packet_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/mj41/go-mc26/net/packet"
	"io"
)

// BlockTransformer is the data component minecraft:block_transformer.
// Value: holder in block_transformer.
type BlockTransformer struct{ Value pk.VarInt }

func (v *BlockTransformer) ReadFrom(r io.Reader) (int64, error) { return v.Value.ReadFrom(r) }
func (v BlockTransformer) WriteTo(w io.Writer) (int64, error)   { return v.Value.WriteTo(w) }

// ID returns the registry name of the component.
func (BlockTransformer) ID() string { return "minecraft:block_transformer" }

var _ DataComponent = (*BlockTransformer)(nil)
