// Code generated by gen/gen_components.go from 26.3/packet_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/mj41/go-mc26/net/packet"
	"github.com/mj41/go-mc26/wire"
	"io"
)

// BlocksAttacks is the data component minecraft:blocks_attacks (Java BlocksAttacks).
type BlocksAttacks struct {
	BlockDelaySeconds    pk.Float
	DisableCooldownScale pk.Float
	DamageReductions     wire.List[BlocksAttacksDamageReduction, *BlocksAttacksDamageReduction]
	ItemDamage           BlocksAttacksItemDamageFunction
	BypassedBy           pk.Option[wire.IDSet, *wire.IDSet]
	BlockSound           pk.Option[wire.Holder[SoundEvent, *SoundEvent], *wire.Holder[SoundEvent, *SoundEvent]]
	DisableSound         pk.Option[wire.Holder[SoundEvent, *SoundEvent], *wire.Holder[SoundEvent, *SoundEvent]]
}

func (v *BlocksAttacks) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.BlockDelaySeconds, &v.DisableCooldownScale, &v.DamageReductions, &v.ItemDamage, &v.BypassedBy, &v.BlockSound, &v.DisableSound}.ReadFrom(r)
}

func (v BlocksAttacks) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.BlockDelaySeconds, v.DisableCooldownScale, v.DamageReductions, v.ItemDamage, v.BypassedBy, v.BlockSound, v.DisableSound}.WriteTo(w)
}

// ID returns the registry name of the component.
func (BlocksAttacks) ID() string { return "minecraft:blocks_attacks" }

var _ DataComponent = (*BlocksAttacks)(nil)
