// Code generated by gen/gen_components.go from 26.2/packet_schema.json; DO NOT EDIT.
package component

import (
	"github.com/mj41/go-mc26/wire"
	"io"
)

// BundleContents is the data component minecraft:bundle_contents.
type BundleContents struct {
	Value wire.List[ItemStackTemplate, *ItemStackTemplate]
}

func (v *BundleContents) ReadFrom(r io.Reader) (int64, error) { return v.Value.ReadFrom(r) }
func (v BundleContents) WriteTo(w io.Writer) (int64, error)   { return v.Value.WriteTo(w) }

// ID returns the registry name of the component.
func (BundleContents) ID() string { return "minecraft:bundle_contents" }

var _ DataComponent = (*BundleContents)(nil)
