// Code generated by gen/gen_components.go from 26.3/packet_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/mj41/go-mc26/net/packet"
	"github.com/mj41/go-mc26/wire"
	"io"
)

// CanBreak is the data component minecraft:can_break (Java AdventureModePredicate).
type CanBreak struct {
	Predicates wire.List[BlockPredicate, *BlockPredicate]
}

func (v *CanBreak) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Predicates}.ReadFrom(r)
}

func (v CanBreak) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Predicates}.WriteTo(w)
}

// ID returns the registry name of the component.
func (CanBreak) ID() string { return "minecraft:can_break" }

var _ DataComponent = (*CanBreak)(nil)
