// Code generated by gen/gen_components.go from 26.3/packet_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/mj41/go-mc26/net/packet"
	"io"
)

// CatSoundVariant is the data component minecraft:cat/sound_variant.
// Value: holder in cat_sound_variant.
type CatSoundVariant struct{ Value pk.VarInt }

func (v *CatSoundVariant) ReadFrom(r io.Reader) (int64, error) { return v.Value.ReadFrom(r) }
func (v CatSoundVariant) WriteTo(w io.Writer) (int64, error)   { return v.Value.WriteTo(w) }

// ID returns the registry name of the component.
func (CatSoundVariant) ID() string { return "minecraft:cat/sound_variant" }

var _ DataComponent = (*CatSoundVariant)(nil)
