// Code generated by gen/gen_components.go from 26.1/packet_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/mj41/go-mc26/net/packet"
	"io"
)

// CatVariant is the data component minecraft:cat/variant.
// Value: holder in cat_variant.
type CatVariant struct{ Value pk.VarInt }

func (v *CatVariant) ReadFrom(r io.Reader) (int64, error) { return v.Value.ReadFrom(r) }
func (v CatVariant) WriteTo(w io.Writer) (int64, error)   { return v.Value.WriteTo(w) }

// ID returns the registry name of the component.
func (CatVariant) ID() string { return "minecraft:cat/variant" }

var _ DataComponent = (*CatVariant)(nil)
