// Code generated by gen/gen_components.go from 26.1/packet_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/mj41/go-mc26/net/packet"
	"io"
)

// ChickenSoundVariant is the data component minecraft:chicken/sound_variant.
// Value: holder in chicken_sound_variant.
type ChickenSoundVariant struct{ Value pk.VarInt }

func (v *ChickenSoundVariant) ReadFrom(r io.Reader) (int64, error) { return v.Value.ReadFrom(r) }
func (v ChickenSoundVariant) WriteTo(w io.Writer) (int64, error)   { return v.Value.WriteTo(w) }

// ID returns the registry name of the component.
func (ChickenSoundVariant) ID() string { return "minecraft:chicken/sound_variant" }

var _ DataComponent = (*ChickenSoundVariant)(nil)
