// Code generated by gen/gen_components.go from 26.3/packet_schema.json; DO NOT EDIT.
package component

import (
	"bytes"
	"testing"
)

// TestComponentRoundTrip encodes the zero value of every generated component,
// decodes it and encodes it again; the two encodings must match.
func TestComponentRoundTrip(t *testing.T) {
	cases := []struct {
		name string
		zero DataComponent
	}{
		{"minecraft:additional_trade_cost", new(AdditionalTradeCost)},
		{"minecraft:attack_animation", new(AttackAnimation)},
		{"minecraft:attack_range", new(AttackRange)},
		{"minecraft:attribute_modifiers", new(AttributeModifiers)},
		{"minecraft:axolotl/variant", new(AxolotlVariant)},
		{"minecraft:banner_patterns", new(BannerPatterns)},
		{"minecraft:base_color", new(BaseColor)},
		{"minecraft:bees", new(Bees)},
		{"minecraft:block_entity_data", new(BlockEntityData)},
		{"minecraft:block_state", new(BlockState)},
		{"minecraft:block_transformer", new(BlockTransformer)},
		{"minecraft:blocks_attacks", new(BlocksAttacks)},
		{"minecraft:break_sound", new(BreakSound)},
		{"minecraft:brewing_fuel", new(BrewingFuel)},
		{"minecraft:bucket_entity_data", new(BucketEntityData)},
		{"minecraft:bundle_contents", new(BundleContents)},
		{"minecraft:can_break", new(CanBreak)},
		{"minecraft:can_place_on", new(CanPlaceOn)},
		{"minecraft:cat/collar", new(CatCollar)},
		{"minecraft:cat/sound_variant", new(CatSoundVariant)},
		{"minecraft:cat/variant", new(CatVariant)},
		{"minecraft:charged_projectiles", new(ChargedProjectiles)},
		{"minecraft:chicken/sound_variant", new(ChickenSoundVariant)},
		{"minecraft:chicken/variant", new(ChickenVariant)},
		{"minecraft:compostable", new(Compostable)},
		{"minecraft:consumable", new(Consumable)},
		{"minecraft:container", new(Container)},
		{"minecraft:container_loot", new(ContainerLoot)},
		{"minecraft:cooking_fuel", new(CookingFuel)},
		{"minecraft:cow/sound_variant", new(CowSoundVariant)},
		{"minecraft:cow/variant", new(CowVariant)},
		{"minecraft:creative_slot_lock", new(CreativeSlotLock)},
		{"minecraft:cushion/color", new(CushionColor)},
		{"minecraft:custom_data", new(CustomData)},
		{"minecraft:custom_model_data", new(CustomModelData)},
		{"minecraft:custom_name", new(CustomName)},
		{"minecraft:damage", new(Damage)},
		{"minecraft:damage_resistant", new(DamageResistant)},
		{"minecraft:damage_type", new(DamageType)},
		{"minecraft:death_protection", new(DeathProtection)},
		{"minecraft:debug_stick_state", new(DebugStickState)},
		{"minecraft:dye", new(Dye)},
		{"minecraft:dyed_color", new(DyedColor)},
		{"minecraft:enchantable", new(Enchantable)},
		{"minecraft:enchantment_glint_override", new(EnchantmentGlintOverride)},
		{"minecraft:enchantments", new(Enchantments)},
		{"minecraft:entity_data", new(EntityData)},
		{"minecraft:equippable", new(Equippable)},
		{"minecraft:firework_explosion", new(FireworkExplosion)},
		{"minecraft:fireworks", new(Fireworks)},
		{"minecraft:food", new(Food)},
		{"minecraft:fox/variant", new(FoxVariant)},
		{"minecraft:frog/variant", new(FrogVariant)},
		{"minecraft:glider", new(Glider)},
		{"minecraft:horse/variant", new(HorseVariant)},
		{"minecraft:instrument", new(Instrument)},
		{"minecraft:intangible_projectile", new(IntangibleProjectile)},
		{"minecraft:interact_animation", new(InteractAnimation)},
		{"minecraft:item_model", new(ItemModel)},
		{"minecraft:item_name", new(ItemName)},
		{"minecraft:jukebox_playable", new(JukeboxPlayable)},
		{"minecraft:kinetic_weapon", new(KineticWeapon)},
		{"minecraft:llama/variant", new(LlamaVariant)},
		{"minecraft:lock", new(Lock)},
		{"minecraft:lodestone_tracker", new(LodestoneTracker)},
		{"minecraft:lore", new(Lore)},
		{"minecraft:map_decorations", new(MapDecorations)},
		{"minecraft:map_id", new(MapID)},
		{"minecraft:map_post_processing", new(MapPostProcessing)},
		{"minecraft:max_damage", new(MaxDamage)},
		{"minecraft:max_stack_size", new(MaxStackSize)},
		{"minecraft:minimum_attack_charge", new(MinimumAttackCharge)},
		{"minecraft:mob_visibility", new(MobVisibility)},
		{"minecraft:mooshroom/variant", new(MooshroomVariant)},
		{"minecraft:note_block_sound", new(NoteBlockSound)},
		{"minecraft:ominous_bottle_amplifier", new(OminousBottleAmplifier)},
		{"minecraft:painting/variant", new(PaintingVariant)},
		{"minecraft:parrot/variant", new(ParrotVariant)},
		{"minecraft:piercing_weapon", new(PiercingWeapon)},
		{"minecraft:pig/sound_variant", new(PigSoundVariant)},
		{"minecraft:pig/variant", new(PigVariant)},
		{"minecraft:pot_decorations", new(PotDecorations)},
		{"minecraft:potion_contents", new(PotionContents)},
		{"minecraft:potion_duration_scale", new(PotionDurationScale)},
		{"minecraft:profile", new(Profile)},
		{"minecraft:provides_banner_patterns", new(ProvidesBannerPatterns)},
		{"minecraft:provides_pottery_pattern", new(ProvidesPotteryPattern)},
		{"minecraft:provides_trim_material", new(ProvidesTrimMaterial)},
		{"minecraft:rabbit/variant", new(RabbitVariant)},
		{"minecraft:rarity", new(Rarity)},
		{"minecraft:recipes", new(Recipes)},
		{"minecraft:repair_cost", new(RepairCost)},
		{"minecraft:repairable", new(Repairable)},
		{"minecraft:salmon/size", new(SalmonSize)},
		{"minecraft:sheep/color", new(SheepColor)},
		{"minecraft:shulker/color", new(ShulkerColor)},
		{"minecraft:sign_text_back", new(SignTextBack)},
		{"minecraft:sign_text_front", new(SignTextFront)},
		{"minecraft:stored_enchantments", new(StoredEnchantments)},
		{"minecraft:sulfur_cube_content", new(SulfurCubeContent)},
		{"minecraft:suspicious_stew_effects", new(SuspiciousStewEffects)},
		{"minecraft:tool", new(Tool)},
		{"minecraft:tooltip_display", new(TooltipDisplay)},
		{"minecraft:tooltip_style", new(TooltipStyle)},
		{"minecraft:trim", new(Trim)},
		{"minecraft:tropical_fish/base_color", new(TropicalFishBaseColor)},
		{"minecraft:tropical_fish/pattern", new(TropicalFishPattern)},
		{"minecraft:tropical_fish/pattern_color", new(TropicalFishPatternColor)},
		{"minecraft:unbreakable", new(Unbreakable)},
		{"minecraft:use_cooldown", new(UseCooldown)},
		{"minecraft:use_effects", new(UseEffects)},
		{"minecraft:use_remainder", new(UseRemainder)},
		{"minecraft:villager/variant", new(VillagerVariant)},
		{"minecraft:villager_food", new(VillagerFood)},
		{"minecraft:waxed", new(Waxed)},
		{"minecraft:weapon", new(Weapon)},
		{"minecraft:wolf/collar", new(WolfCollar)},
		{"minecraft:wolf/sound_variant", new(WolfSoundVariant)},
		{"minecraft:wolf/variant", new(WolfVariant)},
		{"minecraft:writable_book_content", new(WritableBookContent)},
		{"minecraft:written_book_content", new(WrittenBookContent)},
		{"minecraft:zombie_nautilus/variant", new(ZombieNautilusVariant)},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			var a bytes.Buffer
			if _, err := c.zero.WriteTo(&a); err != nil {
				t.Fatalf("encode: %v", err)
			}
			if _, err := c.zero.ReadFrom(bytes.NewReader(a.Bytes())); err != nil {
				t.Fatalf("decode %x: %v", a.Bytes(), err)
			}
			var b bytes.Buffer
			if _, err := c.zero.WriteTo(&b); err != nil {
				t.Fatalf("re-encode: %v", err)
			}
			if !bytes.Equal(a.Bytes(), b.Bytes()) {
				t.Fatalf("round trip differs: %x vs %x", a.Bytes(), b.Bytes())
			}
			if c.zero.ID() != c.name {
				t.Fatalf("ID %q", c.zero.ID())
			}
		})
	}
}
