// Code generated by gen/gen_components.go from 26.3/packet_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/mj41/go-mc26/net/packet"
	"github.com/mj41/go-mc26/wire"
	"io"
)

// Compostable is the data component minecraft:compostable (Java Compostable).
type Compostable struct {
	Layers wire.Either[pk.Int, *pk.Int, pk.Identifier, *pk.Identifier]
}

func (v *Compostable) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Layers}.ReadFrom(r)
}

func (v Compostable) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Layers}.WriteTo(w)
}

// ID returns the registry name of the component.
func (Compostable) ID() string { return "minecraft:compostable" }

var _ DataComponent = (*Compostable)(nil)
