// Code generated by gen/gen_components.go from 26.2/packet_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/mj41/go-mc26/net/packet"
	"github.com/mj41/go-mc26/wire"
	"io"
)

// Consumable is the data component minecraft:consumable (Java Consumable).
type Consumable struct {
	ConsumeSeconds      pk.Float
	Animation           ItemUseAnimation
	Sound               wire.Holder[SoundEvent, *SoundEvent] // registry sound_event
	HasConsumeParticles pk.Boolean
	OnConsumeEffects    wire.List[ConsumeEffect, *ConsumeEffect]
}

func (v *Consumable) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.ConsumeSeconds, &v.Animation, &v.Sound, &v.HasConsumeParticles, &v.OnConsumeEffects}.ReadFrom(r)
}

func (v Consumable) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.ConsumeSeconds, v.Animation, v.Sound, v.HasConsumeParticles, v.OnConsumeEffects}.WriteTo(w)
}

// ID returns the registry name of the component.
func (Consumable) ID() string { return "minecraft:consumable" }

var _ DataComponent = (*Consumable)(nil)
