// Code generated by gen/gen_components.go from 26.2/packet_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/mj41/go-mc26/net/packet"
	"github.com/mj41/go-mc26/wire"
	"io"
)

// Container is the data component minecraft:container.
type Container struct {
	Value wire.List[pk.Option[ItemStackTemplate, *ItemStackTemplate], *pk.Option[ItemStackTemplate, *ItemStackTemplate]]
}

func (v *Container) ReadFrom(r io.Reader) (int64, error) { return v.Value.ReadFrom(r) }
func (v Container) WriteTo(w io.Writer) (int64, error)   { return v.Value.WriteTo(w) }

// ID returns the registry name of the component.
func (Container) ID() string { return "minecraft:container" }

var _ DataComponent = (*Container)(nil)
