// Code generated by gen/gen_components.go from 26.3/packet_schema.json; DO NOT EDIT.
package component

import (
	"github.com/mj41/go-mc26/wire"
	"io"
)

// ContainerLoot is the data component minecraft:container_loot.
type ContainerLoot struct{ Value wire.NBT }

func (v *ContainerLoot) ReadFrom(r io.Reader) (int64, error) { return v.Value.ReadFrom(r) }
func (v ContainerLoot) WriteTo(w io.Writer) (int64, error)   { return v.Value.WriteTo(w) }

// ID returns the registry name of the component.
func (ContainerLoot) ID() string { return "minecraft:container_loot" }

var _ DataComponent = (*ContainerLoot)(nil)
