// Code generated by gen/gen_components.go from 26.2/packet_schema.json; DO NOT EDIT.
package component

import (
	"github.com/mj41/go-mc26/wire"
	"io"
)

// CustomData is the data component minecraft:custom_data.
type CustomData struct{ Value wire.NBT }

func (v *CustomData) ReadFrom(r io.Reader) (int64, error) { return v.Value.ReadFrom(r) }
func (v CustomData) WriteTo(w io.Writer) (int64, error)   { return v.Value.WriteTo(w) }

// ID returns the registry name of the component.
func (CustomData) ID() string { return "minecraft:custom_data" }

var _ DataComponent = (*CustomData)(nil)
