// Code generated by gen/gen_components.go from 26.3/packet_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/mj41/go-mc26/net/packet"
	"github.com/mj41/go-mc26/wire"
	"io"
)

// CustomModelData is the data component minecraft:custom_model_data (Java CustomModelData).
type CustomModelData struct {
	Floats  wire.List[pk.Float, *pk.Float]
	Flags   wire.List[pk.Boolean, *pk.Boolean]
	Strings wire.List[pk.String, *pk.String]
	Colors  wire.List[pk.Int, *pk.Int]
}

func (v *CustomModelData) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Floats, &v.Flags, &v.Strings, &v.Colors}.ReadFrom(r)
}

func (v CustomModelData) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Floats, v.Flags, v.Strings, v.Colors}.WriteTo(w)
}

// ID returns the registry name of the component.
func (CustomModelData) ID() string { return "minecraft:custom_model_data" }

var _ DataComponent = (*CustomModelData)(nil)
