// Code generated by gen/gen_components.go from 26.2/packet_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/mj41/go-mc26/net/packet"
	"github.com/mj41/go-mc26/wire"
	"io"
)

// DamageResistant is the data component minecraft:damage_resistant (Java DamageResistant).
type DamageResistant struct {
	Types wire.IDSet // registry damage_type
}

func (v *DamageResistant) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Types}.ReadFrom(r)
}

func (v DamageResistant) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Types}.WriteTo(w)
}

// ID returns the registry name of the component.
func (DamageResistant) ID() string { return "minecraft:damage_resistant" }

var _ DataComponent = (*DamageResistant)(nil)
