// Code generated by gen/gen_components.go from 26.1/packet_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/mj41/go-mc26/net/packet"
	"io"
)

// DamageType is the data component minecraft:damage_type.
// Value: holder in damage_type.
type DamageType struct{ Value pk.VarInt }

func (v *DamageType) ReadFrom(r io.Reader) (int64, error) { return v.Value.ReadFrom(r) }
func (v DamageType) WriteTo(w io.Writer) (int64, error)   { return v.Value.WriteTo(w) }

// ID returns the registry name of the component.
func (DamageType) ID() string { return "minecraft:damage_type" }

var _ DataComponent = (*DamageType)(nil)
