// Code generated by gen/gen_components.go from 26.3/packet_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/mj41/go-mc26/net/packet"
	"github.com/mj41/go-mc26/wire"
	"io"
)

// DeathProtection is the data component minecraft:death_protection (Java DeathProtection).
type DeathProtection struct {
	DeathEffects wire.List[ConsumeEffect, *ConsumeEffect]
}

func (v *DeathProtection) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.DeathEffects}.ReadFrom(r)
}

func (v DeathProtection) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.DeathEffects}.WriteTo(w)
}

// ID returns the registry name of the component.
func (DeathProtection) ID() string { return "minecraft:death_protection" }

var _ DataComponent = (*DeathProtection)(nil)
