// Code generated by gen/gen_components.go from 26.3/packet_schema.json; DO NOT EDIT.
package component

import (
	"github.com/mj41/go-mc26/wire"
	"io"
)

// DebugStickState is the data component minecraft:debug_stick_state.
type DebugStickState struct{ Value wire.NBT }

func (v *DebugStickState) ReadFrom(r io.Reader) (int64, error) { return v.Value.ReadFrom(r) }
func (v DebugStickState) WriteTo(w io.Writer) (int64, error)   { return v.Value.WriteTo(w) }

// ID returns the registry name of the component.
func (DebugStickState) ID() string { return "minecraft:debug_stick_state" }

var _ DataComponent = (*DebugStickState)(nil)
