// Code generated by gen/gen_components.go from 26.3/packet_schema.json; DO NOT EDIT.
package component

import (
	"io"
)

// Dye is the data component minecraft:dye.
// Value: DyeColor.
type Dye struct{ Value DyeColor }

func (v *Dye) ReadFrom(r io.Reader) (int64, error) { return v.Value.ReadFrom(r) }
func (v Dye) WriteTo(w io.Writer) (int64, error)   { return v.Value.WriteTo(w) }

// ID returns the registry name of the component.
func (Dye) ID() string { return "minecraft:dye" }

var _ DataComponent = (*Dye)(nil)
