// Code generated by gen/gen_components.go from 26.1/packet_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/mj41/go-mc26/net/packet"
	"io"
)

// DyedColor is the data component minecraft:dyed_color (Java DyedItemColor).
type DyedColor struct {
	Rgb pk.Int
}

func (v *DyedColor) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Rgb}.ReadFrom(r)
}

func (v DyedColor) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Rgb}.WriteTo(w)
}

// ID returns the registry name of the component.
func (DyedColor) ID() string { return "minecraft:dyed_color" }

var _ DataComponent = (*DyedColor)(nil)
