// Code generated by gen/gen_components.go from 26.1/packet_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/mj41/go-mc26/net/packet"
	"github.com/mj41/go-mc26/wire"
	"io"
)

// Enchantments is the data component minecraft:enchantments (Java ItemEnchantments).
type Enchantments struct {
	Enchantments wire.Map[pk.VarInt, *pk.VarInt, pk.VarInt, *pk.VarInt]
}

func (v *Enchantments) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Enchantments}.ReadFrom(r)
}

func (v Enchantments) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Enchantments}.WriteTo(w)
}

// ID returns the registry name of the component.
func (Enchantments) ID() string { return "minecraft:enchantments" }

var _ DataComponent = (*Enchantments)(nil)
