// Code generated by gen/gen_components.go from 26.2/packet_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/mj41/go-mc26/net/packet"
	"github.com/mj41/go-mc26/wire"
	"io"
)

// EntityData is the data component minecraft:entity_data (Java TypedEntityData).
type EntityData struct {
	Type pk.VarInt // registry entity_type
	Tag  wire.NBT
}

func (v *EntityData) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Type, &v.Tag}.ReadFrom(r)
}

func (v EntityData) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Type, v.Tag}.WriteTo(w)
}

// ID returns the registry name of the component.
func (EntityData) ID() string { return "minecraft:entity_data" }

var _ DataComponent = (*EntityData)(nil)
