// Code generated by gen/gen_components.go from 26.2/packet_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/mj41/go-mc26/net/packet"
	"github.com/mj41/go-mc26/wire"
	"io"
)

// Equippable is the data component minecraft:equippable (Java Equippable).
type Equippable struct {
	Slot            EquipmentSlot
	EquipSound      wire.Holder[SoundEvent, *SoundEvent] // registry sound_event
	AssetID         pk.Option[pk.Identifier, *pk.Identifier]
	CameraOverlay   pk.Option[pk.Identifier, *pk.Identifier]
	AllowedEntities pk.Option[wire.IDSet, *wire.IDSet]
	Dispensable     pk.Boolean
	Swappable       pk.Boolean
	DamageOnHurt    pk.Boolean
	EquipOnInteract pk.Boolean
	CanBeSheared    pk.Boolean
	ShearingSound   wire.Holder[SoundEvent, *SoundEvent] // registry sound_event
}

func (v *Equippable) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Slot, &v.EquipSound, &v.AssetID, &v.CameraOverlay, &v.AllowedEntities, &v.Dispensable, &v.Swappable, &v.DamageOnHurt, &v.EquipOnInteract, &v.CanBeSheared, &v.ShearingSound}.ReadFrom(r)
}

func (v Equippable) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Slot, v.EquipSound, v.AssetID, v.CameraOverlay, v.AllowedEntities, v.Dispensable, v.Swappable, v.DamageOnHurt, v.EquipOnInteract, v.CanBeSheared, v.ShearingSound}.WriteTo(w)
}

// ID returns the registry name of the component.
func (Equippable) ID() string { return "minecraft:equippable" }

var _ DataComponent = (*Equippable)(nil)
