// Code generated by gen/gen_components.go from 26.3/packet_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/mj41/go-mc26/net/packet"
	"github.com/mj41/go-mc26/wire"
	"io"
)

// FireworkExplosion is the data component minecraft:firework_explosion (Java FireworkExplosion).
type FireworkExplosion struct {
	Shape      FireworkExplosionShape
	Colors     wire.List[pk.Int, *pk.Int]
	FadeColors wire.List[pk.Int, *pk.Int]
	HasTrail   pk.Boolean
	HasTwinkle pk.Boolean
}

func (v *FireworkExplosion) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Shape, &v.Colors, &v.FadeColors, &v.HasTrail, &v.HasTwinkle}.ReadFrom(r)
}

func (v FireworkExplosion) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Shape, v.Colors, v.FadeColors, v.HasTrail, v.HasTwinkle}.WriteTo(w)
}

// ID returns the registry name of the component.
func (FireworkExplosion) ID() string { return "minecraft:firework_explosion" }

var _ DataComponent = (*FireworkExplosion)(nil)
