// Code generated by gen/gen_components.go from 26.2/packet_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/mj41/go-mc26/net/packet"
	"github.com/mj41/go-mc26/wire"
	"io"
)

// Fireworks is the data component minecraft:fireworks (Java Fireworks).
type Fireworks struct {
	FlightDuration pk.VarInt
	Explosions     wire.List[FireworkExplosionRecord, *FireworkExplosionRecord]
}

func (v *Fireworks) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.FlightDuration, &v.Explosions}.ReadFrom(r)
}

func (v Fireworks) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.FlightDuration, v.Explosions}.WriteTo(w)
}

// ID returns the registry name of the component.
func (Fireworks) ID() string { return "minecraft:fireworks" }

var _ DataComponent = (*Fireworks)(nil)
