// Code generated by gen/gen_components.go from 26.2/packet_schema.json; DO NOT EDIT.
package component

// FoxVariant is the data component minecraft:fox/variant (Java Fox$Variant).
// ID returns the registry name of the component.
func (FoxVariant) ID() string { return "minecraft:fox/variant" }

var _ DataComponent = (*FoxVariant)(nil)
