// Code generated by gen/gen_componenthash.go from 26.1/component_hashes.json; DO NOT EDIT.

package component

import (
	"bytes"
	"encoding/base64"
	"testing"
)

// hashRegistries are the data-driven registries the samples' holders were
// written with, by name in id order.
var hashRegistries = map[string][]string{
	"minecraft:banner_pattern":          {"minecraft:base", "minecraft:border", "minecraft:bricks", "minecraft:circle", "minecraft:creeper", "minecraft:cross", "minecraft:curly_border", "minecraft:diagonal_left", "minecraft:diagonal_right", "minecraft:diagonal_up_left", "minecraft:diagonal_up_right", "minecraft:flow", "minecraft:flower", "minecraft:globe", "minecraft:gradient", "minecraft:gradient_up", "minecraft:guster", "minecraft:half_horizontal", "minecraft:half_horizontal_bottom", "minecraft:half_vertical", "minecraft:half_vertical_right", "minecraft:mojang", "minecraft:piglin", "minecraft:rhombus", "minecraft:skull", "minecraft:small_stripes", "minecraft:square_bottom_left", "minecraft:square_bottom_right", "minecraft:square_top_left", "minecraft:square_top_right", "minecraft:straight_cross", "minecraft:stripe_bottom", "minecraft:stripe_center", "minecraft:stripe_downleft", "minecraft:stripe_downright", "minecraft:stripe_left", "minecraft:stripe_middle", "minecraft:stripe_right", "minecraft:stripe_top", "minecraft:triangle_bottom", "minecraft:triangle_top", "minecraft:triangles_bottom", "minecraft:triangles_top"},
	"minecraft:cat_sound_variant":       {"minecraft:classic", "minecraft:royal"},
	"minecraft:cat_variant":             {"minecraft:all_black", "minecraft:black", "minecraft:british_shorthair", "minecraft:calico", "minecraft:jellie", "minecraft:persian", "minecraft:ragdoll", "minecraft:red", "minecraft:siamese", "minecraft:tabby", "minecraft:white"},
	"minecraft:chat_type":               {"minecraft:chat", "minecraft:emote_command", "minecraft:msg_command_incoming", "minecraft:msg_command_outgoing", "minecraft:say_command", "minecraft:team_msg_command_incoming", "minecraft:team_msg_command_outgoing"},
	"minecraft:chicken_sound_variant":   {"minecraft:classic", "minecraft:picky"},
	"minecraft:chicken_variant":         {"minecraft:cold", "minecraft:temperate", "minecraft:warm"},
	"minecraft:cow_sound_variant":       {"minecraft:classic", "minecraft:moody"},
	"minecraft:cow_variant":             {"minecraft:cold", "minecraft:temperate", "minecraft:warm"},
	"minecraft:damage_type":             {"minecraft:arrow", "minecraft:bad_respawn_point", "minecraft:cactus", "minecraft:campfire", "minecraft:cramming", "minecraft:dragon_breath", "minecraft:drown", "minecraft:dry_out", "minecraft:ender_pearl", "minecraft:explosion", "minecraft:fall", "minecraft:falling_anvil", "minecraft:falling_block", "minecraft:falling_stalactite", "minecraft:fireball", "minecraft:fireworks", "minecraft:fly_into_wall", "minecraft:freeze", "minecraft:generic", "minecraft:generic_kill", "minecraft:hot_floor", "minecraft:in_fire", "minecraft:in_wall", "minecraft:indirect_magic", "minecraft:lava", "minecraft:lightning_bolt", "minecraft:mace_smash", "minecraft:magic", "minecraft:mob_attack", "minecraft:mob_attack_no_aggro", "minecraft:mob_projectile", "minecraft:on_fire", "minecraft:out_of_world", "minecraft:outside_border", "minecraft:player_attack", "minecraft:player_explosion", "minecraft:sonic_boom", "minecraft:spear", "minecraft:spit", "minecraft:stalagmite", "minecraft:starve", "minecraft:sting", "minecraft:sweet_berry_bush", "minecraft:thorns", "minecraft:thrown", "minecraft:trident", "minecraft:unattributed_fireball", "minecraft:wind_charge", "minecraft:wither", "minecraft:wither_skull"},
	"minecraft:dialog":                  {"minecraft:custom_options", "minecraft:quick_actions", "minecraft:server_links"},
	"minecraft:dimension_type":          {"minecraft:overworld", "minecraft:overworld_caves", "minecraft:the_end", "minecraft:the_nether"},
	"minecraft:enchantment":             {"minecraft:aqua_affinity", "minecraft:bane_of_arthropods", "minecraft:binding_curse", "minecraft:blast_protection", "minecraft:breach", "minecraft:channeling", "minecraft:density", "minecraft:depth_strider", "minecraft:efficiency", "minecraft:feather_falling", "minecraft:fire_aspect", "minecraft:fire_protection", "minecraft:flame", "minecraft:fortune", "minecraft:frost_walker", "minecraft:impaling", "minecraft:infinity", "minecraft:knockback", "minecraft:looting", "minecraft:loyalty", "minecraft:luck_of_the_sea", "minecraft:lunge", "minecraft:lure", "minecraft:mending", "minecraft:multishot", "minecraft:piercing", "minecraft:power", "minecraft:projectile_protection", "minecraft:protection", "minecraft:punch", "minecraft:quick_charge", "minecraft:respiration", "minecraft:riptide", "minecraft:sharpness", "minecraft:silk_touch", "minecraft:smite", "minecraft:soul_speed", "minecraft:sweeping_edge", "minecraft:swift_sneak", "minecraft:thorns", "minecraft:unbreaking", "minecraft:vanishing_curse", "minecraft:wind_burst"},
	"minecraft:enchantment_provider":    {"minecraft:enderman_loot_drop", "minecraft:mob_spawn_equipment", "minecraft:pillager_spawn_crossbow", "minecraft:raid/pillager_post_wave_3", "minecraft:raid/pillager_post_wave_5", "minecraft:raid/vindicator", "minecraft:raid/vindicator_post_wave_5"},
	"minecraft:frog_variant":            {"minecraft:cold", "minecraft:temperate", "minecraft:warm"},
	"minecraft:instrument":              {"minecraft:admire_goat_horn", "minecraft:call_goat_horn", "minecraft:dream_goat_horn", "minecraft:feel_goat_horn", "minecraft:ponder_goat_horn", "minecraft:seek_goat_horn", "minecraft:sing_goat_horn", "minecraft:yearn_goat_horn"},
	"minecraft:jukebox_song":            {"minecraft:11", "minecraft:13", "minecraft:5", "minecraft:blocks", "minecraft:cat", "minecraft:chirp", "minecraft:creator", "minecraft:creator_music_box", "minecraft:far", "minecraft:lava_chicken", "minecraft:mall", "minecraft:mellohi", "minecraft:otherside", "minecraft:pigstep", "minecraft:precipice", "minecraft:relic", "minecraft:stal", "minecraft:strad", "minecraft:tears", "minecraft:wait", "minecraft:ward"},
	"minecraft:painting_variant":        {"minecraft:alban", "minecraft:aztec", "minecraft:aztec2", "minecraft:backyard", "minecraft:baroque", "minecraft:bomb", "minecraft:bouquet", "minecraft:burning_skull", "minecraft:bust", "minecraft:cavebird", "minecraft:changing", "minecraft:cotan", "minecraft:courbet", "minecraft:creebet", "minecraft:dennis", "minecraft:donkey_kong", "minecraft:earth", "minecraft:endboss", "minecraft:fern", "minecraft:fighters", "minecraft:finding", "minecraft:fire", "minecraft:graham", "minecraft:humble", "minecraft:kebab", "minecraft:lowmist", "minecraft:match", "minecraft:meditative", "minecraft:orb", "minecraft:owlemons", "minecraft:passage", "minecraft:pigscene", "minecraft:plant", "minecraft:pointer", "minecraft:pond", "minecraft:pool", "minecraft:prairie_ride", "minecraft:sea", "minecraft:skeleton", "minecraft:skull_and_roses", "minecraft:stage", "minecraft:sunflowers", "minecraft:sunset", "minecraft:tides", "minecraft:unpacked", "minecraft:void", "minecraft:wanderer", "minecraft:wasteland", "minecraft:water", "minecraft:wind", "minecraft:wither"},
	"minecraft:pig_sound_variant":       {"minecraft:big", "minecraft:classic", "minecraft:mini"},
	"minecraft:pig_variant":             {"minecraft:cold", "minecraft:temperate", "minecraft:warm"},
	"minecraft:timeline":                {"minecraft:day", "minecraft:early_game", "minecraft:moon", "minecraft:villager_schedule"},
	"minecraft:trim_material":           {"minecraft:amethyst", "minecraft:copper", "minecraft:diamond", "minecraft:emerald", "minecraft:gold", "minecraft:iron", "minecraft:lapis", "minecraft:netherite", "minecraft:quartz", "minecraft:redstone", "minecraft:resin"},
	"minecraft:trim_pattern":            {"minecraft:bolt", "minecraft:coast", "minecraft:dune", "minecraft:eye", "minecraft:flow", "minecraft:host", "minecraft:raiser", "minecraft:rib", "minecraft:sentry", "minecraft:shaper", "minecraft:silence", "minecraft:snout", "minecraft:spire", "minecraft:tide", "minecraft:vex", "minecraft:ward", "minecraft:wayfinder", "minecraft:wild"},
	"minecraft:wolf_sound_variant":      {"minecraft:angry", "minecraft:big", "minecraft:classic", "minecraft:cute", "minecraft:grumpy", "minecraft:puglin", "minecraft:sad"},
	"minecraft:wolf_variant":            {"minecraft:ashen", "minecraft:black", "minecraft:chestnut", "minecraft:pale", "minecraft:rusty", "minecraft:snowy", "minecraft:spotted", "minecraft:striped", "minecraft:woods"},
	"minecraft:world_clock":             {"minecraft:overworld", "minecraft:the_end"},
	"minecraft:worldgen/biome":          {"minecraft:badlands", "minecraft:bamboo_jungle", "minecraft:basalt_deltas", "minecraft:beach", "minecraft:birch_forest", "minecraft:cherry_grove", "minecraft:cold_ocean", "minecraft:crimson_forest", "minecraft:dark_forest", "minecraft:deep_cold_ocean", "minecraft:deep_dark", "minecraft:deep_frozen_ocean", "minecraft:deep_lukewarm_ocean", "minecraft:deep_ocean", "minecraft:desert", "minecraft:dripstone_caves", "minecraft:end_barrens", "minecraft:end_highlands", "minecraft:end_midlands", "minecraft:eroded_badlands", "minecraft:flower_forest", "minecraft:forest", "minecraft:frozen_ocean", "minecraft:frozen_peaks", "minecraft:frozen_river", "minecraft:grove", "minecraft:ice_spikes", "minecraft:jagged_peaks", "minecraft:jungle", "minecraft:lukewarm_ocean", "minecraft:lush_caves", "minecraft:mangrove_swamp", "minecraft:meadow", "minecraft:mushroom_fields", "minecraft:nether_wastes", "minecraft:ocean", "minecraft:old_growth_birch_forest", "minecraft:old_growth_pine_taiga", "minecraft:old_growth_spruce_taiga", "minecraft:pale_garden", "minecraft:plains", "minecraft:river", "minecraft:savanna", "minecraft:savanna_plateau", "minecraft:small_end_islands", "minecraft:snowy_beach", "minecraft:snowy_plains", "minecraft:snowy_slopes", "minecraft:snowy_taiga", "minecraft:soul_sand_valley", "minecraft:sparse_jungle", "minecraft:stony_peaks", "minecraft:stony_shore", "minecraft:sunflower_plains", "minecraft:swamp", "minecraft:taiga", "minecraft:the_end", "minecraft:the_void", "minecraft:warm_ocean", "minecraft:warped_forest", "minecraft:windswept_forest", "minecraft:windswept_gravelly_hills", "minecraft:windswept_hills", "minecraft:windswept_savanna", "minecraft:wooded_badlands"},
	"minecraft:zombie_nautilus_variant": {"minecraft:temperate", "minecraft:warm"},
}

// hashSamples are components of stacks a give command makes, in their network
// encoding (Typed), with the hash a vanilla client computes for each.
var hashSamples = []struct {
	stack, component, wire string
	hash                   int32
}{
	{"diamond_pickaxe[damage=7,repair_cost=2,unbreakable={},enchantment_glint_override=true]", "minecraft:damage", "Awc=", -1726626450},
	{"diamond_pickaxe[damage=7,repair_cost=2,unbreakable={},enchantment_glint_override=true]", "minecraft:repair_cost", "EwI=", 1064459813},
	{"diamond_pickaxe[damage=7,repair_cost=2,unbreakable={},enchantment_glint_override=true]", "minecraft:unbreakable", "BA==", -982207288},
	{"diamond_pickaxe[damage=7,repair_cost=2,unbreakable={},enchantment_glint_override=true]", "minecraft:enchantment_glint_override", "FQE=", -1019818302},
	{"diamond_pickaxe[enchantments={\"minecraft:efficiency\":4,\"minecraft:unbreaking\":3}]", "minecraft:enchantments", "DQIoAwgE", 1851319040},
	{"enchanted_book[stored_enchantments={\"minecraft:sharpness\":5}]", "minecraft:stored_enchantments", "KgEhBQ==", 1722377199},
	{"diamond_sword[custom_name=\"Excalibur\",lore=[\"first line\",{text:\"red\",color:\"red\",italic:false}]]", "minecraft:custom_name", "BggACUV4Y2FsaWJ1cg==", 1552767058},
	{"diamond_sword[custom_name=\"Excalibur\",lore=[\"first line\",{text:\"red\",color:\"red\",italic:false}]]", "minecraft:lore", "CwIIAApmaXJzdCBsaW5lCggABWNvbG9yAANyZWQIAAR0ZXh0AANyZWQBAAZpdGFsaWMAAA==", -1801439824},
	{"diamond_sword[custom_name={text:\"Bold\",bold:true,extra:[\" and \",{translate:\"item.minecraft.stick\"}]}]", "minecraft:custom_name", "BgoJAAVleHRyYQoAAAACCAAAAAUgYW5kIAAIAAl0cmFuc2xhdGUAFGl0ZW0ubWluZWNyYWZ0LnN0aWNrAAgABHRleHQABEJvbGQBAARib2xkAQA=", -2005479663},
	{"diamond_sword[item_name={translate:\"item.minecraft.stick\",with:[\"x\",{text:\"y\",underlined:true}]}]", "minecraft:item_name", "CQoJAAR3aXRoCgAAAAIIAAAAAXgAAQAKdW5kZXJsaW5lZAEIAAR0ZXh0AAF5AAgACXRyYW5zbGF0ZQAUaXRlbS5taW5lY3JhZnQuc3RpY2sA", 1906354621},
	{"diamond_sword[rarity=\"epic\",max_stack_size=4,max_damage=10]", "minecraft:rarity", "DAM=", -292715907},
	{"diamond_sword[rarity=\"epic\",max_stack_size=4,max_damage=10]", "minecraft:max_stack_size", "AQQ=", -80262057},
	{"diamond_sword[rarity=\"epic\",max_stack_size=4,max_damage=10]", "minecraft:max_damage", "Ago=", -919192125},
	{"diamond_sword[tooltip_display={hide_tooltip:false,hidden_components:[\"minecraft:enchantments\",\"minecraft:damage\"]}]", "minecraft:tooltip_display", "EgACDQM=", 805869483},
	{"diamond_sword[custom_data={a:1b,b:\"s\",c:[I;1,2],d:{e:2.5d,f:[1.0f,2.0f]},g:3L,h:4s}]", "minecraft:custom_data", "AAoBAAFhAQgAAWIAAXMLAAFjAAAAAgAAAAEAAAACCgABZAYAAWVABAAAAAAAAAkAAWYFAAAAAj+AAABAAAAAAAQAAWcAAAAAAAAAAwIAAWgABAA=", -1431263309},
	{"written_book[written_book_content={title:\"T\",author:\"Robot\",pages:[\"one\",\"two\"]}]", "minecraft:written_book_content", "NwFUAAVSb2JvdAACCAADb25lAAgAA3R3bwAA", 1345259746},
	{"written_book[written_book_content={title:{raw:\"T\",filtered:\"t\"},author:\"Robot\",generation:2,resolved:true,pages:[{raw:\"one\",filtered:\"1\"}]}]", "minecraft:written_book_content", "NwFUAQF0BVJvYm90AgEIAANvbmUBCAABMQE=", 219928326},
	{"writable_book[writable_book_content={pages:[\"draft\",{raw:\"a\",filtered:\"b\"}]}]", "minecraft:writable_book_content", "NgIFZHJhZnQAAWEBAWI=", 848676656},
	{"firework_rocket[fireworks={flight_duration:2,explosions:[{shape:\"star\",colors:[I;16711680],has_trail:true}]}]", "minecraft:fireworks", "RQIBAgEA/wAAAAEA", 1870020809},
	{"firework_rocket[fireworks={flight_duration:1,explosions:[{shape:\"burst\",colors:[I;1,2],fade_colors:[I;3],has_twinkle:true}]}]", "minecraft:fireworks", "RQEBBAIAAAABAAAAAgEAAAADAAE=", -1339755266},
	{"firework_star[firework_explosion={shape:\"large_ball\",colors:[I;255]}]", "minecraft:firework_explosion", "RAEBAAAA/wAAAA==", 483758278},
	{"potion[potion_contents={potion:\"minecraft:strength\"}]", "minecraft:potion_contents", "MwEiAAAA", -1285948701},
	{"potion[potion_contents={custom_color:255,custom_effects:[{id:\"minecraft:speed\",amplifier:1b,duration:200,show_particles:false}],custom_name:\"fast\"}]", "minecraft:potion_contents", "MwABAAAA/wEAAcgBAAAAAAEEZmFzdA==", -448207497},
	{"tipped_arrow[potion_contents={potion:\"minecraft:swiftness\"}]", "minecraft:potion_contents", "MwENAAAA", -1164789092},
	{"leather_chestplate[dyed_color=16711680]", "minecraft:dyed_color", "LAD/AAA=", 603347239},
	{"iron_chestplate[trim={material:\"minecraft:gold\",pattern:\"minecraft:coast\"}]", "minecraft:trim", "OAUC", -1717879411},
	{"player_head[profile={name:\"Robot\"}]", "minecraft:profile", "RgABBVJvYm90AAAAAAAA", 1799696278},
	{"player_head[profile={name:\"Robot\",id:[I;1,2,3,4]}]", "minecraft:profile", "RgEAAAABAAAAAgAAAAMAAAAEBVJvYm90AAAAAAA=", 1103543631},
	{"white_banner[banner_patterns=[{pattern:\"minecraft:stripe_top\",color:\"red\"},{pattern:\"minecraft:border\",color:\"blue\"}]]", "minecraft:banner_patterns", "SAInDgIL", 1820218543},
	{"shield[base_color=\"red\"]", "minecraft:base_color", "SQ4=", -1939582294},
	{"bundle[bundle_contents=[{id:\"minecraft:stone\",count:2},{id:\"minecraft:diamond_sword\",components:{\"minecraft:damage\":3}}]]", "minecraft:bundle_contents", "MgIBAgAAqQcBAQADAw==", 865414495},
	{"shulker_box[container=[{slot:0,item:{id:\"minecraft:dirt\",count:3}},{slot:5,item:{id:\"minecraft:stick\"}}]]", "minecraft:container", "SwYBHAMAAAAAAAABswcBAAA=", -1090433852},
	{"crossbow[charged_projectiles=[{id:\"minecraft:arrow\"}]]", "minecraft:charged_projectiles", "MQGABwEAAA==", 1401819792},
	{"goat_horn[instrument=\"minecraft:ponder_goat_horn\"]", "minecraft:instrument", "PQU=", -1123313158},
	{"compass[lodestone_tracker={target:{pos:[I;0,64,0],dimension:\"minecraft:overworld\"},tracked:false}]", "minecraft:lodestone_tracker", "QwETbWluZWNyYWZ0Om92ZXJ3b3JsZAAAAAAAAABAAA==", -1922909851},
	{"compass[lodestone_tracker={}]", "minecraft:lodestone_tracker", "QwAB", -982207288},
	{"suspicious_stew[suspicious_stew_effects=[{id:\"minecraft:speed\",duration:100},{id:\"minecraft:night_vision\"}]]", "minecraft:suspicious_stew_effects", "NQIAZA+gAQ==", 307644502},
	{"filled_map[map_id=3]", "minecraft:map_id", "LgM=", -499649379},
	{"golden_apple[rarity=\"rare\"]", "minecraft:rarity", "DAI=", -1420566726},
	{"diamond_sword[attribute_modifiers=[{type:\"minecraft:attack_damage\",id:\"minecraft:x\",amount:3.0d,operation:\"add_value\",slot:\"mainhand\"}]]", "minecraft:attribute_modifiers", "EAECC21pbmVjcmFmdDp4QAgAAAAAAAAAAQA=", -2064243466},
	{"stone[custom_model_data={floats:[1.5f],flags:[true],strings:[\"a\"],colors:[I;7]}]", "minecraft:custom_model_data", "EQE/wAAAAQEBAWEBAAAABw==", -1668267434},
}

func TestHashSamples(t *testing.T) {
	names := func(registry string, id int32) (string, bool) {
		if l, ok := hashRegistries[registry]; ok {
			if id < 0 || int(id) >= len(l) {
				return "", false
			}
			return l[id], true
		}
		return StaticNames(registry, id)
	}
	for _, s := range hashSamples {
		b, err := base64.StdEncoding.DecodeString(s.wire)
		if err != nil {
			t.Fatal(err)
		}
		var c Typed
		r := bytes.NewReader(b)
		if _, err := c.ReadFrom(r); err != nil {
			t.Errorf("%s %s: decoding: %v", s.stack, s.component, err)
			continue
		}
		if r.Len() != 0 {
			t.Errorf("%s %s: %d bytes left after decoding", s.stack, s.component, r.Len())
			continue
		}
		h, ok := HashWith(c.Value, names)
		if !ok {
			t.Errorf("%s %s: not hashed", s.stack, s.component)
		} else if h != s.hash {
			t.Errorf("%s %s: hash %d, the game's %d", s.stack, s.component, h, s.hash)
		}
	}
}
