// Code generated by gen/gen_components.go from 26.2/packet_schema.json; DO NOT EDIT.
package component

// HorseVariant is the data component minecraft:horse/variant (Java Variant).
// ID returns the registry name of the component.
func (HorseVariant) ID() string { return "minecraft:horse/variant" }

var _ DataComponent = (*HorseVariant)(nil)
