// Code generated by gen/gen_components.go from 26.2/packet_schema.json; DO NOT EDIT.
package component

import (
	"github.com/mj41/go-mc26/wire"
	"io"
)

// Instrument is the data component minecraft:instrument.
// Value: registry instrument.
type Instrument struct {
	Value wire.Holder[InstrumentRecord, *InstrumentRecord]
}

func (v *Instrument) ReadFrom(r io.Reader) (int64, error) { return v.Value.ReadFrom(r) }
func (v Instrument) WriteTo(w io.Writer) (int64, error)   { return v.Value.WriteTo(w) }

// ID returns the registry name of the component.
func (Instrument) ID() string { return "minecraft:instrument" }

var _ DataComponent = (*Instrument)(nil)
