// Code generated by gen/gen_components.go from 26.1/packet_schema.json; DO NOT EDIT.
package component

import (
	"github.com/mj41/go-mc26/wire"
	"io"
)

// IntangibleProjectile is the data component minecraft:intangible_projectile.
type IntangibleProjectile struct{ Value wire.NBT }

func (v *IntangibleProjectile) ReadFrom(r io.Reader) (int64, error) { return v.Value.ReadFrom(r) }
func (v IntangibleProjectile) WriteTo(w io.Writer) (int64, error)   { return v.Value.WriteTo(w) }

// ID returns the registry name of the component.
func (IntangibleProjectile) ID() string { return "minecraft:intangible_projectile" }

var _ DataComponent = (*IntangibleProjectile)(nil)
