// Code generated by gen/gen_components.go from 26.3/packet_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/mj41/go-mc26/net/packet"
	"io"
)

// InteractAnimation is the data component minecraft:interact_animation (Java SwingAnimation).
type InteractAnimation struct {
	Type     SwingAnimationType
	Duration pk.VarInt
}

func (v *InteractAnimation) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Type, &v.Duration}.ReadFrom(r)
}

func (v InteractAnimation) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Type, v.Duration}.WriteTo(w)
}

// ID returns the registry name of the component.
func (InteractAnimation) ID() string { return "minecraft:interact_animation" }

var _ DataComponent = (*InteractAnimation)(nil)
