// Code generated by gen/gen_components.go from 26.1/packet_schema.json; DO NOT EDIT.
package component

import (
	"github.com/mj41/go-mc26/chat"
	"io"
)

// ItemName is the data component minecraft:item_name.
type ItemName struct{ Value chat.Message }

func (v *ItemName) ReadFrom(r io.Reader) (int64, error) { return v.Value.ReadFrom(r) }
func (v ItemName) WriteTo(w io.Writer) (int64, error)   { return v.Value.WriteTo(w) }

// ID returns the registry name of the component.
func (ItemName) ID() string { return "minecraft:item_name" }

var _ DataComponent = (*ItemName)(nil)
