// Code generated by gen/gen_components.go from 26.3/packet_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/mj41/go-mc26/net/packet"
	"github.com/mj41/go-mc26/wire"
	"io"
)

// JukeboxPlayable is the data component minecraft:jukebox_playable (Java JukeboxPlayable).
type JukeboxPlayable struct {
	Song wire.Holder[JukeboxSong, *JukeboxSong] // registry jukebox_song
}

func (v *JukeboxPlayable) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Song}.ReadFrom(r)
}

func (v JukeboxPlayable) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Song}.WriteTo(w)
}

// ID returns the registry name of the component.
func (JukeboxPlayable) ID() string { return "minecraft:jukebox_playable" }

var _ DataComponent = (*JukeboxPlayable)(nil)
