// Code generated by gen/gen_components.go from 26.2/packet_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/mj41/go-mc26/net/packet"
	"github.com/mj41/go-mc26/wire"
	"io"
)

// KineticWeapon is the data component minecraft:kinetic_weapon (Java KineticWeapon).
type KineticWeapon struct {
	ContactCooldownTicks pk.VarInt
	DelayTicks           pk.VarInt
	DismountConditions   pk.Option[KineticWeaponCondition, *KineticWeaponCondition]
	KnockbackConditions  pk.Option[KineticWeaponCondition, *KineticWeaponCondition]
	DamageConditions     pk.Option[KineticWeaponCondition, *KineticWeaponCondition]
	ForwardMovement      pk.Float
	DamageMultiplier     pk.Float
	Sound                pk.Option[wire.Holder[SoundEvent, *SoundEvent], *wire.Holder[SoundEvent, *SoundEvent]]
	HitSound             pk.Option[wire.Holder[SoundEvent, *SoundEvent], *wire.Holder[SoundEvent, *SoundEvent]]
}

func (v *KineticWeapon) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.ContactCooldownTicks, &v.DelayTicks, &v.DismountConditions, &v.KnockbackConditions, &v.DamageConditions, &v.ForwardMovement, &v.DamageMultiplier, &v.Sound, &v.HitSound}.ReadFrom(r)
}

func (v KineticWeapon) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.ContactCooldownTicks, v.DelayTicks, v.DismountConditions, v.KnockbackConditions, v.DamageConditions, v.ForwardMovement, v.DamageMultiplier, v.Sound, v.HitSound}.WriteTo(w)
}

// ID returns the registry name of the component.
func (KineticWeapon) ID() string { return "minecraft:kinetic_weapon" }

var _ DataComponent = (*KineticWeapon)(nil)
