// Code generated by gen/gen_components.go from 26.3/packet_schema.json; DO NOT EDIT.
package component

import (
	"github.com/mj41/go-mc26/wire"
	"io"
)

// Lock is the data component minecraft:lock.
type Lock struct{ Value wire.NBT }

func (v *Lock) ReadFrom(r io.Reader) (int64, error) { return v.Value.ReadFrom(r) }
func (v Lock) WriteTo(w io.Writer) (int64, error)   { return v.Value.WriteTo(w) }

// ID returns the registry name of the component.
func (Lock) ID() string { return "minecraft:lock" }

var _ DataComponent = (*Lock)(nil)
