// Code generated by gen/gen_components.go from 26.2/packet_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/mj41/go-mc26/net/packet"
	"github.com/mj41/go-mc26/wire"
	"io"
)

// LodestoneTracker is the data component minecraft:lodestone_tracker (Java LodestoneTracker).
type LodestoneTracker struct {
	Target  pk.Option[wire.GlobalPos, *wire.GlobalPos]
	Tracked pk.Boolean
}

func (v *LodestoneTracker) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Target, &v.Tracked}.ReadFrom(r)
}

func (v LodestoneTracker) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Target, v.Tracked}.WriteTo(w)
}

// ID returns the registry name of the component.
func (LodestoneTracker) ID() string { return "minecraft:lodestone_tracker" }

var _ DataComponent = (*LodestoneTracker)(nil)
