// Code generated by gen/gen_components.go from 26.3/packet_schema.json; DO NOT EDIT.
package component

import (
	"github.com/mj41/go-mc26/chat"
	"github.com/mj41/go-mc26/wire"
	"io"
)

// Lore is the data component minecraft:lore.
type Lore struct {
	Value wire.List[chat.Message, *chat.Message]
}

func (v *Lore) ReadFrom(r io.Reader) (int64, error) { return v.Value.ReadFrom(r) }
func (v Lore) WriteTo(w io.Writer) (int64, error)   { return v.Value.WriteTo(w) }

// ID returns the registry name of the component.
func (Lore) ID() string { return "minecraft:lore" }

var _ DataComponent = (*Lore)(nil)
