// Code generated by gen/gen_components.go from 26.1/packet_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/mj41/go-mc26/net/packet"
	"io"
)

// MapColor is the data component minecraft:map_color.
type MapColor struct{ Value pk.Int }

func (v *MapColor) ReadFrom(r io.Reader) (int64, error) { return v.Value.ReadFrom(r) }
func (v MapColor) WriteTo(w io.Writer) (int64, error)   { return v.Value.WriteTo(w) }

// ID returns the registry name of the component.
func (MapColor) ID() string { return "minecraft:map_color" }

var _ DataComponent = (*MapColor)(nil)
