// Code generated by gen/gen_components.go from 26.3/packet_schema.json; DO NOT EDIT.
package component

import (
	"github.com/mj41/go-mc26/wire"
	"io"
)

// MapDecorations is the data component minecraft:map_decorations.
type MapDecorations struct{ Value wire.NBT }

func (v *MapDecorations) ReadFrom(r io.Reader) (int64, error) { return v.Value.ReadFrom(r) }
func (v MapDecorations) WriteTo(w io.Writer) (int64, error)   { return v.Value.WriteTo(w) }

// ID returns the registry name of the component.
func (MapDecorations) ID() string { return "minecraft:map_decorations" }

var _ DataComponent = (*MapDecorations)(nil)
