// Code generated by gen/gen_components.go from 26.2/packet_schema.json; DO NOT EDIT.
package component

// MapPostProcessing is the data component minecraft:map_post_processing (Java MapPostProcessing).
// ID returns the registry name of the component.
func (MapPostProcessing) ID() string { return "minecraft:map_post_processing" }

var _ DataComponent = (*MapPostProcessing)(nil)
