// Code generated by gen/gen_components.go from 26.1/packet_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/mj41/go-mc26/net/packet"
	"io"
)

// MaxDamage is the data component minecraft:max_damage.
type MaxDamage struct{ Value pk.VarInt }

func (v *MaxDamage) ReadFrom(r io.Reader) (int64, error) { return v.Value.ReadFrom(r) }
func (v MaxDamage) WriteTo(w io.Writer) (int64, error)   { return v.Value.WriteTo(w) }

// ID returns the registry name of the component.
func (MaxDamage) ID() string { return "minecraft:max_damage" }

var _ DataComponent = (*MaxDamage)(nil)
