// Code generated by gen/gen_components.go from 26.2/packet_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/mj41/go-mc26/net/packet"
	"io"
)

// MaxStackSize is the data component minecraft:max_stack_size.
type MaxStackSize struct{ Value pk.VarInt }

func (v *MaxStackSize) ReadFrom(r io.Reader) (int64, error) { return v.Value.ReadFrom(r) }
func (v MaxStackSize) WriteTo(w io.Writer) (int64, error)   { return v.Value.WriteTo(w) }

// ID returns the registry name of the component.
func (MaxStackSize) ID() string { return "minecraft:max_stack_size" }

var _ DataComponent = (*MaxStackSize)(nil)
