// Code generated by gen/gen_components.go from 26.1/packet_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/mj41/go-mc26/net/packet"
	"io"
)

// MinimumAttackCharge is the data component minecraft:minimum_attack_charge.
type MinimumAttackCharge struct{ Value pk.Float }

func (v *MinimumAttackCharge) ReadFrom(r io.Reader) (int64, error) { return v.Value.ReadFrom(r) }
func (v MinimumAttackCharge) WriteTo(w io.Writer) (int64, error)   { return v.Value.WriteTo(w) }

// ID returns the registry name of the component.
func (MinimumAttackCharge) ID() string { return "minecraft:minimum_attack_charge" }

var _ DataComponent = (*MinimumAttackCharge)(nil)
