// Code generated by gen/gen_components.go from 26.2/packet_schema.json; DO NOT EDIT.
package component

// MooshroomVariant is the data component minecraft:mooshroom/variant (Java MushroomCow$Variant).
// ID returns the registry name of the component.
func (MooshroomVariant) ID() string { return "minecraft:mooshroom/variant" }

var _ DataComponent = (*MooshroomVariant)(nil)
