// Code generated by gen/gen_components.go from 26.1/packet_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/mj41/go-mc26/net/packet"
	"io"
)

// NoteBlockSound is the data component minecraft:note_block_sound.
type NoteBlockSound struct{ Value pk.Identifier }

func (v *NoteBlockSound) ReadFrom(r io.Reader) (int64, error) { return v.Value.ReadFrom(r) }
func (v NoteBlockSound) WriteTo(w io.Writer) (int64, error)   { return v.Value.WriteTo(w) }

// ID returns the registry name of the component.
func (NoteBlockSound) ID() string { return "minecraft:note_block_sound" }

var _ DataComponent = (*NoteBlockSound)(nil)
