// Code generated by gen/gen_components.go from 26.1/packet_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/mj41/go-mc26/net/packet"
	"io"
)

// OminousBottleAmplifier is the data component minecraft:ominous_bottle_amplifier (Java OminousBottleAmplifier).
type OminousBottleAmplifier struct {
	Value pk.VarInt
}

func (v *OminousBottleAmplifier) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Value}.ReadFrom(r)
}

func (v OminousBottleAmplifier) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Value}.WriteTo(w)
}

// ID returns the registry name of the component.
func (OminousBottleAmplifier) ID() string { return "minecraft:ominous_bottle_amplifier" }

var _ DataComponent = (*OminousBottleAmplifier)(nil)
