// Code generated by gen/gen_components.go from 26.3/packet_schema.json; DO NOT EDIT.
package component

import (
	"github.com/mj41/go-mc26/wire"
	"io"
)

// PaintingVariant is the data component minecraft:painting/variant.
// Value: registry painting_variant.
type PaintingVariant struct {
	Value wire.Holder[PaintingVariantRecord, *PaintingVariantRecord]
}

func (v *PaintingVariant) ReadFrom(r io.Reader) (int64, error) { return v.Value.ReadFrom(r) }
func (v PaintingVariant) WriteTo(w io.Writer) (int64, error)   { return v.Value.WriteTo(w) }

// ID returns the registry name of the component.
func (PaintingVariant) ID() string { return "minecraft:painting/variant" }

var _ DataComponent = (*PaintingVariant)(nil)
