// Code generated by gen/gen_components.go from 26.2/packet_schema.json; DO NOT EDIT.
package component

// ParrotVariant is the data component minecraft:parrot/variant (Java Parrot$Variant).
// ID returns the registry name of the component.
func (ParrotVariant) ID() string { return "minecraft:parrot/variant" }

var _ DataComponent = (*ParrotVariant)(nil)
