// Code generated by gen/gen_components.go from 26.1/packet_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/mj41/go-mc26/net/packet"
	"github.com/mj41/go-mc26/wire"
	"io"
)

// PiercingWeapon is the data component minecraft:piercing_weapon (Java PiercingWeapon).
type PiercingWeapon struct {
	DealsKnockback pk.Boolean
	Dismounts      pk.Boolean
	Sound          pk.Option[wire.Holder[SoundEvent, *SoundEvent], *wire.Holder[SoundEvent, *SoundEvent]]
	HitSound       pk.Option[wire.Holder[SoundEvent, *SoundEvent], *wire.Holder[SoundEvent, *SoundEvent]]
}

func (v *PiercingWeapon) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.DealsKnockback, &v.Dismounts, &v.Sound, &v.HitSound}.ReadFrom(r)
}

func (v PiercingWeapon) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.DealsKnockback, v.Dismounts, v.Sound, v.HitSound}.WriteTo(w)
}

// ID returns the registry name of the component.
func (PiercingWeapon) ID() string { return "minecraft:piercing_weapon" }

var _ DataComponent = (*PiercingWeapon)(nil)
