// Code generated by gen/gen_components.go from 26.3/packet_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/mj41/go-mc26/net/packet"
	"io"
)

// PotDecorations is the data component minecraft:pot_decorations (Java PotDecorations).
type PotDecorations struct {
	Back  pk.Option[ItemStackTemplate, *ItemStackTemplate]
	Left  pk.Option[ItemStackTemplate, *ItemStackTemplate]
	Right pk.Option[ItemStackTemplate, *ItemStackTemplate]
	Front pk.Option[ItemStackTemplate, *ItemStackTemplate]
}

func (v *PotDecorations) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Back, &v.Left, &v.Right, &v.Front}.ReadFrom(r)
}

func (v PotDecorations) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Back, v.Left, v.Right, v.Front}.WriteTo(w)
}

// ID returns the registry name of the component.
func (PotDecorations) ID() string { return "minecraft:pot_decorations" }

var _ DataComponent = (*PotDecorations)(nil)
