// Code generated by gen/gen_components.go from 26.3/packet_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/mj41/go-mc26/net/packet"
	"io"
)

// PotionDurationScale is the data component minecraft:potion_duration_scale.
type PotionDurationScale struct{ Value pk.Float }

func (v *PotionDurationScale) ReadFrom(r io.Reader) (int64, error) { return v.Value.ReadFrom(r) }
func (v PotionDurationScale) WriteTo(w io.Writer) (int64, error)   { return v.Value.WriteTo(w) }

// ID returns the registry name of the component.
func (PotionDurationScale) ID() string { return "minecraft:potion_duration_scale" }

var _ DataComponent = (*PotionDurationScale)(nil)
