// Code generated by gen/gen_components.go from 26.1/packet_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/mj41/go-mc26/net/packet"
	"github.com/mj41/go-mc26/wire"
	"io"
)

// Profile is the data component minecraft:profile (Java ResolvableProfile).
type Profile struct {
	Unpack    wire.Either[wire.GameProfile, *wire.GameProfile, ResolvableProfilePartial, *ResolvableProfilePartial]
	SkinPatch PlayerSkinPatch
}

func (v *Profile) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Unpack, &v.SkinPatch}.ReadFrom(r)
}

func (v Profile) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Unpack, v.SkinPatch}.WriteTo(w)
}

// ID returns the registry name of the component.
func (Profile) ID() string { return "minecraft:profile" }

var _ DataComponent = (*Profile)(nil)
