// Code generated by gen/gen_components.go from 26.3/packet_schema.json; DO NOT EDIT.
package component

import (
	"github.com/mj41/go-mc26/wire"
	"io"
)

// ProvidesBannerPatterns is the data component minecraft:provides_banner_patterns.
// Value: registry banner_pattern.
type ProvidesBannerPatterns struct{ Value wire.IDSet }

func (v *ProvidesBannerPatterns) ReadFrom(r io.Reader) (int64, error) { return v.Value.ReadFrom(r) }
func (v ProvidesBannerPatterns) WriteTo(w io.Writer) (int64, error)   { return v.Value.WriteTo(w) }

// ID returns the registry name of the component.
func (ProvidesBannerPatterns) ID() string { return "minecraft:provides_banner_patterns" }

var _ DataComponent = (*ProvidesBannerPatterns)(nil)
