// Code generated by gen/gen_components.go from 26.3/packet_schema.json; DO NOT EDIT.
package component

import (
	"github.com/mj41/go-mc26/wire"
	"io"
)

// ProvidesTrimMaterial is the data component minecraft:provides_trim_material.
// Value: registry trim_material.
type ProvidesTrimMaterial struct {
	Value wire.Holder[TrimMaterial, *TrimMaterial]
}

func (v *ProvidesTrimMaterial) ReadFrom(r io.Reader) (int64, error) { return v.Value.ReadFrom(r) }
func (v ProvidesTrimMaterial) WriteTo(w io.Writer) (int64, error)   { return v.Value.WriteTo(w) }

// ID returns the registry name of the component.
func (ProvidesTrimMaterial) ID() string { return "minecraft:provides_trim_material" }

var _ DataComponent = (*ProvidesTrimMaterial)(nil)
