// Code generated by gen/gen_components.go from 26.2/packet_schema.json; DO NOT EDIT.
package component

// Rarity is the data component minecraft:rarity (Java Rarity).
// ID returns the registry name of the component.
func (Rarity) ID() string { return "minecraft:rarity" }

var _ DataComponent = (*Rarity)(nil)
