// Code generated by gen/gen_components.go from 26.3/packet_schema.json; DO NOT EDIT.
package component

import (
	"github.com/mj41/go-mc26/wire"
	"io"
)

// Recipes is the data component minecraft:recipes.
type Recipes struct{ Value wire.NBT }

func (v *Recipes) ReadFrom(r io.Reader) (int64, error) { return v.Value.ReadFrom(r) }
func (v Recipes) WriteTo(w io.Writer) (int64, error)   { return v.Value.WriteTo(w) }

// ID returns the registry name of the component.
func (Recipes) ID() string { return "minecraft:recipes" }

var _ DataComponent = (*Recipes)(nil)
