// Code generated by gen/gen_components.go from 26.1/packet_schema.json; DO NOT EDIT.
package component

import (
	"io"
)

// ShulkerColor is the data component minecraft:shulker/color.
// Value: DyeColor.
type ShulkerColor struct{ Value DyeColor }

func (v *ShulkerColor) ReadFrom(r io.Reader) (int64, error) { return v.Value.ReadFrom(r) }
func (v ShulkerColor) WriteTo(w io.Writer) (int64, error)   { return v.Value.WriteTo(w) }

// ID returns the registry name of the component.
func (ShulkerColor) ID() string { return "minecraft:shulker/color" }

var _ DataComponent = (*ShulkerColor)(nil)
