// Code generated by gen/gen_components.go from 26.3/packet_schema.json; DO NOT EDIT.
package component

import (
	"github.com/mj41/go-mc26/chat"
	pk "github.com/mj41/go-mc26/net/packet"
	"io"
)

// SignTextFront is the data component minecraft:sign_text_front (Java SignText).
type SignTextFront struct {
	Messages                         chat.Message
	FilteredMessagesForSerialization pk.Option[chat.Message, *chat.Message]
	Color                            DyeColor
	HasGlowingText                   pk.Boolean
}

func (v *SignTextFront) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Messages, &v.FilteredMessagesForSerialization, &v.Color, &v.HasGlowingText}.ReadFrom(r)
}

func (v SignTextFront) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Messages, v.FilteredMessagesForSerialization, v.Color, v.HasGlowingText}.WriteTo(w)
}

// ID returns the registry name of the component.
func (SignTextFront) ID() string { return "minecraft:sign_text_front" }

var _ DataComponent = (*SignTextFront)(nil)
