// Code generated by gen/gen_components.go from 26.3/packet_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/mj41/go-mc26/net/packet"
	"io"
)

// SulfurCubeContent is the data component minecraft:sulfur_cube_content (Java ItemStackTemplate).
type SulfurCubeContent struct {
	Item       pk.VarInt // holder in item
	Count      pk.VarInt
	Components Patch
}

func (v *SulfurCubeContent) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Item, &v.Count, &v.Components}.ReadFrom(r)
}

func (v SulfurCubeContent) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Item, v.Count, v.Components}.WriteTo(w)
}

// ID returns the registry name of the component.
func (SulfurCubeContent) ID() string { return "minecraft:sulfur_cube_content" }

var _ DataComponent = (*SulfurCubeContent)(nil)
