// Code generated by gen/gen_components.go from 26.2/packet_schema.json; DO NOT EDIT.
package component

import (
	"github.com/mj41/go-mc26/wire"
	"io"
)

// SuspiciousStewEffects is the data component minecraft:suspicious_stew_effects.
type SuspiciousStewEffects struct {
	Value wire.List[SuspiciousStewEffectsEntry, *SuspiciousStewEffectsEntry]
}

func (v *SuspiciousStewEffects) ReadFrom(r io.Reader) (int64, error) { return v.Value.ReadFrom(r) }
func (v SuspiciousStewEffects) WriteTo(w io.Writer) (int64, error)   { return v.Value.WriteTo(w) }

// ID returns the registry name of the component.
func (SuspiciousStewEffects) ID() string { return "minecraft:suspicious_stew_effects" }

var _ DataComponent = (*SuspiciousStewEffects)(nil)
