// Code generated by gen/gen_components.go from 26.2/packet_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/mj41/go-mc26/net/packet"
	"io"
)

// SwingAnimation is the data component minecraft:swing_animation (Java SwingAnimation).
type SwingAnimation struct {
	Type     SwingAnimationType
	Duration pk.VarInt
}

func (v *SwingAnimation) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Type, &v.Duration}.ReadFrom(r)
}

func (v SwingAnimation) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Type, v.Duration}.WriteTo(w)
}

// ID returns the registry name of the component.
func (SwingAnimation) ID() string { return "minecraft:swing_animation" }

var _ DataComponent = (*SwingAnimation)(nil)
