// Code generated by gen/gen_components.go from 26.1/packet_schema.json; DO NOT EDIT.
package component

import (
	"io"
)

// TropicalFishPatternColor is the data component minecraft:tropical_fish/pattern_color.
// Value: DyeColor.
type TropicalFishPatternColor struct{ Value DyeColor }

func (v *TropicalFishPatternColor) ReadFrom(r io.Reader) (int64, error) { return v.Value.ReadFrom(r) }
func (v TropicalFishPatternColor) WriteTo(w io.Writer) (int64, error)   { return v.Value.WriteTo(w) }

// ID returns the registry name of the component.
func (TropicalFishPatternColor) ID() string { return "minecraft:tropical_fish/pattern_color" }

var _ DataComponent = (*TropicalFishPatternColor)(nil)
