// Code generated by gen/gen_components.go from 26.3/packet_schema.json; DO NOT EDIT.
package component

// TropicalFishPattern is the data component minecraft:tropical_fish/pattern (Java TropicalFish$Pattern).
// ID returns the registry name of the component.
func (TropicalFishPattern) ID() string { return "minecraft:tropical_fish/pattern" }

var _ DataComponent = (*TropicalFishPattern)(nil)
