// Code generated by gen/gen_components.go from 26.1/packet_schema.json; DO NOT EDIT.
package component

import (
	"io"
)

// Unbreakable is the data component minecraft:unbreakable.
type Unbreakable struct{}

func (*Unbreakable) ReadFrom(io.Reader) (int64, error) { return 0, nil }
func (Unbreakable) WriteTo(io.Writer) (int64, error)   { return 0, nil }

// ID returns the registry name of the component.
func (Unbreakable) ID() string { return "minecraft:unbreakable" }

var _ DataComponent = (*Unbreakable)(nil)
