// Code generated by gen/gen_components.go from 26.1/packet_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/mj41/go-mc26/net/packet"
	"io"
)

// UseRemainder is the data component minecraft:use_remainder (Java UseRemainder).
type UseRemainder struct {
	ConvertInto ItemStackTemplate
}

func (v *UseRemainder) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.ConvertInto}.ReadFrom(r)
}

func (v UseRemainder) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.ConvertInto}.WriteTo(w)
}

// ID returns the registry name of the component.
func (UseRemainder) ID() string { return "minecraft:use_remainder" }

var _ DataComponent = (*UseRemainder)(nil)
