// Code generated by gen/gen_components.go from 26.2/packet_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/mj41/go-mc26/net/packet"
	"io"
)

// VillagerVariant is the data component minecraft:villager/variant.
// Value: holder in villager_type.
type VillagerVariant struct{ Value pk.VarInt }

func (v *VillagerVariant) ReadFrom(r io.Reader) (int64, error) { return v.Value.ReadFrom(r) }
func (v VillagerVariant) WriteTo(w io.Writer) (int64, error)   { return v.Value.WriteTo(w) }

// ID returns the registry name of the component.
func (VillagerVariant) ID() string { return "minecraft:villager/variant" }

var _ DataComponent = (*VillagerVariant)(nil)
