// Code generated by gen/gen_components.go from 26.3/packet_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/mj41/go-mc26/net/packet"
	"io"
)

// VillagerFood is the data component minecraft:villager_food (Java VillagerFood).
type VillagerFood struct {
	Nutrition pk.VarInt
}

func (v *VillagerFood) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.Nutrition}.ReadFrom(r)
}

func (v VillagerFood) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.Nutrition}.WriteTo(w)
}

// ID returns the registry name of the component.
func (VillagerFood) ID() string { return "minecraft:villager_food" }

var _ DataComponent = (*VillagerFood)(nil)
