// Code generated by gen/gen_components.go from 26.1/packet_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/mj41/go-mc26/net/packet"
	"io"
)

// Weapon is the data component minecraft:weapon (Java Weapon).
type Weapon struct {
	ItemDamagePerAttack       pk.VarInt
	DisableBlockingForSeconds pk.Float
}

func (v *Weapon) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&v.ItemDamagePerAttack, &v.DisableBlockingForSeconds}.ReadFrom(r)
}

func (v Weapon) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{v.ItemDamagePerAttack, v.DisableBlockingForSeconds}.WriteTo(w)
}

// ID returns the registry name of the component.
func (Weapon) ID() string { return "minecraft:weapon" }

var _ DataComponent = (*Weapon)(nil)
