// Code generated by gen/gen_packets.go from 26.1/packet_schema.json; DO NOT EDIT.
package component

import (
	"bytes"
	"fmt"
	"io"

	pk "github.com/mj41/go-mc26/net/packet"
	"github.com/mj41/go-mc26/wire"
)

var _ = io.EOF

// Typed is Java TypedDataComponent: a component type id and the value that type selects,
// which NewComponent makes.
type Typed struct {
	Type  pk.VarInt // registry data_component_type
	Value DataComponent
}

func (v *Typed) ReadFrom(r io.Reader) (n int64, err error) {
	if n, err = v.Type.ReadFrom(r); err != nil {
		return
	}
	if v.Value = NewComponent(int32(v.Type)); v.Value == nil {
		return n, fmt.Errorf("component %d: this version has no such type", v.Type)
	}
	m, err := v.Value.ReadFrom(r)
	return n + m, err
}

func (v Typed) WriteTo(w io.Writer) (n int64, err error) {
	if n, err = v.Type.WriteTo(w); err != nil {
		return
	}
	value := v.Value
	if value == nil {
		if value = NewComponent(int32(v.Type)); value == nil {
			return n, fmt.Errorf("component %d: this version has no such type", v.Type)
		}
	}
	m, err := value.WriteTo(w)
	return n + m, err
}

// DelimitedTyped is Java DataComponentPatch$3Entry: a component type id and the value that type selects,
// which NewComponent makes. The value carries its length in bytes, so a reader can
// step over a component it does not know; such a value keeps its bytes in Raw and is
// written back unchanged.
type DelimitedTyped struct {
	Type  pk.VarInt // registry data_component_type
	Value DataComponent
	Raw   []byte // set when Value is nil: a component this version does not know
}

func (v *DelimitedTyped) ReadFrom(r io.Reader) (n int64, err error) {
	var size pk.VarInt
	if n, err = (pk.Tuple{&v.Type, &size}).ReadFrom(r); err != nil {
		return
	}
	if size < 0 {
		return n, fmt.Errorf("component %d: negative length %d", v.Type, size)
	}
	body := make([]byte, int(size))
	m, err := io.ReadFull(r, body)
	n += int64(m)
	if err != nil {
		return n, err
	}
	v.Value, v.Raw = NewComponent(int32(v.Type)), nil
	if v.Value == nil {
		v.Raw = body
		return n, nil
	}
	if _, err := v.Value.ReadFrom(bytes.NewReader(body)); err != nil {
		return n, fmt.Errorf("component %d: %w", v.Type, err)
	}
	return n, nil
}

func (v DelimitedTyped) WriteTo(w io.Writer) (n int64, err error) {
	body := v.Raw
	if v.Value != nil {
		var buf bytes.Buffer
		if _, err = v.Value.WriteTo(&buf); err != nil {
			return 0, err
		}
		body = buf.Bytes()
	}
	if n, err = (pk.Tuple{v.Type, pk.VarInt(len(body))}).WriteTo(w); err != nil {
		return
	}
	m, err := w.Write(body)
	return n + int64(m), err
}

// Patch is Java DataComponentPatch.
type Patch struct {
	PositiveCount pk.VarInt
	NegativeCount pk.VarInt
	Positive      wire.Counted[Typed, *Typed]         // as many entries as PositiveCount says
	Negative      wire.Counted[pk.VarInt, *pk.VarInt] // as many entries as NegativeCount says
}

func (v *Patch) ReadFrom(r io.Reader) (n int64, err error) {
	var m int64
	m, err = pk.Tuple{&v.PositiveCount, &v.NegativeCount}.ReadFrom(r)
	n += m
	if err != nil {
		return n, err
	}
	if v.PositiveCount != 0 || v.NegativeCount != 0 {
		m, err = pk.Tuple{wire.CountedOf(&v.Positive, int(v.PositiveCount)), wire.CountedOf(&v.Negative, int(v.NegativeCount))}.ReadFrom(r)
		n += m
		if err != nil {
			return n, err
		}
	}
	return n, nil
}

func (v Patch) WriteTo(w io.Writer) (n int64, err error) {
	var m int64
	m, err = pk.Tuple{v.PositiveCount, v.NegativeCount}.WriteTo(w)
	n += m
	if err != nil {
		return n, err
	}
	if v.PositiveCount != 0 || v.NegativeCount != 0 {
		m, err = pk.Tuple{wire.CountedOf(&v.Positive, int(v.PositiveCount)), wire.CountedOf(&v.Negative, int(v.NegativeCount))}.WriteTo(w)
		n += m
		if err != nil {
			return n, err
		}
	}
	return n, nil
}

// DelimitedPatch is Java DataComponentPatch.
type DelimitedPatch struct {
	PositiveCount pk.VarInt
	NegativeCount pk.VarInt
	Positive      wire.Counted[DelimitedTyped, *DelimitedTyped] // as many entries as PositiveCount says
	Negative      wire.Counted[pk.VarInt, *pk.VarInt]           // as many entries as NegativeCount says
}

func (v *DelimitedPatch) ReadFrom(r io.Reader) (n int64, err error) {
	var m int64
	m, err = pk.Tuple{&v.PositiveCount, &v.NegativeCount}.ReadFrom(r)
	n += m
	if err != nil {
		return n, err
	}
	if v.PositiveCount != 0 || v.NegativeCount != 0 {
		m, err = pk.Tuple{wire.CountedOf(&v.Positive, int(v.PositiveCount)), wire.CountedOf(&v.Negative, int(v.NegativeCount))}.ReadFrom(r)
		n += m
		if err != nil {
			return n, err
		}
	}
	return n, nil
}

func (v DelimitedPatch) WriteTo(w io.Writer) (n int64, err error) {
	var m int64
	m, err = pk.Tuple{v.PositiveCount, v.NegativeCount}.WriteTo(w)
	n += m
	if err != nil {
		return n, err
	}
	if v.PositiveCount != 0 || v.NegativeCount != 0 {
		m, err = pk.Tuple{wire.CountedOf(&v.Positive, int(v.PositiveCount)), wire.CountedOf(&v.Negative, int(v.NegativeCount))}.WriteTo(w)
		n += m
		if err != nil {
			return n, err
		}
	}
	return n, nil
}

// SlotData is Java ItemStack.
type SlotData struct {
	Count      pk.VarInt
	Item       pk.VarInt // holder in item
	Components Patch
}

func (v *SlotData) ReadFrom(r io.Reader) (n int64, err error) {
	var m int64
	m, err = pk.Tuple{&v.Count}.ReadFrom(r)
	n += m
	if err != nil {
		return n, err
	}
	if v.Count > 0 {
		m, err = pk.Tuple{&v.Item, &v.Components}.ReadFrom(r)
		n += m
		if err != nil {
			return n, err
		}
	}
	return n, nil
}

func (v SlotData) WriteTo(w io.Writer) (n int64, err error) {
	var m int64
	m, err = pk.Tuple{v.Count}.WriteTo(w)
	n += m
	if err != nil {
		return n, err
	}
	if v.Count > 0 {
		m, err = pk.Tuple{v.Item, v.Components}.WriteTo(w)
		n += m
		if err != nil {
			return n, err
		}
	}
	return n, nil
}

// UntrustedSlotData is Java ItemStack.
type UntrustedSlotData struct {
	Count      pk.VarInt
	Item       pk.VarInt // holder in item
	Components DelimitedPatch
}

func (v *UntrustedSlotData) ReadFrom(r io.Reader) (n int64, err error) {
	var m int64
	m, err = pk.Tuple{&v.Count}.ReadFrom(r)
	n += m
	if err != nil {
		return n, err
	}
	if v.Count > 0 {
		m, err = pk.Tuple{&v.Item, &v.Components}.ReadFrom(r)
		n += m
		if err != nil {
			return n, err
		}
	}
	return n, nil
}

func (v UntrustedSlotData) WriteTo(w io.Writer) (n int64, err error) {
	var m int64
	m, err = pk.Tuple{v.Count}.WriteTo(w)
	n += m
	if err != nil {
		return n, err
	}
	if v.Count > 0 {
		m, err = pk.Tuple{v.Item, v.Components}.WriteTo(w)
		n += m
		if err != nil {
			return n, err
		}
	}
	return n, nil
}
