// Code generated by gen/gen_components.go from 26.3/packet_schema.json; DO NOT EDIT.
package component

import (
	pk "github.com/mj41/go-mc26/net/packet"
	"io"
)

// WolfSoundVariant is the data component minecraft:wolf/sound_variant.
// Value: holder in wolf_sound_variant.
type WolfSoundVariant struct{ Value pk.VarInt }

func (v *WolfSoundVariant) ReadFrom(r io.Reader) (int64, error) { return v.Value.ReadFrom(r) }
func (v WolfSoundVariant) WriteTo(w io.Writer) (int64, error)   { return v.Value.WriteTo(w) }

// ID returns the registry name of the component.
func (WolfSoundVariant) ID() string { return "minecraft:wolf/sound_variant" }

var _ DataComponent = (*WolfSoundVariant)(nil)
