// Code generated by gen/gen_components.go from 26.3/packet_schema.json; DO NOT EDIT.
package component

import (
	"github.com/mj41/go-mc26/wire"
	"io"
)

// WritableBookContent is the data component minecraft:writable_book_content.
type WritableBookContent struct {
	Value wire.List[Filterable, *Filterable]
}

func (v *WritableBookContent) ReadFrom(r io.Reader) (int64, error) { return v.Value.ReadFrom(r) }
func (v WritableBookContent) WriteTo(w io.Writer) (int64, error)   { return v.Value.WriteTo(w) }

// ID returns the registry name of the component.
func (WritableBookContent) ID() string { return "minecraft:writable_book_content" }

var _ DataComponent = (*WritableBookContent)(nil)
