// Code generated by gen/gen_packets.go from 26.1/packet_schema.json + packets.json; DO NOT EDIT.
// Package handshake holds the generated 26.1 packets of the handshake state.
package handshake

import (
	"io"

	"github.com/mj41/go-mc26/data/packetid"
	pk "github.com/mj41/go-mc26/net/packet"
	"github.com/mj41/go-mc26/protocol/types"
)

var (
	_ = io.EOF
	_ pk.Field
	_ types.Empty
)

// NewServerbound returns an empty handshake serverbound packet of the given id, or nil when this
// version has no such packet or it is not generated.
func NewServerbound(id packetid.ServerboundPacketID) pk.Field {
	switch id {
	case packetid.ServerboundHandshakeIntention:
		return new(ClientIntention)
	}
	return nil
}

// ClientIntention is serverbound/minecraft:intention (0x00), Java ClientIntentionPacket.
type ClientIntention struct {
	ProtocolVersion pk.VarInt
	HostName        pk.String
	Port            pk.UnsignedShort
	Intention       types.ClientIntent
}

// PacketID returns the serverbound id of ClientIntention.
func (ClientIntention) PacketID() packetid.ServerboundPacketID {
	return packetid.ServerboundHandshakeIntention
}

func (p *ClientIntention) ReadFrom(r io.Reader) (int64, error) {
	return pk.Tuple{&p.ProtocolVersion, &p.HostName, &p.Port, &p.Intention}.ReadFrom(r)
}

func (p ClientIntention) WriteTo(w io.Writer) (int64, error) {
	return pk.Tuple{p.ProtocolVersion, p.HostName, p.Port, p.Intention}.WriteTo(w)
}
