// Code generated by gen/gen_constants.go from 26.2/constants.json; DO NOT EDIT.

// Package constants holds compile-time constants of Minecraft 26.2's classes that
// the library's hand-written code follows: the inventory slot layout, the section
// geometry, the level limits, the NBT keys of living entities.
package constants

// SectionPos (net.minecraft.core.SectionPos)
const (
	SectionPosPackedXLength     = 22
	SectionPosPackedXMask       = 4194303
	SectionPosPackedYLength     = 20
	SectionPosPackedYMask       = 1048575
	SectionPosPackedZLength     = 22
	SectionPosPackedZMask       = 4194303
	SectionPosRelativeXShift    = 8
	SectionPosRelativeYShift    = 0
	SectionPosRelativeZShift    = 4
	SectionPosSectionBits       = 4
	SectionPosSectionBlockCount = 4096
	SectionPosSectionHalfSize   = 8
	SectionPosSectionMask       = 15
	SectionPosSectionMaxIndex   = 15
	SectionPosSectionSize       = 16
	SectionPosXOffset           = 42
	SectionPosYOffset           = 0
	SectionPosZOffset           = 20
)

// LivingEntity (net.minecraft.world.entity.LivingEntity)
const (
	LivingEntityArmorSlotOffset                            = 100
	LivingEntityBaseHorizontalAirDrag                      = 0.91
	LivingEntityBaseJumpPower                              = 0.42
	LivingEntityBaseSwimSpeed                              = 0.02
	LivingEntityBaseVerticalAirDrag                        = 0.98
	LivingEntityBodyArmorOffset                            = 105
	LivingEntityClimbingVerticalSpeed                      = 0.2
	LivingEntityCurrentImpulseContextResetGraceTimeTicks   = 40
	LivingEntityDamageSourceTimeout                        = 40
	LivingEntityDeathDuration                              = 20
	LivingEntityDefaultBabyScale                           = 0.5
	LivingEntityDefaultBaseGravity                         = 0.08
	LivingEntityDefaultCurrentImpulseContextResetGraceTime = 0
	LivingEntityDefaultKnockback                           = 0.4
	LivingEntityDolphinsGraceWaterDrag                     = 0.96
	LivingEntityElytraHorizontalAirDrag                    = 0.99
	LivingEntityElytraVerticalAirDrag                      = 0.98
	LivingEntityEquipmentSlotOffset                        = 98
	LivingEntityExtraRenderCullingSizeWithBigHat           = 0.5
	LivingEntityFlyingAirDrag                              = 0.91
	LivingEntityFlyingLavaDrag                             = 0.5
	LivingEntityFlyingVerticalAirDrag                      = 0.91
	LivingEntityFlyingWaterDrag                            = 0.8
	LivingEntityFreeFallEventsPerElytraBreak               = 2
	LivingEntityHurtDurationTicks                          = 10
	LivingEntityInputFriction                              = 0.98
	LivingEntityInvulnerableDuration                       = 20
	LivingEntityLavaDrag                                   = 0.5
	LivingEntityLavaShallowVerticalDrag                    = 0.8
	LivingEntityLivingEntityFlagIsUsing                    = 1
	LivingEntityLivingEntityFlagOffHand                    = 2
	LivingEntityLivingEntityFlagSpinAttack                 = 4
	LivingEntityMaxLineOfSightTestRange                    = 128
	LivingEntityMinMovementDistance                        = 0.003
	LivingEntityParticleFrequencyWhenInvisible             = 15
	LivingEntityPlayerHurtExperienceTime                   = 100
	LivingEntitySaddleOffset                               = 106
	LivingEntitySprintingWaterDrag                         = 0.9
	LivingEntitySwimmingVerticalSpeed                      = 0.04
	LivingEntitySwimAmountPerTick                          = 0.09
	LivingEntityTagActiveEffects                           = "active_effects"
	LivingEntityTagAttributes                              = "attributes"
	LivingEntityTagBrain                                   = "Brain"
	LivingEntityTagDeathTime                               = "DeathTime"
	LivingEntityTagEquipment                               = "equipment"
	LivingEntityTagFallFlying                              = "FallFlying"
	LivingEntityTagHealth                                  = "Health"
	LivingEntityTagHurtTime                                = "HurtTime"
	LivingEntityTagSleepingPos                             = "sleeping_pos"
	LivingEntityTicksPerElytraFreeFallEvent                = 10
	LivingEntityWaterDrag                                  = 0.8
)

// Inventory (net.minecraft.world.entity.player.Inventory)
const (
	InventoryInventorySize   = 36
	InventoryNotFoundIndex   = -1
	InventoryPopTimeDuration = 5
	InventorySelectionSize   = 9
	InventorySlotBodyArmor   = 41
	InventorySlotOffhand     = 40
	InventorySlotSaddle      = 42
)

// Player (net.minecraft.world.entity.player.Player)
const (
	PlayerCraftingSlotOffset                          = 500
	PlayerCreativeEntityInteractionRangeModifierValue = 2
	PlayerDefaultBlockInteractionRange                = 4.5
	PlayerDefaultEntityInteractionRange               = 3
	PlayerDefaultExperienceLevel                      = 0
	PlayerDefaultExperienceProgress                   = 0
	PlayerDefaultScore                                = 0
	PlayerDefaultSelectedSlot                         = 0
	PlayerDefaultSleepTimer                           = 0
	PlayerDefaultTotalExperience                      = 0
	PlayerEnderSlotOffset                             = 200
	PlayerHeldItemSlot                                = 499
	PlayerMaxHealth                                   = 20
	PlayerNoEnchantmentSeed                           = 0
	PlayerSleepDuration                               = 100
	PlayerWakeUpDuration                              = 10
)

// AbstractContainerMenu (net.minecraft.world.inventory.AbstractContainerMenu)
const (
	AbstractContainerMenuCarriedSlotSize          = 2147483647
	AbstractContainerMenuQuickcraftHeaderContinue = 1
	AbstractContainerMenuQuickcraftHeaderEnd      = 2
	AbstractContainerMenuQuickcraftHeaderStart    = 0
	AbstractContainerMenuQuickcraftTypeCharitable = 0
	AbstractContainerMenuQuickcraftTypeClone      = 2
	AbstractContainerMenuQuickcraftTypeGreedy     = 1
	AbstractContainerMenuSlotsPerRow              = 9
	AbstractContainerMenuSlotClickedOutside       = -999
	AbstractContainerMenuSlotSize                 = 18
)

// InventoryMenu (net.minecraft.world.inventory.InventoryMenu)
const (
	InventoryMenuArmorSlotCount     = 4
	InventoryMenuArmorSlotEnd       = 9
	InventoryMenuArmorSlotStart     = 5
	InventoryMenuContainerId        = 0
	InventoryMenuCraftingGridHeight = 2
	InventoryMenuCraftingGridWidth  = 2
	InventoryMenuCraftSlotCount     = 4
	InventoryMenuCraftSlotEnd       = 5
	InventoryMenuCraftSlotStart     = 1
	InventoryMenuInvSlotEnd         = 36
	InventoryMenuInvSlotStart       = 9
	InventoryMenuResultSlot         = 0
	InventoryMenuShieldSlot         = 45
	InventoryMenuUseRowSlotEnd      = 45
	InventoryMenuUseRowSlotStart    = 36
)

// Level (net.minecraft.world.level.Level)
const (
	LevelAcrossTheWholeWorld    = 60000000
	LevelLongParticleClipRange  = 512
	LevelMaxBrightness          = 15
	LevelMaxEntitySpawnY        = 20000000
	LevelMaxLevelSize           = 30000000
	LevelMinEntitySpawnY        = -20000000
	LevelShortParticleClipRange = 32
)

// LevelChunkSection (net.minecraft.world.level.chunk.LevelChunkSection)
const (
	LevelChunkSectionBiomeContainerBits = 2
)
